### ISSUE TITLE
Install as app whilst b2g running

### ISSUE THREAD

**Issue by andymckay** [mozilla/r2d2b2g#1]
If you do this, nothing happens. Would be nice to have a "go restart b2g" message.

**Comment by mykmelez** [comment]
Indeed! At the very least, we should let you know to restart B2G. (Ideally, we should restart it ourselves or figure out how to install an app without requiring a restart.)

**Comment by mykmelez** [comment]
As of commit 6eb2f6afb484d678711fa5ea98188062816fbeb3, the addon restarts B2G Desktop automagically!
