### ISSUE TITLE
Can't Add Web App to Home Screen from Mobile Browser

### ISSUE THREAD

**Issue by japzone** [mozilla/r2d2b2g#103]
I'm trying to add the Pulse.me Web App to the Home Screen but nothing happens when I click the "Add to HomeScreen" button in the "Add to HomeScreen" menu. The Error Console shows this:
![Error Console](http://i.imgur.com/k5r1B.png)

I've tried adding other Web Sites to the HomeScreen and None of them work. After a few attempts the Simulator crashes along with the Error Console.

System:
OS: Ubuntu 11.04
Firefox: v16.0.1
Simulator: v0.7

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
