### ISSUE TITLE
Bing ? And if i want to change it

### ISSUE THREAD

**Issue by saerdryl** [mozilla/r2d2b2g#104]
hi 
I try to chnage my search engine on firefox but i can t do it. pershaps i don t find the way or we can t change...

Anyway i want to change it so add some option please :)

Thx

**Comment by tofumatt** [comment]
This is the repository for the Firefox OS simulator; I believe you can change the search engine on the phone, but this repository is just for the simulator.

You may want to check out the Mozilla/Gaia repository, or check out Firefox Support for help.
- tofumatt (Sent from mobile)
