### ISSUE TITLE
Set the time format

### ISSUE THREAD

**Issue by pierrick-marie** [mozilla/r2d2b2g#107]
I can't set the time format. The default format is "hh:mm PM/AM" and I would like something like : "0-23:mm"

Into the settings menu part "Date & Time", I set manually the "Time zone" to Paris but the time format still "hh:mm PM/AM". I also looked into the part "Language & Region" but I found nothing to set the time format.

**Comment by hkgrild** [comment]
Also a little bug here : http://imageshack.us/scaled/landing/4/settingstimedate.png

2 texts supperposed

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
