### ISSUE TITLE
SMS - Real bug here [ScreenShot]

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#108]
my config: (win7, sp1, .net 3.5 4.0 4.5)
All java things installed for developper

---
## BUG DETAILS :

1) All texte not always showing up in the received list. The GMT.... can sometimes be wrapped to a second line... Why did you add that GMT thing... useless at his best point!

2) Text from message is OVER the date and time...

3) For a fresh install, you should remove all previous SMS (I have SMS and Calls from 11/01/2012...)

SMS BUG SCREENSHOT HERE : http://img526.imageshack.us/img526/4606/firefoxossmsbug.png

Home Screen Bugs SCREENSHOT HERE : http://img526.imageshack.us/img526/4264/firefoxoswtfhomescreen.png

Also my opinion is, 2 format for the time on Home screen... + GMT thing... 
Yeah, you guys are good developpers, you know how to do some cool things, but we really DON'T CARE about GMT... Do you really need to show us 3 differents time/date format? can't we choose the one we like? (ap, pm, 12/24h, show GMT....)

6:22 Fri
Nov 16
2012
18:22:00 (little timer here for the seconds at least.......)
GMT+0100
Friday Fri Nov 16 2012 18:23 (don't even change at the same time than the other one)
GMT+0100 November...

Guys, seriously?!? All that shit to tell me it's 6.22pm, Nov 16 (i know it's 2012 since it is for 11 months now -_-')
See, i tell the user same informations as this shitty homescreen, but with 2 lines!
Come on, remove some lines, look at the time thing that doesn't change at the same time(or don't if you just remove some lines :D!)

Thanks for reading!

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
