### ISSUE TITLE
[Enhancement] Opening a menu that as never been opened... some visual 'bugs'

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#109]
So, i'm going to "Settings"

By clicking on each submenu, we can see that the new window that it's opening, sometimes it looks like it was already loaded in background (so the Settings window slide to left, and background window don't slide), sometimes it's normal (both windows sliding together..)

Check it out ;)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
