### ISSUE TITLE
[Enhancement] Region in settings doesn't match GMT ...

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#110]
I just choosed my language and region. By default, the Region is Brazil...
I Didn't know Brazil was GMT +0100 ;)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
