### ISSUE TITLE
[Enhancement] Settings -> Sounds -> Message -> Bug playing the sound file...

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#111]
(nothing is playing except the 3rd sound...)

First, i choose the 3rd sound.
Then, i click the 'Old School' one, and clicking real quick on the 3rd one again... 
'Old School' is still selected, but the 3rd one is playing

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
