### ISSUE TITLE
[Enhancement] Settings -> Wifi -> Manage Networks ... 

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#112]
When i choose a secured WiFi, there is a margin-top of 20 px that screw the template for that menu

---

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
