### ISSUE TITLE
[bug?] Settings -> Display -> TimeOut 

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#113]
---
## EDIT: my bad ^^ looks like normal for this one :)

When i click on the '1 minute'  timeout scrollbox, the 'Display' menu's Image is showing in background, and 'Display' texte also... It's not doing it with other menus?

---

**Comment by hkgrild** [comment]
Also, if I unselect the 'Adjust Automatically', there is 2 SlideBar, the one in the bottom is not fully showing up !
So in don't even know what this is for ^^.

---

## Screenshot here : http://img191.imageshack.us/img191/5843/firefoxosdisplaymanuall.png

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
