### ISSUE TITLE
[Bugs / Enhancement] Calendar

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#115]
First of all, the 'Top Left button'  (that offer the Offline Calendar) is not fully visible.

The 'Week' Button:
Just try it guys, the content doesn't fit (AT ALL!!!!!) on the cell... Seriously? That bugged?
AND REMOVE THAT FUCKING GMT !!! WE DON'T CARE !!!!!!

Then try the 'Day' Button
Again, nothing is showed properly... Texts are supperposed, one hover the other....
Where the bug come from? The GMT thing, AGAIN! ...

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
