### ISSUE TITLE
[Enhancement] Geolocation Test -> Text not centered

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#116]
Just a little thing here.. text is too much on the right side...

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
