### ISSUE TITLE
[Enhancement] Calculator , clic on the 'C' Button

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#117]
The image when i press on the 'C' button (the blue image) doesn't fit the button

**Comment by autonome** [comment]
Hi! I can't seem to find a way to send you a message, so posting here:

Please file bugs for Firefox OS here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia

This repo is _only_ for the Simulator code that wraps it up and packages it in Firefox.

Thanks!
