### ISSUE TITLE
[Enhancement] Install a Flash plugin with firefox!!!!!

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#118]
You guys really should think about 'pre' installing a Flash Player with FireFox! 
Also, don't forget to make it updatable ...

**Comment by mykmelez** [comment]
Thanks for reporting the problem! But this issue tracker is actually just for the Simulator code that bundles Firefox OS to provide a test environment for app developers. Report issues with Firefox OS itself in [its issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
