### ISSUE TITLE
facebook login page password field bug Windows

### ISSUE THREAD

**Issue by sangsang** [mozilla/r2d2b2g#121]
When trying to put the facebook account password, the page starts to move up and down.

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
