### ISSUE TITLE
PenguinPop game not screen compatible

### ISSUE THREAD

**Issue by SSk123** [mozilla/r2d2b2g#122]
The game does not fit in the emulator screen ,  same is the problem with TowerJelly game

**Comment by clips-ennovate** [comment]
I also noticed this bug. 
http://i45.tinypic.com/30hvqk2.jpg

Running the simulator on Windows server 2008 R2

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
