### ISSUE TITLE
Simulator not working properly on lubuntu 12.10 Firefox 19.0a1 (2012-11-07)

### ISSUE THREAD

**Issue by thomasysliu** [mozilla/r2d2b2g#123]
The Firefox nighty is from PPA

deb http://ppa.launchpad.net/ubuntu-mozilla-daily/ppa/ubuntu precise main
deb-src http://ppa.launchpad.net/ubuntu-mozilla-daily/ppa/ubuntu precise main

The simulator just not start any new window. And the switch turn off soon after it start.

**Comment by thomasysliu** [comment]
It also happened on Aurora

The error message is 
/////
Running global cleanup code from study base classes.
info: r2d2b2g: Simulator.onMessage getIsRunning
info: r2d2b2g: Simulator.onMessage listApps
info: r2d2b2g: Simulator.sendListApps
info: r2d2b2g: Simulator.onMessage listTabs
info: r2d2b2g: Simulator.onMessage getPreference
info: r2d2b2g: Simulator.onMessage toggle
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
info: r2d2b2g: linux/b2g/b2g-bin terminated with 139

/////////////////

info: r2d2b2g: Simulator.onMessage toggle
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
info: r2d2b2g: linux/b2g/b2g-bin terminated with 139
Failed to open VDPAU backend libvdpau_nvidia.so: 無法開啟共用目的檔: 沒有此一檔案或目錄

**Comment by thomasysliu** [comment]
Crash gdb information

liu@thomas-laptop:~/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ ./b2g 
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
程式記憶體區段錯誤 (core dumped)
liu@thomas-laptop:~/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ 
liu@thomas-laptop:~/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ 
liu@thomas-laptop:~/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ gdb ./b2g 
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
For bug reporting instructions, please see:
http://bugs.launchpad.net/gdb-linaro/...
Reading symbols from /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g...(no debugging symbols found)...done.
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
No stack.
(gdb) 
No stack.
(gdb) 
No stack.
(gdb) run
Starting program: /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb4203b40 (LWP 4151)]
[New Thread 0xb3739b40 (LWP 4152)]
[New Thread 0xb24ffb40 (LWP 4153)]
[New Thread 0xb1afeb40 (LWP 4154)]
[New Thread 0xb0effb40 (LWP 4155)]
[New Thread 0xb04feb40 (LWP 4156)]
[New Thread 0xaf4ffb40 (LWP 4157)]
[New Thread 0xaeafeb40 (LWP 4158)]
[New Thread 0xaddffb40 (LWP 4159)]
[New Thread 0xad3feb40 (LWP 4160)]
[New Thread 0xac9fdb40 (LWP 4161)]
[New Thread 0x9e8ffb40 (LWP 4163)]
[New Thread 0x9defeb40 (LWP 4164)]
[New Thread 0x9cd0eb40 (LWP 4165)]
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157

Program received signal SIGSEGV, Segmentation fault.
0xb7fcbe9b in mozalloc_abort(char const_) ()
   from /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/libmozalloc.so
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0xb7fcbe9b in mozalloc_abort(char const_) ()
   from /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/libmozalloc.so
#1  0xb639961c in NS_DebugBreak_P ()
   from /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/libxul.so
#2  0xb56fe973 in X11Error ()
   from /home/liu/.mozilla/firefox-trunk/ovqpozp5.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/libxul.so
#3  0xb2bc1b16 in ?? () from /usr/lib/i386-linux-gnu/libbonoboui-2.so.0
#4  0xb50a8acb in _XError () from /usr/lib/i386-linux-gnu/libX11.so.6
#5  0xb50a589d in ?? () from /usr/lib/i386-linux-gnu/libX11.so.6
#6  0xb50a6897 in _XReply () from /usr/lib/i386-linux-gnu/libX11.so.6
#7  0x9c26c387 in ?? () from /usr/lib/fglrx/libGL.so.1
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by thomasysliu** [comment]
I found that it seems relate to this issue
http://askubuntu.com/questions/81344/how-to-fix-error-with-ati-driver-error-of-failed-request

But it is hard to reproduce.

**Comment by mykmelez** [comment]
There's more info in [Ubuntu bug 293012](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/293012). It sounds like this is an issue in the proprietary _fglrx_ driver, and when it happens, all OpenGL apps fail, including the _glxinfo_ command and example apps like _glxgears_. Solutions in that bug include reinstalling _fglrx_ per the instructions in the [ATI Binary Driver Howto](https://help.ubuntu.com/community/BinaryDriverHowto/ATI) and uninstalling it and using the open-source drivers (which Ubuntu recommends).

Unfortunately, B2G Desktop depends on OpenGL, so we can't fix this in the Simulator. Your system needs to have a working OpenGL implementation to use the Simulator.

**Comment by mykmelez** [comment]
Closing, as this is an Ubuntu issue that we can't fix in the Simulator.
