### ISSUE TITLE
Make a workflow for Gaia localizers 

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#124]
This could involve pointing to an external Gaia folder to make changes.

Apps need to work, like Data Usage which is now a blank screen.

See in `gaia/locales/README.md` for additional references.

Thanks to @jincreator.

**Comment by mykmelez** [comment]
I recently landed some build system enhancements for building with additional locales. I think those enhancements satisfy the goal here of making it possible for Gaia localizers to use the Simulator to develop their locales. Here are the instructions for building, running, and packaging with all locales, which you can then modify as appropriate to do so for a single locale:

```
git clone git://github.com/mozilla/r2d2b2g.git
cd r2d2b2g/
git submodule init
git submodule update
export LOCALES_FILE=${PWD}/gaia/locales/languages_all.json
make locales # clones/updates relevant locale repositories from hg.mozilla.org
make build
```

To test the build (starts Firefox with addon preinstalled), do:

```
make run
```

Then, to produce a redistributable package (at addon/r2d2b2g.xpi), do:

```
make package
```

On Linux, however, make again before packaging with B2G_PLATFORM set to the _other_ bit depth (i.e. the one that is _not_ your computer's bit depth) to produce a package that works on both 32-bit and 64-bit Linux systems:

```
# On 32-bit Linux, also build 64-bit:
B2G_PLATFORM=linux64 make build
# On 64-bit Linux, also build 32-bit:
B2G_PLATFORM=linux make build
```

The Simulator's Makefile assumes _LOCALE_BASEDIR_ is _${PWD}/gaia-l10n_ for `make locales` and `make build`, but you can set it to a different value.

On Windows, I built with MozillaBuild and mintty. Building should work without mintty, but it probably won't work without MozillaBuild.
