### ISSUE TITLE
Can't open twitter or facebook app

### ISSUE THREAD

**Issue by erikvold** [mozilla/r2d2b2g#126]
When I start the simulator and swipe to the left of the home screen I see the social group of apps, I click that and the group opens, then I can't click on the apps like twitter or facebook, and the back button doesn't work either.

**Comment by mykmelez** [comment]
That's the everything.me app, which lets you install other apps. I'm not sure why it isn't working, but the Simulator is designed to provide a test environment for app developers, and we don't typically address issues with using features of Firefox OS that don't impact testing of your own apps, as those are properly Firefox OS issues. You can report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator.
