### ISSUE TITLE
mail-box doesnt refresh

### ISSUE THREAD

**Issue by shreyas1988** [mozilla/r2d2b2g#128]
after deleting a mail from my inbox(or any folders) the new list of emails is not updated.

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
