### ISSUE TITLE
stop advertising Escape keyboard shortcut for removed Back action

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#13]
The Helper tells users to use the Escape key to go Back, but B2G recently removed the Back action, so the Helper should stop advertising that keyboard shortcut.

**Comment by fwenzel** [comment]
Is there any way to go back on B2G desktop then? Or will the app have to do that in its own UI?

**Comment by mykmelez** [comment]
@fabricedesre can confirm, but I think there is no built-in way to go back in any manifestation of B2G, including on the phone, which will not have a Back button. Instead, apps that want to provide back/forward navigation will have to do so in their own UI, as does the Firefox browser on the phone.

**Comment by fabricedesre** [comment]
That's correct! Home takes you back to the homescreen, and a long-press on Home opens the task app switcher.

**Comment by mykmelez** [comment]
Looks like that commit did indeed fix the issue!
