### ISSUE TITLE
proxy setting?

### ISSUE THREAD

**Issue by wangweij** [mozilla/r2d2b2g#130]
I need a proxy to visit the Internet. My Firefox already has a setup but it seems the Firefox OS simulator does not honor it. Is there a separate place I can set?

**Comment by mykmelez** [comment]
Hmm, I'm not sure how to address configuring a proxy in the Simulator. One possibility is to manually copy proxy settings from your Firefox profile's prefs.js file to the Simulator profile's prefs.js file (which is inside your Firefox profile at extensions/r2d2b2g@mozilla.org/profile/).

**Comment by shia86** [comment]
I use FoxyProxy for nightly ,but firefox os doesn't support proxy?

**Comment by mykmelez** [comment]
@shia86: I think Firefox OS does support proxies via the same set of proxy configuration preferences that are available in Firefox. However, I'm not sure how best to support proxies in the Simulator. As a partial solution, perhaps we could automatically apply your Firefox proxy configuration to the Simulator when you first install it.

**Comment by Smalllily** [comment]
firefox OS browser does support the proxy which is same with the configure in IE..

**Comment by huangzhongming** [comment]
Thanks Smalllily provided the best solutions. That worked well. 

Cheers,

**Comment by shia86** [comment]
Sorry,I'm not clearly at Smalllily's solution. Can you give me more details,Thanks in advanced

**Comment by nickdesaulniers** [comment]
@shia86 , to find the proxy settings:
1. Start FFOS simulator
2. Open Settings app
3. Click Cellular & Data
4. Click Data Settings
5. Enter proxy credentials in HTTP proxy host & port.

If you can verify that this works, please let us know and close this issue.  Thanks!

**Comment by shia86** [comment]
Thanks.But I using a proxy in  localhost ,so I'm not sure if it's ok to add the 127.0.0.1 in proxy host.
When using the configure as seem as Foxyproxy , It seemed doesn't work in FFOS

Of course such occasion maybe a little strange ,so you can close this issue for convenience .

**Comment by huangzhongming** [comment]
可以在IE种设置代理。

**Comment by mykmelez** [comment]
@shia86 I suspect that it is ok to put 127.0.0.1 in the proxy host field, although I don't know for sure.

In any case, it sounds like this feature is supported natively in Gaia via Settings > Cellular & Data > Data settings, and that works sufficiently, so I'm going to close this issue. But please reopen if it turns out to be insufficient!
