### ISSUE TITLE
not have a task manager, games open in a size bigger than the phone screen

### ISSUE THREAD

**Issue by leandroruel** [mozilla/r2d2b2g#132]
must have a task manager to kill processes, and a option to add widgets to desktop.
and the games are opening ia a size bigger than the phone screen... =(

**Comment by fwenzel** [comment]
Are these two different issues? Please only report one issue per ticket, so they are easier to track.

**Comment by tofumatt** [comment]
It is possible to hold the home button and swipe up to "close app processes", same as on the phone, if that's what you are looking for. That's a feature of the OS, not the Simulator, but it should cover what you're looking for.
- tofumatt (Sent from mobile)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
