### ISSUE TITLE
remove Feedback app from Simulator

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#133]
The folks monitoring feedback for Firefox OS are being inundated with feedback from Simulator users. But the Simulator is not intended to be used for testing Firefox OS, only apps, and the Feedback app is intended to be used by folks dogfooding an actual device. So we should remove the Feedback app from the Simulator.

**Comment by victorb** [comment]
Maybe replace the Feedback app with another view that shows information that you should submit issues in the Github if you're not sure that the bug is related to Firefox OS and not emulator

**Comment by ghost** [comment]
If that's the case, there should be something that directs them to feeback on issues about the OS because it is definitely unclear.

**Comment by mykmelez** [comment]
I removed the Feedback app in commit 369acc8b703b080f439c6d1779893e8e0ac74319.

Note that the Help tab of the Manager provides a link to this issue tracker, and this is the right place to report issues with the Simulator, including issues with Firefox OS that affect use of the Simulator to test apps.

This tracker should not be used for reporting issues with Firefox OS that don't affect use of the Simulator to test apps (i.e. user issues with using Firefox OS), however, since the Simulator's sole purpose is to help app developers test their apps.

We could direct users to another method for reporting such issues, but I'm loathe to do so, since the Simulator is not intended for such use, and user issues in the Simulator don't necessarily exist in Firefox OS installations that are user-focused.

Nevertheless, it is possible to report such issues via the B2G/Gaia's Bugzilla issue tracker: https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia. And I will let folks know that when they report issues in this tracker.
