### ISSUE TITLE
keyboard doesn't dissappear when going back to homescreen

### ISSUE THREAD

**Issue by nightjack** [mozilla/r2d2b2g#135]
Discovored this bug when using the keyboard in firefox. The keyboard stays in the backround of the homescreen.

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
