### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by dmh902005** [mozilla/r2d2b2g#137]
wifi just continues to search for a connection

**Comment by mykmelez** [comment]
That should be ok, as the Simulator should still be able to use your computer's existing network connection to make requests. Or do you find that apps (like Firefox) running on the Simulator are unable to make network requests?

**Comment by mykmelez** [comment]
Closing due to a lack of response. But please reopen if you're still experiencing this behavior and it prevents you from using the Simulator to test apps!
