### ISSUE TITLE
Notification Bar crashes Simulator

### ISSUE THREAD

**Issue by dvenkatas** [mozilla/r2d2b2g#140]
Windows : 7 with SP installed
Firefox Version : 16.0.2
Version of Simulator : 0.7

When I try to pull down the notification area (Wifi buttons) etc., the simulator crashes.

**Comment by mykmelez** [comment]
Do you still see this problem with the latest version of the Simulator?

**Comment by mykmelez** [comment]
Closing due to a lack of response. But please reopen if you still see this problem!
