### ISSUE TITLE
Add ability to change prefs, ideally on the fly

### ISSUE THREAD

**Issue by gerv** [mozilla/r2d2b2g#142]
B2G has no interface like about:config. However, there are various prefs that it's very useful to be able to tweak for debugging purposes. E.g.  being able to change the user agent override prefs would be very, very helpful for the evangelism team to help them determine if problems they are seeing are UA-related.

Can the Simulator provide this function? The best way would be so you could change an arbitrary pref in a running instance via an about:config like interface. Almost as good would be the ability to view or change a pref, where you had to type the name. Slightly not as good as that would be if you had to restart B2G afterwards. But whatever you can manage is almost certainly easier than a recompile/reflash cycle!

**Comment by victorb** [comment]
Yes, that would be lovely. Issue #136 would benefit from it also.

**Comment by mykmelez** [comment]
Our goal is to build a test environment for app developers, so we're not focusing on features for other constituencies. But it should be possible to create a B2G Desktop extension that provides this functionality. The Simulator itself bundles a B2G Desktop extension that adds a toolbar to the bottom of the B2G window with a Home button that simulates the hardware Home button on a phone device.

So you could create an extension for B2G Desktop that adds a menu for selecting a UA string or even opens about:config in a new window (just like it's possible to open the Error Console in a new window in B2G Desktop by passing it the -jsconsole flag on the command line).

See the [prosthesis directory](https://github.com/mykmelez/r2d2b2g/tree/master/prosthesis) in the Simulator source code for an example.
