### ISSUE TITLE
"Try again" spelled incorrectly when unable to connect

### ISSUE THREAD

**Issue by pulkitanand** [mozilla/r2d2b2g#147]
On trying to login to marketplace, it tries to connect to login.persona.org/sign_in . On unable to connect, it shows a screen with options to "Close" or "Try again". "Try again" is spelled incorrectly as "Try agin".

Screenshot: http://s8.postimage.org/m7tl9u2v9/try_agin.jpg

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
