### ISSUE TITLE
Install crashes on Win 7 64 bit - Firefox 16.0.2

### ISSUE THREAD

**Issue by ckxion** [mozilla/r2d2b2g#148]
When I try to instrall I get the following popup error message

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: resource:///modules/XPIProvider.jsm:229

**Comment by mykmelez** [comment]
Thanks for reporting the problem! This is actually an issue in Firefox itself, which I have filed in Firefox's issue tracker as [bug 814505](https://bugzilla.mozilla.org/show_bug.cgi?id=814505). Note that pressing the Continue button will continue with the installation, which will eventually succeed (in rare cases, you may see the dialog again and have to press the Continue button in the second dialog too).
