### ISSUE TITLE
track created apps outside Gaia profile

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#15]
r2d2b2g's nascent Create App function installs an app into the Gaia profile but doesn't record its existence anywhere other than the webapps/webapps.json file in the profile. That means it'll lose track of the app after an addon update, when the addon completely removes and replaces the profile. It also means that it's hard to distinguish between built-in apps and those created by the addon.

r2d2b2g should track created apps in a persistent store that survives updates and clearly distinguishes between the user's apps and built-in apps. One option would be to use the simple-storage module https://addons.mozilla.org/en-US/developers/docs/sdk/latest/packages/addon-kit/simple-storage.html.

**Comment by digitarald** [comment]
Feature to track directories added in #38.

Missing: Track installed hosted apps and apps generated from pages.

**Comment by digitarald** [comment]
Finished in #42
