### ISSUE TITLE
 when i launch firefox browser with Firefox OS simulator it crash

### ISSUE THREAD

**Issue by FlynnV** [mozilla/r2d2b2g#150]
When i use firefox browser on the Firefox OS simulator, the simulator crash. It's impossible to use it.

**Comment by mykmelez** [comment]
What version of the Simulator are you using, and which platform (Windows, Mac, Linux) are you using it on? We had a problem like that with the Simulator on Windows, but it should be fixed in the latest version of the Simulator (0.8).

**Comment by FlynnV** [comment]
I use Windows and the simulator is the version 0.6

**Comment by mykmelez** [comment]
That sounds like the problem we fixed in more recent versions of the Simulator. Please try the latest version, and let me know if this problem still occurs!

https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi

**Comment by FlynnV** [comment]
It's ok, this version don't bug

**Comment by mykmelez** [comment]
Great, thanks for the quick response!

**Comment by prasaddhule** [comment]
The problem still exist with the new simulator 5.0pre3.. Any solutions??
