### ISSUE TITLE
Conversations are not getting deleted.

### ISSUE THREAD

**Issue by vasuans** [mozilla/r2d2b2g#153]
When I tried to delete a new(or) existing conversation, DELETING..... message was displayed for a long time. After some time messages application got hanged and I had to close the simulator and open it again to see whether the conversation was deleted or not. Finally the the conversation was not deleted.

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
