### ISSUE TITLE
Time/Date duplicate data

### ISSUE THREAD

**Issue by Kasraeian** [mozilla/r2d2b2g#154]
1. Date shown on the first (main) screen got duplicate day information.
   Like: Monday Mon Nov 26 2012 01:00:16
2. When clicking on the clock other view got two duplicate data
   Like: Monday, November Mon Nov 26 2012

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the  [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
