### ISSUE TITLE
expose "created apps" API to Helper

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#16]
r2d2b2g exposes a Create App function to the Helper page, but it doesn't expose an API for Helper to retrieve information about created apps. It should do so, so Helper can list the user's created apps and give the user tools for accessing them and performing common tasks, in particular:
1. Start App (re/install app, re/start B2G Desktop, and go directly to the app via the `-webapp` command-line option);
2. Open File Location (open a File Manager window--Explorer on Windows, Finder on Mac, Files on GNOME--to the directory containing the app's files, probably by using `nsIFile::reveal()`);
3. Package App (archive the app in a ZIP archive suitable for uploading to Marketplace).

**Comment by digitarald** [comment]
Feature to store and list apps added in #38.
