### ISSUE TITLE
FirefoxOS Simulator won't start on Ubuntu 11.10 (Linux 64-bit)

### ISSUE THREAD

**Issue by wamoyo** [mozilla/r2d2b2g#160]
I'm not sure if it's not yet supported on my distribution, but when I clip on "stopped" it won't switch to "started." It jolts slightly, as it the switch is trying to toggle, but doesn't.  Also, I'm using Nightly.

**Comment by mykmelez** [comment]
This is highly likely to be issue #105!

**Comment by wamoyo** [comment]
Yes, exactly, thank you!!!
