### ISSUE TITLE
OS 0.8 Firefox 16.0.2 values of textbox in contacts can not have double quotes

### ISSUE THREAD

**Issue by demiterra** [mozilla/r2d2b2g#161]
If you use the double quotes in any value except for the name, last name and company, the value will get cut when you try to update.

example:
you write in a contact a comment like:         friend "oscar"

you update and if you want to edit the contact again you will lost all the characters that are after the double quote

so you will have this value in comment:       friend

My OS is windows 7

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
