### ISSUE TITLE
Cannot install FirefoxOS in Windows 7 x64

### ISSUE THREAD

**Issue by qaiser73pk** [mozilla/r2d2b2g#162]
Too much blockage from installed Norton 360 for installation files for OS marked as Threat. Following threats identified:

Suspicious.Cloud.7.EP in FREEBL3.DLL
WS.Reputation.1 in several files (exe and dll)

Installation failed.

**Comment by mykmelez** [comment]
Thanks for reporting the problem, and sorry the install didn't work for you!

I'm not sure what's going on, but I suspect that these are false positives, i.e. Norton 360 flagged the files as potential threats, but they actually aren't.

Files that are distributed from ftp.mozilla.org are automatically scanned for viruses and other malware, and none were identified in the Firefox OS Simulator packages. I just did an additional scan of the Simulator's files on my local computer using Microsoft Security Essentials with the latest updates, and it didn't find any problems.

You might try installing the latest version of B2G Desktop and see if Norton 360 identifies any problems in it:

https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-beta/b2g-18.0.en-US.win32.zip

That doesn't help you run the Simulator, obviously, but it would give us more information about the problem.

**Comment by mykmelez** [comment]
Closing due to lack of additional information, and because this is likely to be a false positive on Norton's part. But please reopen if you still see the problem!
