### ISSUE TITLE
Firefox OS - Issues/modifications in contacts, settings, firefox, gallery, fm radio

### ISSUE THREAD

**Issue by jineshpk** [mozilla/r2d2b2g#163]
1.Contacts :  - when adding a contact>when inputting name need an option to toggle between phone like keypad and Qwetykeypad.

2.Firefox  - In firefox it will be better if we have an Exit button alongwith bookmark button.

3.Firefox  - the settings menu is not upto mark..

4.Firefox - Settings>About Firefox> back button is not working
1. Gallery - select photo>Edit> from edit screen not able to go back.
2. FM Radio - option button is needed. Most of the screen missing option buttons..

**Comment by mykmelez** [comment]
Thanks for reporting the problems! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
