### ISSUE TITLE
Close Running Apps

### ISSUE THREAD

**Issue by Sopanx** [mozilla/r2d2b2g#164]
How to close running apps. when i long press home button i can see apps that are running... but how to close them..?

**Comment by tofumatt** [comment]
To close running apps you need to bring up what I'd call the "App Switcher"; hold down the Home button. To force close an app, swipe it up.

It's not very intuitive, I agree. Sorry!

**Comment by Sopanx** [comment]
^^tofumatt Thank You Very Much...:)
