### ISSUE TITLE
[win] compilation errors..

### ISSUE THREAD

**Issue by Maksims** [mozilla/r2d2b2g#165]
Hi. Just git this last repo (9f0aa60211860086f8e033d34d568b5d54e7e0b1)
And trying to build it. So I have installed cygwin with make and wget packages.
So I clone repo, ran git submodule on both modules.
Then "make build", it downloaded long file, but then gives this error:

```
$ make build
make -C gaia
make[1]: Entering directory `/cygdrive/c/b2g/gaia'
Generating application data...
test -d profile || mkdir -p profile
run-js-command  applications-data
./xulrunner-sdk/bin/run-mozilla.sh: line 109: /cygdrive/c/b2g/gaia/xulrunner-sdk/bin/xpcshell: cannot execute binary file
./xulrunner-sdk/bin/run-mozilla.sh: line 109: /cygdrive/c/b2g/gaia/xulrunner-sdk/bin/xpcshell: No error
Makefile:293: recipe for target `applications-data' failed
make[1]: *** [applications-data] Error 1
make[1]: Leaving directory `/cygdrive/c/b2g/gaia'
Makefile:14: recipe for target `profile' failed
make: *** [profile] Error 2
```

I am pretty newbie, but looks like compilation process is not really straight forward..
Could you please assist me to make success compilation?

**Comment by mykmelez** [comment]
Hi @Maksims, sorry about the problems! You're right that the process is not straightforward; we should make it better.

In the meantime, you may be able to build it successfully by using [MozillaBuild](https://wiki.mozilla.org/MozillaBuild), which is a package of tools for building Mozilla projects. Download and install it (I recommend installing it to _c:\mozilla-build_), then use its _start-l10n.bat_ script to open a terminal window you can use to build the project. Note that there are other _.bat_ files for various versions of MSVC, but the r2d2b2g Makefile doesn't actually compile any code, so you don't need MSVC to build it. Thus _start-l10n.bat_, which doesn't require MSVC, is sufficient for building the project.

**Comment by mykmelez** [comment]
I'm going to close this issue, as I think the instructions in the previous comment address it, but please reopen if you still have problems!
