### ISSUE TITLE
Translate mouse into touch events

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#166]
B2G doesn't fire touch events currently.

Mouse interaction should fire touch events (only single-touch probably).

Optionally mouse events should not reach B2G (default: prevent events), to properly simulate phone behavior (the spec allows to fire both, though all implementations I saw never fire mouse events for touch).

Feedback?

**Comment by mykmelez** [comment]
Erm, I lost track of this, but your suggestion makes perfect sense to me, as it would much more closely simulate a phone environment!

**Comment by nhoizey** [comment]
Is there any progress on this? It's not possible currently to test touch events without replacing them all by mouse events.

Modernizr sees it as touch enabled.

**Comment by digitarald** [comment]
I took a first stab at it @ https://github.com/digitarald/r2d2b2g/tree/feature-touchme

**Comment by endemic** [comment]
This bug bit me when submitting an app to the Firefox Marketplace. Just leaving a note here instead of opening a new issue.

**Comment by peregrinogris** [comment]
What's the status of the patch for this? I faced this issue when trying to use a library that supports both mobile and desktop, and it fails when detecting if running on mobile or desktop.
I tried to monkey-patch the library to get it working at least on my app, but I couldn't find a way to know if it's running on the FirefoxOS Simulator or the real thing. Is there a way to detect when running on the Simulator?

**Comment by elgerlambert** [comment]
Just wanted to drop a line to say this is an issue for me also. I've built a mobile web app which uses Zepto to bind to touch events (I don't bind to click events at all).

Since this is my first comment related to Firefox OS, just wanted to say I love the project and wish it luck aswell!

Kind regards

**Comment by mykmelez** [comment]
[Bug 751147](https://bugzilla.mozilla.org/show_bug.cgi?id=751147) removed something similar from B2G a while back. Perhaps we can reuse that code.

**Comment by mykmelez** [comment]
Given the issues in the pull request, it feels scary to take this at the end of a development cycle. Even though it's very important, I'd rather land it at the beginning of the next cycle. So I've removed its milestone/priority settings pending reprioritization for the next milestone.

**Comment by mykmelez** [comment]
Fixed by #510!
