### ISSUE TITLE
Problem scrolling inside the browser.

### ISSUE THREAD

**Issue by jaydeepw** [mozilla/r2d2b2g#175]
When I open any website in Firefox on the emulator and try to scroll the page using mouse, it does not work.

Sometimes it works, but its uncertainly reliable. 
Same with scrolling using space-bar button.

**Comment by mohamedsalama** [comment]
this issue is in the pages of the OS such as Settings page

**Comment by mykmelez** [comment]
When you say "scroll the page using mouse", are you trying to scroll by simulating a tap-and-drag on a touchscreen using a click-and-drag with the mouse?

I have noticed problems with scrolling using click-and-drag, and we should figure out what's going on and fix the problem.

We are unlikely to fix bugs with scrolling using the scrollwheel or spacebar, though, as those are desktop-specific interfaces, and our focus is on simulating a phone environment.

**Comment by mykmelez** [comment]
The issue with the Settings app is #114, which should be fixed by issue #166.
