### ISSUE TITLE
changing the URL (to a large XPI?) freezes Firefox

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#179]
Kris Maglione notes in his preliminary review of Simulator 1.0:

> It might be worth noting that I also managed to freeze Firefox pretty hard while changing the URL trying to get this to work. After a while changes to the URL field stopped producing error console output, a while later I got an unresponsive script dialog in request.js, and finally Firefox just froze and wouldn't come back. I'm not entirely sure how to reproduce this, but it probably has something to do with me accidentally pasting the URL of a a 68MB r2d2b2g XPI in the field at one point... In any case, I thought it worth mentioning.

**Comment by ochameau** [comment]
Wouldn't it be a freeze when the xpi is unzipped in profile?

**Comment by mykmelez** [comment]
I think this is actually different from issue #83, which is about the freeze that occurs when the XPI is unzipped as part of the installation process. This freeze occurs when a user enters the URL to the XPI into the "URL for page or manifest.webapp" field of the Dashboard.

When a URL is entered into that field, the addon checks to see if the URL references a manifest; and if so, it changes the Add URL button to Add Manifest and installs the app from the manifest (instead of faking a manifest to enable the user to install any website as an app). I think that check downloads the URL to make the determination; and if it references a large file, which takes a long time to download, then it causes this problem.

If that's the problem, then the solution is probably to issue a HEAD request instead of a GET request and use the content type of the response to make the determination. @digitarald's UX changes to the Add App flow, which @potch is going to tackle, may also resolve this problem by clearly distinguishing between the "add app from manifest" and "add website as app" actions.
