### ISSUE TITLE
created app sometimes shows blank screen

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#18]
Sometimes, when you create an app, start B2G Desktop, and then start the app, the app displays a black screen instead of the app, and B2G Desktop becomes unresponsive (it isn't possible to go back to the home screen). When that happens, I don't see any different error messages in the console, just these same two that always appear:

```
Content JS INFO at app://system.gaiamobile.org/js/window_manager.js:802 in createFrame: %%%%% Launching My App 39 as remote (OOP)
Content JS LOG at app://system.gaiamobile.org/js/window_manager.js:379 in anonymous: Window Manager: No screenshot in database. This is expected from a fresh installed app.
```

I wonder if that black screen is some kind of default screenshot that appears when an app doesn't have a screenshot, per that log message. And then something goes wrong between the display of the screenshot and the loading of the app's actual content.

In any case, starting the app should always show the app! So if there's something we're doing wrong when creating the app that causes it to sometimes fail to start, then we need to fix that. Or, if this is a B2G Desktop bug, then fix that.

**Comment by anantn** [comment]
I haven't been able to launch a created app via r2d2b2g yet, but there's some known race conditions in the --runapp code. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=801801 to track this issue, it needs a fix on the B2G code.

**Comment by mykmelez** [comment]
Thanks for fixing the B2G Desktop issue! Hopefully that fixes the problem, but leaving this bug open until someone can verify that.

**Comment by digitarald** [comment]
Shall we remove the create-blank-app code, as we can add directories now.

**Comment by digitarald** [comment]
I haven't experience this in the recent builds. Please reopen if you can reproduce.

**Comment by mykmelez** [comment]
Note that we switched to Aurora builds of B2G Desktop several days ago (including for the 0.5 builds on Wednesday), but [bug 801801](https://bugzilla.mozilla.org/show_bug.cgi?id=801801) only landed on Aurora yesterday, so you may be able to reproduce the problem in the 0.5 builds, but you shouldn't see it in next week's builds nor in development builds you make yourself from today on.
