### ISSUE TITLE
Link to open hosted app in the browser

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#187]
Using `origin` and `launch_path`, developers should have an accessible link to open the app right in the browser.

Also works great with #186.

**Comment by mykmelez** [comment]
Right now the Manager gives you an _Open Location_ link for each app that opens a URL in a new tab. The link for a Generated app opens the app itself, but the link for a Hosted/Packaged app opens the manifest, which doesn't seem particularly useful.

We should change the link to _Open In Browser_ and make it open the app itself in all three cases, using the manifest of a Hosted/Packaged app to determine its location.

**Comment by digitarald** [comment]
UX Fix: Display path for local/packaged apps and launch-URL for hosted/generated apps. Clicking either opens the path for local apps or opens the launch URL for hosted apps. An "open URL" icon next to the URL can further hint the click action.

**Comment by mykmelez** [comment]
That seems reasonable too!

**Comment by mykmelez** [comment]
@digitarald are you actively working on this?

**Comment by digitarald** [comment]
Open Location should do exactly that (I just didn't close the ticket), but it seems that it's currently broken. I pinged @potch about it. This ticket can therefor be closed.
