### ISSUE TITLE
addon update fails on Windows

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#189]
On Windows, if you update the addon while B2G is running, the update fails. This is presumably because Windows locks the files of a running process in a way that prevents their deletion. I don't see the same problem on Mac.

**Comment by mykmelez** [comment]
Note: if you experience this, the workaround is to simply quit B2G before updating the addon.

**Comment by mykmelez** [comment]
In theory the addon kills the B2G process when it gets unloaded in preparation for being updated. Perhaps that isn't working. Or maybe it's working, but Windows holds onto the filehandles for some time after the B2G process has already quit. Or the process dies asynchronously, and the addon update races it.

**Comment by mykmelez** [comment]
This is now happening more consistently, and when it does, I see an adb.exe process running. Killing it makes a subsequent update succeed.

**Comment by mykmelez** [comment]
It looks like we don't kill adb on any platform, not just Windows. And that's a waste of resources in addition to causing this bug. We should do so whenever we don't need that process, and definitely when unloading the addon.

**Comment by mykmelez** [comment]
I think #409 has fixed this (modulo a potential race condition with Windows file deletion that could cause intermittent failure and would probably be exceedingly hard to resolve).

**Comment by fabiomagnoni** [comment]
Just a feedback about this for the App Manager. The developer wasn't able to install 1.2 or 1.3 because Nightly couldn't open the needed file.

**Comment by ochameau** [comment]
@fabiomagnoni This bug is tracked on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=932361 This is a very recent regression on Nightly. (It should work fine on aurora.)
