### ISSUE TITLE
Add rotate button

### ISSUE THREAD

**Issue by waldyrious** [mozilla/r2d2b2g#195]
...possibly next to the home button. Spawned from #41.

**Comment by mykmelez** [comment]
This is a more specific manifestation of issue #6, which requests a way to change orientation, so let's track it in that issue.

Also note that there are multiple ways we might implement the feature, and the issue tracks implementation generally, not the specifics of how we do it. Nevertheless, in recent conversations with @rpl, I suggested this very solution: a button on the toolbar that rotates the Simulator window.
