### ISSUE TITLE
Window shouldn't be resizeable

### ISSUE THREAD

**Issue by waldyrious** [mozilla/r2d2b2g#196]
Resizing the window results in black background showing up, and there's no way to restore the original size.

OS: Xubuntu 12.04
Firefox 17.0.1
Simulator Version 1.0

However, window resizing should be possible (automatically) in the event of a rotation between portrait and landscape modes. See #195.

**Comment by mykmelez** [comment]
I've seen this too, and it's quite annoying. It should also be fairly easy to fix, although we might have to fix it in the B2G code.

**Comment by mykmelez** [comment]
Adding this to prosthesis/defaults/preferences/prefs.js should fix this, but it doesn't:

```
user_pref("toolkit.defaultChromeFeatures", "chrome,dialog=no,resizable=no,all");
user_pref("dom.disable_window_open_feature.resizable", false);
```

I'm not sure why that is.

**Comment by mykmelez** [comment]
#457 fixed horizontal resizing. Unfortunately, it looks like we can't fix vertical resizing, or at least we haven't found a way to do so. So I'm going to close the issue, as we've gotten as close as it looks like we can get.
