### ISSUE TITLE
updating app doesn't consistently run it in Simulator

### ISSUE THREAD

**Issue by iamjayakumars** [mozilla/r2d2b2g#199]
Hi,
I installed Firefox Os Simulator in Linux - Ubuntu 10.04.4 LTS.
My Firefox version Mozilla/5.0 (X11; Linux i686; rv:20.0) Gecko/20121211 Firefox/20.0
In the Dashboard i added the "https://marketplace.firefox.com" and i clicked the update button in the dashboard, It opens the Firefox OS Simulator and not showing the Firefox Marketplace, it simply showing the home screen.

**Comment by mykmelez** [comment]
There used to be an issue in B2G that made opening B2G to a specific application inconsistent. We tried to fix it, and I thought we succeeded, but perhaps we didn't, as this sounds like exactly that problem.

**Comment by mykmelez** [comment]
@rpl just landed an architectural change that should make it possible for us to fix this bug, so updating an app consistently runs it in the Simulator.

**Comment by iamjayakumars** [comment]
ok...
i filed, some other issues in Firefox OS.
i filed in bugzilla.

**Comment by mykmelez** [comment]
I think this now works, but please reopen if it doesn't!
