### ISSUE TITLE
Install Page as App crashes immediately

### ISSUE THREAD

**Issue by Rudloff** [mozilla/r2d2b2g#20]
When I click on Install Page as App, it opens B2G for a second then immediately closes it.
The only information I have in Firefox error console is :
info: r2d2b2g: linux/b2g/b2g-bin terminated with 0

**Comment by mykmelez** [comment]
Are you on a 64-bit version of Linux by any chance? We don't yet support 64-bit Linux because of [bug 776845](https://bugzilla.mozilla.org/show_bug.cgi?id=776845).

**Comment by Rudloff** [comment]
No, I have a 32-bit version.

**Comment by mykmelez** [comment]
Hmm, puzzling. What distribution are you using? The output of `uname -a` would also be handy.

**Comment by Rudloff** [comment]
I am using Xubuntu:
Linux pierre-MacBook 3.2.0-32-generic-pae #51-Ubuntu SMP Wed Sep 26 21:54:23 UTC 2012 i686 i686 i386 GNU/Linux

**Comment by digitarald** [comment]
Does this still persist in the current builds, @Rudloff ?

**Comment by Rudloff** [comment]
No, I can't reproduce it anymore.
