### ISSUE TITLE
web browser crash

### ISSUE THREAD

**Issue by CobainLed** [mozilla/r2d2b2g#201]
![fire fox1](https://f.cloud.github.com/assets/3024756/7903/b9e386f6-444e-11e2-9704-475f256e62fe.PNG)
this happened after i entered a text to search in Bing engine
OS :Windows7
Web Browser: FireFox 17.0.1
Simulator : Firefox OS Simulator

**Comment by CobainLed** [comment]
I was able to pinpoint exactly when this can happen: "I ​​do a search on Bing then I click on the arrow at the top right (1) then I click on the arrow (2) in the upper left and BIIIIIIING it's the BUG 
![fire fox 4](https://f.cloud.github.com/assets/3024756/7919/2b9d6c84-4450-11e2-976e-252a3aded883.PNG)
![Fire fox 3](https://f.cloud.github.com/assets/3024756/7921/2bf448f6-4450-11e2-8ac5-95136995a626.PNG)
![Fire fox2](https://f.cloud.github.com/assets/3024756/7920/2bf03b3a-4450-11e2-9a92-b999a32d9cfc.PNG)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
