### ISSUE TITLE
Compsing number not working

### ISSUE THREAD

**Issue by phoewass** [mozilla/r2d2b2g#202]
Opening call screen.
![b2g0](https://f.cloud.github.com/assets/683485/8041/521e4bd2-445d-11e2-8566-57ed689e7a3d.PNG)

It doesnt display any composed number.
![b2g1](https://f.cloud.github.com/assets/683485/8042/523d3da8-445d-11e2-9a99-206c8979310f.PNG)

**Comment by Ashref** [comment]
great , good job wass :)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
