### ISSUE TITLE
selecting entry from history makes Communications app unresponsive

### ISSUE THREAD

**Issue by Ashref** [mozilla/r2d2b2g#204]
when i click  to find who i called recently the application stop working

![firefox7](https://f.cloud.github.com/assets/3025705/8118/c150019c-4464-11e2-88fe-19818b01c6e3.PNG)
![fire fox6](https://f.cloud.github.com/assets/3025705/8119/c151e7b4-4464-11e2-90ab-1f71f8675c5c.PNG)
![fire fox8](https://f.cloud.github.com/assets/3025705/8117/c14d1cc0-4464-11e2-97db-08b2c1ee84b6.PNG)
![firefox9](https://f.cloud.github.com/assets/3025705/8128/ec4b76a6-4464-11e2-9598-8f79eeab6809.PNG)

**Comment by mykmelez** [comment]
Sorry to hear about the problem! I see this too, and while in general the Simulator team doesn't track issues with Firefox OS itself, this seems like a problem that could affect app developers, since the Communications app provides a _dial_ activity that some app developers will want to use.

**Comment by mykmelez** [comment]
This is now working, although I'm not sure which change fixed it.
