### ISSUE TITLE
Starting the simulator hang firefox

### ISSUE THREAD

**Issue by hfiguiere** [mozilla/r2d2b2g#205]
I installed the r2d2b2g addon from AMO. I run Nightly on Linux (Fedora 17 x86_64) (compiled by myself).

When clicking the button to start the simulator, Firefox hang. I have no other choice but to kill it.

And the b2g simulator never shows it.

This is OK on Mac.

**Comment by mykmelez** [comment]
I know of some issues that cause B2G to hang on startup, but I haven't yet heard of Firefox hanging on B2G startup. We do, however, use jsctypes code to spawn a subprocess, and perhaps that code is somehow causing the hang. Is your custom-compiled copy of Firefox a debug build by any chance?

**Comment by hfiguiere** [comment]
No it is does not have --enable-debug in the mozconfig.

**Comment by mykmelez** [comment]
Hmm, it's hard to debug a custom-compiled version of Firefox, but if you send me your build, I'll give it a shot!

**Comment by mykmelez** [comment]
@hfiguiere: are you still seeing this problem?

**Comment by nickdesaulniers** [comment]
bump @hfiguiere

**Comment by mykmelez** [comment]
Closing this due to lack of needed info. But please do reopen if you can provide that info!
