### ISSUE TITLE
Clock Double Click Error

### ISSUE THREAD

**Issue by CobainLed** [mozilla/r2d2b2g#207]
The error bellow is shown just when i double click on the clock on home screen

the code behind this error is :

  var landingTime = document.querySelector('#landing-time');
  landingTime.addEventListener('click', function launchClock(evt) {
    Applications.getByOrigin(clockOrigin).launch();
  });

![Eror](https://f.cloud.github.com/assets/3024756/8771/866a5714-4485-11e2-9ffe-a02815a28d26.PNG)

**Comment by mykmelez** [comment]
Thanks for reporting the problem! However, the Simulator is designed to provide a test environment for app developers, and this issue tracker only tracks issues with using the Simulator to test your apps. It doesn't track other issues with using Firefox OS. Report those issues in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you experienced the problem while using Firefox OS via the Simulator!
