### ISSUE TITLE
Overlapping texts in messages menu

### ISSUE THREAD

**Issue by Sco768** [mozilla/r2d2b2g#208]
Windows 7 x64 Russian with FF 17.0.1 x86.

![FF](https://f.cloud.github.com/assets/212704/10744/eb8f679c-452f-11e2-8f56-7f1de82e127e.JPG)

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
