### ISSUE TITLE
Script execution scope

### ISSUE THREAD

**Issue by Sco768** [mozilla/r2d2b2g#209]
Windows 7 x64 with FF 17.0.1 x86.

Since some sites like http://www.screenresolution.org/ and http://internet.yandex.ru report my screen resolution as 1920x1280, I believe javascript is not scoped to emulator only. That seems broken if not insecure.

**Comment by rpl** [comment]
This can be related to limitations in the screen resolution emulation code currently used in the b2g-desktop builds.

**Comment by digitarald** [comment]
Duplicate of #7.
