### ISSUE TITLE
Built in Key Board is not working on emuleter 

### ISSUE THREAD

**Issue by ambeshthakur** [mozilla/r2d2b2g#210]
When ever I want to insert a word in text field .a built in keyboard appears but on clicking a key it disappears .

**Comment by mykmelez** [comment]
I see this too! And it sure is a problem, as it prevents app developers from testing their app's interactions with the keyboard. So we must fix it.

In the meantime, as a workaround, you can enter text using your computer's physical keyboard.

Also, note that this was previously reported as issue #191, so let's track it there.
