### ISSUE TITLE
Date and Time Setting has no option of manual date and time settup

### ISSUE THREAD

**Issue by ambeshthakur** [mozilla/r2d2b2g#211]
navigational steps:- In main menu navigate to setting .
click on date and time, 
Click Set Automatically button to off ,but no date and time manual setup appears .

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
