### ISSUE TITLE
Creating event in callender does not give reminder

### ISSUE THREAD

**Issue by ambeshthakur** [mozilla/r2d2b2g#212]
In main menu click on calender , and add a event . The added event should give reminder but it does not give show.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
