### ISSUE TITLE
Contact/Calender Sync with Mac

### ISSUE THREAD

**Issue by rimbold** [mozilla/r2d2b2g#214]
For me a important issue is to sync my phone with my Mac.
In the past my old nokia worked well with bluetooth connect to the mac with the mac "Sync" application.
It was a 100% sync bidirectional.
Since i switched to android, it is very hard to do a perfect sync. 
So here a see a new OS...and my request for the new OS is to connect the device easily via bluetooth with a Mac and sync it with the "Sync" Application....
I hope this issue is planned for this new OS...

**Comment by mykmelez** [comment]
Thanks for making this request! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks enhancement requests related to testing apps. It doesn't track other requests for Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia).
