### ISSUE TITLE
Calendar Not Displaying todays date

### ISSUE THREAD

**Issue by iamjayakumars** [mozilla/r2d2b2g#217]
Calendar Not displaying today's date in Menu's .
Its shows 1st date always

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
