### ISSUE TITLE
Gmaps in FirefoxOS Ap?

### ISSUE THREAD

**Issue by palmagro** [mozilla/r2d2b2g#219]
Hi all,

There is a way to use Gmaps in a FirefoxOS app Testing in r2d2b2g?

I tried using the normal gmaps script and google loader but still iḿ getting probems with CSP:

[JavaScript Warning: "CSP WARN:  Directive script-src app://myapp44.gaiamobile.org violated by https://maps.googleapis.com/maps/api/js?v=3&format=json&sensor=false&callback=google.loader.callbacks.maps
"]

Some ideas?

Thank you in advance...

Pedro

**Comment by digitarald** [comment]
If yo are developing a packaged app, all JS has to be in the package, due to CSP: https://developer.mozilla.org/en-US/docs/Security/CSP/Introducing_Content_Security_Policy .
Using a hosted app (added from localhost or another server) is not restricted.

**Comment by kakimanu** [comment]
You can use a <iframe> pointer to a "map.html" which contains a map... but your "map.html" must be hosted in a remote server.
