### ISSUE TITLE
Add URL featurn can't add manifest with charset set in Content-Type header

### ISSUE THREAD

**Issue by huangzhongming** [mozilla/r2d2b2g#221]
Can't add the manifest for "Add URL": when server returns Content-Type: application/x-web-app-manifest+json; charset=ISO-8859-1, there will be "Unexpected Content Type error."

Refereed to:

> The document must be UTF-8 in order for the app to be submitted to Firefox Marketplace. It is recommended to omit the byte order mark (BOM). Other encodings can be specified with a charset parameter on the Content-Type header (i.e. Content-Type: application/x-web-app-manifest+json; charset=ISO-8859-4), though this will not be respected by the Marketplace.

**Comment by digitarald** [comment]
I currently do an exact match against the content-type. I will fix r2d2b2g validation to work even if the charset is included.

You should fix the content-type header send it in UTF-8, as all JSON-based content, at least for Marketplace.

**Comment by benfrancis** [comment]
This has come up a few times at the Madrid app workshop. Some web servers like Rails apparently automatically add the charset to the content type header and it can be difficult to configure. The simulator is being too picky!

**Comment by benfrancis** [comment]
CC @Rik

**Comment by mykmelez** [comment]
@digitarald Is this a straightforward, low-risk fix that you could make in short order? Given that multiple folks ran into this problem at the Madrid workshop, we should get it into v3.

**Comment by digitarald** [comment]
That is a simple low-risk fix! I will provide a pull request.
