### ISSUE TITLE
Can't move picture when setting walpaper.

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#223]
When I was setting up a wallpaper I couldn't move the picture.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
