### ISSUE TITLE
Letters over letters

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#224]
See images.
![foss](https://f.cloud.github.com/assets/3098205/27111/d7a64fbe-4b71-11e2-91e8-fca9d0393955.png)
![foss](https://f.cloud.github.com/assets/3098205/27084/6ad9180a-4b6f-11e2-804f-77effc2a7460.png)
![foss](https://f.cloud.github.com/assets/3098205/27122/8c242942-4b73-11e2-9dd7-97286404f9a1.png)

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
