### ISSUE TITLE
Small letters in task app

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#225]
The letters in the task app are very small. Some older people couldn't read. For us young this isn't a big problem. ;)
![foss](https://f.cloud.github.com/assets/3098205/27103/48f5d956-4b71-11e2-87c7-1400f6b8bed3.png)

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
