### ISSUE TITLE
unlock padlock icon not intuitive

### ISSUE THREAD

**Issue by quixote7** [mozilla/r2d2b2g#230]
Using Firefox Simulator running on FF16 under LinuxMintDebian Testing. Unlock involves swiping up (_very_ nice discoverability there, by the way, with the elastic semicircle and arrow pointing up), and then clicking the little padlock icon.

The padlock icon is shown in an UNlocked state. My first assumption would be that tapping that would LOCK it. I knew from reading that I was supposed to tap it to unlock, but I don't think you want people to have to look up how to take the first step with the device.

If there are problems for some people faced with a locked icon, maybe another animation would help: show a locked icon with a gentle glow which briefly moves to "unlocked" and then back again.

Great job so far. Looking forward to using this on my phone!

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
