### ISSUE TITLE
Wi-Fi issue and Place name in date and time

### ISSUE THREAD

**Issue by harishdharman** [mozilla/r2d2b2g#231]
Wi-Fi activation key has problem. After switching off W-Fi connection it is not possible to activate.
And please add Bangalore in location under date and time settings.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
