### ISSUE TITLE
TowerJelly issue

### ISSUE THREAD

**Issue by sku009** [mozilla/r2d2b2g#235]
Not showing properly

![b2g1](https://f.cloud.github.com/assets/3121363/30469/75e2a994-4e96-11e2-8d90-3463dbe616b6.png)

**Comment by mykmelez** [comment]
This is a known issue with that app. However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
