### ISSUE TITLE
Create command line app installer

### ISSUE THREAD

**Issue by tofumatt** [mozilla/r2d2b2g#24]
Add a Firefox command line tool to install the current page or an arbitrary URL to B2G Simulator.

**Comment by mykmelez** [comment]
According to the [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit), this should take the form of the following Developer Toolbar command:

```
firefoxos install app [URL]
    install hosted app from URL
    URL is optional, defaults to URL of current tab
    behaves similarly to the “Add App from URL” button, as far as notifying the user
    when a manifest is generated for them.
```

**Comment by digitarald** [comment]
Check out the commands we already have, should be a piece of cake now.
