### ISSUE TITLE
updating app removes other apps from Simulator

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#244]
When I press the Update button to update one of my apps in the Simulator, the app gets updated, but any other apps that I installed in the Simulator get removed, so only the updated app is available. Updating an app shouldn't affect the status of any other app.

It doesn't look like Gaia apps are affected, just the apps that I installed using the Simulator.

@rpl: Perhaps this is a regression from landing the debugger communications channel?

**Comment by rpl** [comment]
@mykmelez I've just reviewed our last 2 pull requests related to debugger channel and there's nothing related to apps updating (I'm working hard on that code during these days for the issue #237, but we've not merged anything from that feature branch yet)

Besides that, coming changes into the application management code that we are introducing for the issue #237 should fix this too.

**Comment by rpl** [comment]
@mykmelez this issue should be fixed now (all install/run/update/remove commands are already completely migrated to mozApps API)

**Comment by mykmelez** [comment]
So say we all!
