### ISSUE TITLE
Not able to import complete contacts from Facebook

### ISSUE THREAD

**Issue by kkdeep** [mozilla/r2d2b2g#253]
While importing the Facebook contacts its importing only few of them  (i.e. 17 or 18 out of 300+). While importing rest of the contacts its taking forever time & not able to complete it. I'm using Firefox 18 on ubuntu 12.10 & simulator version is 1.1pre3.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
