### ISSUE TITLE
similator preview version cannot unlock the screen on  ubuntu 12.02

### ISSUE THREAD

**Issue by virteman** [mozilla/r2d2b2g#254]
I update the plugin today, open it ,but I cannot unlock the screen.

**Comment by mykmelez** [comment]
Hmm, I can't reproduce this problem with the latest preview release.

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

The general procedure to unlock the screen: press and hold down the mouse button near the drawer at the bottom of the screen, then drag the mouse up to expose the unlock icon and release the mouse button. Finally, click the unlock icon.

If you still have this problem with the latest preview release, please reopen the issue and provide any additional details you have available! It would be particularly useful to know what part of the unlock procedure fails and exactly how it fails.
