### ISSUE TITLE
Localization Key shown instead of string

### ISSUE THREAD

**Issue by xadhix-zz** [mozilla/r2d2b2g#256]
The localization key `{{brandShortName}}` is shown instead of the actual localized text.
Steps to reproduce : Go to Settings -> Improve Browser OS
Please see image attached.

![firefoxos1](https://f.cloud.github.com/assets/285383/82934/ec419fb8-63c3-11e2-927a-2c0e5b4be244.png)
- OS : Windows7
- Firefox Version : 18.0.1
- Simuator Version : 1.0, Last Updated : January 21, 2013

Thanks,
Adhi

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.

**Comment by xadhix-zz** [comment]
Ok Thanks :)

(is this a no-reply email ID?)

On 29 January 2013 00:41, Myk Melez notifications@github.com wrote:

> Thanks for reporting this problem! However, the Simulator is intended to
> be a test environment for app developers, and this issue tracker only
> tracks issues with testing apps. It doesn't track other problems with
> Firefox OS. Report those in the Boot2Gecko issue trackerhttps://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia,
> making sure to note that you noticed the problem in the Simulator.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/r2d2b2g/issues/256#issuecomment-12798451.

## 

Thanks and Regards,
       Adhithya

**Comment by mykmelez** [comment]
Hmm, I'm not sure what you mean by "no-reply email ID", but GitHub will post a comment when you respond to an email about an issue.
