### ISSUE TITLE
"persona login failed. A server error was encountered"

### ISSUE THREAD

**Issue by pouar** [mozilla/r2d2b2g#258]
keep getting this error every time I try to login to the marketplace inside the Simulator, whether I click on the marketplace icon or open it from the browser. it works fine on my PC but not inside the Simulator

**Comment by nhoizey** [comment]
Same issue on my side. What can I do to help investigate?

**Comment by eduardocasas** [comment]
I have the same problem.

**Comment by nhoizey** [comment]
Thanks @Rik, who told me to try last build of the extension (r2d2b2g-2.0pre5-mac.xpi), which fixes this issue:
https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/

**Comment by mykmelez** [comment]
I'm glad to hear the issue is fixed in the latest preview release!
