### ISSUE TITLE
Add auto-generated app from URL/Tab

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#26]
1. User click "Add App from URL/Tab"
2. User selects tab or enter URL
3. Manifest gets generated from page title and URL
4. App gets installed, no "Update" button required
5. Actions: Edit manifest (?)

**Comment by mykmelez** [comment]
The [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit) says:

> “Add App from URL” will just prompt the user to enter a URL and will install that URL as a “hosted app”. If the URL points to a manifest (with the proper MIME type as required by the Marketplace), the app is simply installed. If the URL does not refer to a manifest, the user is notified that an manifest has been created for them. Valuable, but likely P2: provide a button that allows the user to edit the generated manifest.

So I would simplify and just implement "Add App from URL" for now, reserving "Add App from Tab" for later!

**Comment by digitarald** [comment]
Added in #42. Both added, as URL field auto completes from open tabs.
