### ISSUE TITLE
On Screen Keyboard Does not Show Up on SMS App

### ISSUE THREAD

**Issue by bitthegeek** [mozilla/r2d2b2g#262]
Firefox 18, Fedora 17 64 bit

Keyboard does show up in other apps (physical keyboard input disabled) but does not appear on the SMS Application (physical keyboard however is not disabled)

**Comment by mykmelez** [comment]
I don't see this in the latest preview release, which we released three days ago.

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

Can you reproduce the problem with that release?

**Comment by bitthegeek** [comment]
It seems already fixed. Closing now, thanks!
