### ISSUE TITLE
Can't turn Wi-Fi on

### ISSUE THREAD

**Issue by jaydson** [mozilla/r2d2b2g#264]
I can't turn wi-fi on. 
When i click to turn on, the button automatically turns off.
I'm using Ubuntu 12.04, Firefox 18 and Firefox OS Simulator 1.0.

**Comment by mykmelez** [comment]
The wifi button doesn't work in the Simulator, but it should still be able to use your computer's network connection (whether wifi or wired). Does your installation have access to the network, even though the wifi button indicates that wiki is disabled? And if not, does installing the latest preview release fix the problem?

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by jaydson** [comment]
With the latest preview release, it works fine.
