### ISSUE TITLE
Firefox breaks when editing Gaia

### ISSUE THREAD

**Issue by juliankrispel** [mozilla/r2d2b2g#267]
I fancied playing around with styling Gaia a little, however, when I edit the contents of the zip file, rezip it and replace it with the original, even if I don't actually change it but only rezip it, fos breaks. I'm guessing that this is because 'certified' apps are signed.

Is there a way around that so that I can start messing around with fos to my hearts content?

**Comment by mykmelez** [comment]
I'm not sure why recreating the archive doesn't work, but the easiest way to hack on Gaia is to clone its repository https://github.com/mozilla-b2g/gaia/, install a nightly build of B2G Desktop https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/, make your changes to the Gaia source files, build a Gaia profile containing your changes, and then run B2G Desktop with your Gaia profile!

See [Gaia/Hacking](https://wiki.mozilla.org/Gaia/Hacking) for more information.

**Comment by juliankrispel** [comment]
Hi Myk! Thanks for the feedback. I tried that and it seems to work. Is there a way around the build step? Ideally I'd just edit a css file and relaunch the app, not possible is it?

**Comment by mykmelez** [comment]
If you build Gaia with DEBUG=1, then it leaves the source files unpackaged, so you should be able to change them and then relaunch the app to see your changes. I'm not familiar with the details, though. That Gaia/Hacking page may have more info.

**Comment by juliankrispel** [comment]
I saw James Hugman talking about FxOS in Brighton, he said you were a good guy, he's right! :+1:
