### ISSUE TITLE
Simulator doesn't remove old versions of apps

### ISSUE THREAD

**Issue by mattbasta** [mozilla/r2d2b2g#271]
When an app is removed from the dashboard, it isn't uninstalled from the simulator

**Comment by mykmelez** [comment]
The app should get uninstalled after you
1. reload the Dashboard (causing the Undo button to disappear);
2. restart the Simulator.

That's suboptimal, of course. Especially now that we can install an app without restarting the Simulator, we should be able to uninstall it without doing so as well. And we should uninstall the app when the user removes it from the Dashboard, then reinstall if the user presses Undo.

**Comment by rpl** [comment]
should be fixed by #291 
reopen if it's not fixed.
