### ISSUE TITLE
Numeric keypad in the simulator does not work

### ISSUE THREAD

**Issue by mattbasta** [mozilla/r2d2b2g#273]
Pressing the "123" button in the keyboard closes the keyboard.

**Comment by mykmelez** [comment]
Strange, I'm unable to reproduce this problem. Does it happen on all apps or just certain ones? And which version of the Simulator and OS are you using?

**Comment by mattbasta** [comment]
At the app day, I was able to reproduce it across Windows, Linux, and OS X.

It is possible that this problem is due to an old version of the simulator being provided on the thumb drives given to the app day participants. What's the latest "release" version of the simulator? I can try to update my local version and try to reproduce.

**Comment by mykmelez** [comment]
> It is possible that this problem is due to an old version of the simulator being provided on the thumb drives given to the app day participants.

Indeed, that is quite possible!

> What's the latest "release" version of the simulator?

The latest release version is 1.0, but the latest preview version is 2.0pre5, and that's the version to test.

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by nickdesaulniers** [comment]
bump @mattbasta

**Comment by mattbasta** [comment]
This appears to be fixed in 2.0.
