### ISSUE TITLE
Troubles acessing memory card

### ISSUE THREAD

**Issue by rgaiacs** [mozilla/r2d2b2g#275]
I like to try/test the gallery/music/video app. Unfortunate the home screen of any of this apps show some thing like

![ff_home_music](https://f.cloud.github.com/assets/1506457/99906/2c1223d6-67d1-11e2-9411-baf8ac65afd7.png)

Where is set the memory card files?

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS or issues with trying/testing Firefox OS itself.
