### ISSUE TITLE
Simulator no longer loading OS ?

### ISSUE THREAD

**Issue by g13nn** [mozilla/r2d2b2g#278]
I installed 'firefox OS simulator" all was working fine. But now the simulator has stopped working. It loads up with a black screen with mozilla logo. Anyone else have this problem?

Anyways removing the firefox OS simulator extension and installing it again seems to have fixed this issue for now.

**Comment by mykmelez** [comment]
Sorry about the problem, but I'm glad to hear things are working again!

It sounds like there was a stuck Simulator process running on your computer. In that situation, you can often get things working again by looking for such a process (which should be called b2g or b2g-bin) in your OS's activity manager and killing the process.
