### ISSUE TITLE
Error Console lacks scrollbar

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#279]
The Error Console lacks a vertical scrollbar. It's still possible to scroll the window using a scrollwheel, but that's not very discoverable, and not all users have scrollwheels. So it should have a vertical scrollbar too.

This is probably caused by a global CSS rule that removes scrollbars for all B2G Desktop windows, and the fix is to create a rule that adds back the vertical scrollbar for the Error Console window.

**Comment by mattbasta** [comment]
It might also be a worthwhile feature to have the console scroll with the output, so until the user scrolls up, they can see the most recently outputted message. Generally, just starting the simulator fills up the console with warnings and errors, meaning the user will always need to scroll.

**Comment by mykmelez** [comment]
This is fixed in the latest preview release, probably because we undid some style changes that stock B2G makes to all windows.

Regarding the enhancement request, the console in question is just the Mozilla Toolkit Error Console, so the request would be best reported to that console's issue tracker. I see that [Console²](https://addons.mozilla.org/en-us/firefox/addon/console%C2%B2/) works that way, so it's definitely possible to do.

Also note that we're actively looking into ways to improve the console logging experience in the Simulator, primarily via integration with the Developer Tools Web Console, which does scroll in this fashion.
