### ISSUE TITLE
Using FormData() with an ajax post request doesn't post correctly using the Simulator

### ISSUE THREAD

**Issue by operatorjen** [mozilla/r2d2b2g#280]
posting with this causes the screen to go white and not respond.

**Comment by mykmelez** [comment]
Is this with your Roller app http://roller.noodletalk.org/, and what would I need to do in the app to reproduce the problem?

**Comment by operatorjen** [comment]
Nope another app :)

Steps to reproduce:
1. Log into https://detourapp.com with Persona
2. Go to settings -> add yourself as a contact (same email you signed in with), save
3. Add a new message, type some text or just trigger the upload file button, add yourself in the Contacts button
4. Submit

Screen will turn white for both versions of the app (as a Marketplace installation and through the browser on the Simulator)

**Comment by operatorjen** [comment]
closing as it works after subsequent testing!

**Comment by mykmelez** [comment]
Glad to hear! Please do reopen if you encounter it again. :-)
