### ISSUE TITLE
UI Tests text links double-up Visual Error

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#284]
Some of the Test links in the "UI Tests" App Double-Up. Some text links appear overlayed upon other links. The display error cancels out the overlayed links rendering them un-clickable.

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
