### ISSUE TITLE
[Bug - Trivial] Swipes starting from links does not actually swipe

### ISSUE THREAD

**Issue by bitthegeek** [mozilla/r2d2b2g#287]
(probably only the simulator is affected)

I don't know if this is just OS specific or just that the Firefox OS simulator's backend cannot have a workaround for this.

Swiping starting from links drag the link somewhere instead of scrolling. Releasing the mouse does not 'lift the finger' and instead, follows the mouse as if 'the finger wasn't yet lifted'. A click somewhere else releases 'the finger'.

Browser: Firefox 18
Operating System: Fedora 17 Beefy Miracle
Simulator: Firefox OS Simulator 2.0pre5

**Comment by ghost** [comment]
Try clicking the Mouse Wheel button, as a temporary fix, while this is happening to fix the issue. Works for me ;P

**Comment by mykmelez** [comment]
This sounds like #114, which will be fixed by #166.
