### ISSUE TITLE
facebook infinite comments 

### ISSUE THREAD

**Issue by starecat28** [mozilla/r2d2b2g#292]
(Sorry, I don't write in English very well) When I comment or post some content in Facebook, that post is repeated infinitely until the page is refreshed.

-Firefox OS simulator 2.0pre6, Windows7, Waterfox 18.0.1

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
