### ISSUE TITLE
Full Screen in browser feature request

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#295]
It would be cool to have some kind of Full-Screen feature for the built in browser on Firefox OS!

**Comment by JosiahOne** [comment]
This should be requested as part of the actual Firefox OS source code. You can file a bug here,
https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko

This simulator only simulates the Firefox OS, changes like animated wallpaper can and should not be confined to a simulator. Use the link above and set severity to "enhancement". 

Thanks,
Josiah Bruner.

**Comment by nickdesaulniers** [comment]
Thanks for making this request! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks enhancement requests related to testing apps. It doesn't track other requests for Firefox OS. Report those in the Boot2Gecko issue tracker.
