### ISSUE TITLE
Animated Wallpapers feature request

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#296]
Animated wallpapers would be great, but with paused movement while the handsets are locked, to save battery

**Comment by JosiahOne** [comment]
I believe this should be requested as part of the Firefox OS code itself. The simulator only "simulates" the OS. You can use this link to a file a bug. Be sure to set severity to "enhancement".

https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko

**Comment by nickdesaulniers** [comment]
Looks like .gif's aren't supported for backgrounds ATM.

**Comment by nickdesaulniers** [comment]
Also for future reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=837456
http://imgur.com/a/g78pE#0

**Comment by nickdesaulniers** [comment]
Thanks for making this request! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks enhancement requests related to testing apps. It doesn't track other requests for Firefox OS. Report those in the Boot2Gecko issue tracker.
