### ISSUE TITLE
Youtube videos do not load.

### ISSUE THREAD

**Issue by marcos635** [mozilla/r2d2b2g#299]
Testing in the simulator version 2.0Pre5 when I see some of the youtube video when I open a video screen is black and does not load.
![4856](https://f.cloud.github.com/assets/3501069/135417/18c515c8-7121-11e2-867f-3bf39573aa36.png)

**Comment by nickdesaulniers** [comment]
https://gist.github.com/digitarald/ea3470bdd501f1e463a2

**Comment by mykmelez** [comment]
@digitarald, do you see the same behavior when you include that gist in an app? If so, do you happen to have an app with which I can test it?

**Comment by digitarald** [comment]
Youtube on the phone works sadly very different, as the user agent is overridden and the video app is  used to stream the URL scheme that is usually used to trigger the youtube app intent on Android.

I wonder what that bug describes, @marcos635. Are you opening launching the video app from your app or opening youtube.com?

**Comment by dorman** [comment]
This is also happening to me as well when I go and try to load a video.I've tried loading the video and waiting for a few minutes and I still just see the loading symbol. 

Oh and I am using the browser to view a YouTube video.

**Comment by mykmelez** [comment]
I see this in the Error Console when trying to play a video from youtube.com in the browser:

> Timestamp: 2013/03/29 11:00:52
> Warning: HTTP "Content-Type" of "video/mp4" is not supported. Load of media resource http://r2---sn-o097znez.c.youtube.com/videoplayback?ip=63.245.220.240&key=yt1&sparams=cp%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&fexp=900716%2C908457%2C916807%2C915700%2C914025%2C916611%2C932000%2C906383%2C902000%2C919512%2C929903%2C931202%2C900821%2C900823%2C931203%2C931401%2C908529%2C930807%2C919373%2C930803%2C906836%2C920201%2C929602%2C930101%2C930603%2C900824%2C910223&newshard=yes&ipbits=8&ratebypass=yes&mv=m&mt=1364580027&itag=18&id=0dca27b1f1ac5f20&expire=1364606814&ms=au&upn=lbVIAa_zlsk&source=youtube&cp=U0hVSVZLVF9GTkNONV9ORVhJOkdWYWo1VTFubVdZ&sver=3&signature=C970FFD139CE9475D338B6AE29AE2E102CD07969.863888DA763594A8FF7EECE6FB75C8B53277DBE0 failed.
> Source File: app://video.gaiamobile.org/view.html
> Line: 0

**Comment by digitarald** [comment]
Video playback depends on hardware codecs and will therefor not work in the Simulator. This affects MP3, MP4 and Webm.

**Comment by mykmelez** [comment]
Hmm, ok, then we can't fix this problem, so unfortunately we have to close the issue without resolving the problem. Note that @wbamberg has documented this limitation in his [new Simulator docs on MDC](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator). And I just added a sentence to that doc that mentions Youtube specifically:

> This means it isn't possible to use the Simulator to test video playback in apps and on websites like Youtube that rely on these codecs.
