### ISSUE TITLE
Use mobile user agent instead of host machine's

### ISSUE THREAD

**Issue by lisabrewster** [mozilla/r2d2b2g#3]
The user agent that's showing up for me is:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:18.0) Gecko/18.0 Firefox/18.0

Which means many sites are returning desktop content.  I'd think for the purposes of quick and easy app testing, r2d2b2g should use the (generally agreed upon) mobile user agent:

Mozilla/5.0 (Mobile; rv:18.0) Gecko/18.0 Firefox/18.0

(Obligatory: Yes, it's better for developers to do feature detection and responsive design than user agent sniffing.)

**Comment by JoeStagner** [comment]
Instead - how about letting the user choose the UA ?

**Comment by mykmelez** [comment]
> Instead - how about letting the user choose the UA ?

I'd fall back to that approach if changing the UA causes problems for a significant number of users. But let's try simply changing the UA to @lisabrewster's suggested value first, as that might be sufficient.

Commit mykmelez/gaia@248583e3c47ac1f21a3250c69565aaf84eac3ef2 in my fork of the Gaia repository uses a custom-prefs.js file to override the string, and commit 0beac1d6a6e1edaebdd2dba43a1bce31f704f950 makes r2d2b2g use that version of Gaia, resolving this issue.
