### ISSUE TITLE
addon doesn't appear in Add-ons Manager after installation

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#307]
On AMO, aidosnet writes:

> Ubuntu 12.10 64bit, installation procedure terminates signaling that was ok, but I've no menu item for Firefox Os Simulator in tools -> web developer and the extension doesn't appear int the add-ons list. I've also tried to restart FF with no success.

**Comment by mykmelez** [comment]
@aidosnet: did Firefox ask you about an "unresponsive script" during the installation process? And, if so, did you happen to press the Stop Script button in the dialog? If so, try installing again, but this time, press the Continue button.

**Comment by aidosnet** [comment]
thanks for you answer, I tried again to reinstall the extensions. I never had a "Stop Script dialog" or  other error dialog during the installation, that continues without problems...but I don't have a menu item in the tools->web developer or a an item in the add-ons list...

**Comment by nickdesaulniers** [comment]
@boscaini , is this still an issue with the latest version (3.0pre2) release 2 days ago?

**Comment by mykmelez** [comment]
Closing due to lack of info needed to diagnose problem. Please reopen if you can still reproduce with the latest preview build!

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).
