### ISSUE TITLE
updating all apps on addon update causes Simulator to start unexpectedly

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#308]
Updating an app causes the Simulator to start if it isn't already running. That's ok when the user triggers the update by pressing the app's Update button, since it's clear that the Simulator started as a result of the button press, and the user probably wants to test the app after updating it.

But it's a problem when an addon update triggers updating all apps, because it isn't clear why the Simulator started in that case, especially if the Dashboard is closed. Launching the Simulator then is unexpected and startles the user.

We have to start the Simulator to update an app. But that is a technical implementation detail. And we shouldn't expose the user to it. The Simulator should only start when the user asks it to, either because they press the Start button or because they press the Update button for a particular app.

We could fix this by starting the Simulator in a special "install app" mode when updating all apps while the Simulator is not running. The mode, triggered by a command-line flag, would install the app specified on the command line (or multiple apps specified in a temporary file) and then quit. All without ever opening a window. So the user will never see the Simulator.

cc: @rpl

**Comment by mykmelez** [comment]
Witness: https://twitter.com/rik24d/status/301323026274852865

**Comment by robcee** [comment]
so that's what happened!

**Comment by kumar303** [comment]
Hah. I was so confused.

**Comment by willbprog127** [comment]
Ah, okay, just filed an issue about this...will delete it (if I can)
