### ISSUE TITLE
Firefox OS SImulator could not work on windows 8

### ISSUE THREAD

**Issue by YamamotoYusuke** [mozilla/r2d2b2g#310]
I'm using Firefox OS Simulator 2.0 on FIrefox 18.0.2,  and windows8.
I could unlock the lockscreen, but couldn't swipe homescreen.
Then, I could tap the icon ( like browse icon ), but the app didn't launch.
I could only unlock the lockscreen.

Did FIrefox OS Simulator support for windows8?

Best regards.
Thanks.

**Comment by mykmelez** [comment]
I don't yet have a Windows 8 installation, so I haven't tested the Simulator on Windows 8. Thus I'm not sure of the status of the Simulator on that OS. However, I have requested a license and installation media for the OS and will install it and test the Simulator on it once I receive it (ETA: one week).

**Comment by YamamotoYusuke** [comment]
Hi mykmelez,

Thanks for your confirmation.
I'm waiting it that Firefox OS Simulator move on Windows8.

Thanks.

**Comment by mykmelez** [comment]
I now have a Windows 8 installation and will look at this next week.

**Comment by mykmelez** [comment]
I've been diagnosing several issues with Windows builds, and I found a couple problems, so I created a test build with fixes for them.

https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-3.0pre6dev-windows.xpi

I'm not sure this build will resolve your issue, but please try it out, and let me know how it works for you!

**Comment by mykmelez** [comment]
I just pushed new preview builds ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) which resolve this issue on Windows 8!
