### ISSUE TITLE
Firefox OS Simulator started up on its own

### ISSUE THREAD

**Issue by willbprog127** [mozilla/r2d2b2g#313]
While reading a story on a web-page, Firefox OS Simulator spontaneously launched!  I had not tried to launch it earlier, nor have I in quite a few days.  Was kinda creepy, actually.

My system info:

---

Firefox OS Simulator 2.0
Firefox: 18.0.2
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:18.0) Gecko/20100101 Firefox/18.0
Running on: Salix OS
Kernel: 3.2.29

**Comment by willbprog127** [comment]
Closed because another issue was filed about this.

**Comment by rpl** [comment]
already tracked by issue #308

**Comment by willbprog127** [comment]
Hence the closure.  Thanks :-)
