### ISSUE TITLE
Testing Privileged (packaged) app on Simulator 2.0

### ISSUE THREAD

**Issue by Jaxo** [mozilla/r2d2b2g#315]
2.0 is great, but...  how can I test my application which requires mozbrowser iframes?

**Comment by mykmelez** [comment]
I think there's a permission you can declare in the "permissions" property of the manifest to enable them, perhaps "browser", which is one of the permissions the built-in browser app declares in [its manifest](https://github.com/mozilla-b2g/gaia/blob/master/apps/browser/manifest.webapp). But I haven't actually tested this to see if it works.

cc: @digitarald @nickdesaulniers and @rpl, who may know better.

**Comment by digitarald** [comment]
`browser` permission is implicit for privileged apps. You just need to set your `type` to `privileged`, declare the `browser` permission and you should be good to go. Only certified apps can't be tested with the new installation flow.

**Comment by Jaxo** [comment]
(Ubuntu 12.04.1 32bits, Nightly 21.0a1 / 2013-02-15, Simulator 2.0)
1. installing a privileged app  on the simulator _using the dashboard_ works PERFECTLY
therefore, this issue is less important: anybody can test a privileged Application b4 to submit to the MarketPlace.
2. but my problem was that I followed what's described in "Testing packaged app installation" at https://developer.mozilla.org/en-US/docs/Apps/Packaged_apps
That is: Apache2 serving a "package.webapp" (mini-manif), "application.zip", thru an install.html (installPackage).
Invalid mini-manifest, spinning wheel, ... What should be in the mini-manifest? are they naming conventions for the files?  Again, this is much less important now that I have a mean for testing.

Thanks for your outstanding work.

**Comment by nickdesaulniers** [comment]
@mykmelez we need to update [this](https://developer.mozilla.org/en-US/docs/Apps/Packaged_apps) MDN page to reflect how much easier it is to install packaged apps now on device.  @Jaxo, please upgrade to the latest build which now supports push to device.  I'm closing this issue and will open a new one for updating the documentation.  Feel free to comment on the new one, or reopen this one if there's an outstanding issue not related to documentation.
