### ISSUE TITLE
Firefox OS Simulator item in Tools menu should be under Web Developer menu

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#32]
The Firefox OS Simulator item in the Tools menu currently appears underneath the Page Info item. Per the [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit), it should appear just below the Web Developer menu.

**Comment by dangoor** [comment]
If this change is more than a few minutes' work, we can skip it.
