### ISSUE TITLE
Developer Toolbar > More Tools > Firefox OS Simulator

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#33]
Per the [v1 spec](https://docs.google.com/document/d/1S538182p1zwCAFHvIRTYCu0LkdHLVh3KZCVhOdKbh1Q/edit), there should be a Firefox OS Simulator item in the More Tools menu of the Developer Toolbar. Selecting it should open the manager.

**Comment by syssgx** [comment]
I think it's ok and can be closed now.

**Comment by mykmelez** [comment]
Unfortunately, we haven't implemented this yet! We do have a Firefox OS Simulator item in the Tools > Web Developer menu, and we also have one in the Unified Menu > Web Developer menu on Windows. But this issue is about putting one into the More Tools menu on the Developer Toolbar, and we haven't put it there yet.

**Comment by mykmelez** [comment]
The Developer Toolbar has changed in recent nightlies, and it no longer includes a More Tools menu, so it is no longer possible to do this.
