### ISSUE TITLE
You can see the clock in the background when you change the page

### ISSUE THREAD

**Issue by Just4FireFox** [mozilla/r2d2b2g#330]
Windows 7 Professional Service Pack 1
Firefox 18.0.2
FireFox OS Simulator 2.0

When I change the pageview from "Home" to one more right or from the right to another I can see the last numbers of the Clock / Kalendar of the home-pageview

![testest](https://f.cloud.github.com/assets/3692194/191247/442abf9a-7f2e-11e2-9c8a-298ca0f4e08e.png)

**Comment by Just4FireFox** [comment]
I found something that could initiate this bug in Date&Time settings, the Time tag is way too long

![testestes](https://f.cloud.github.com/assets/3692194/191381/c0fc09d8-7f34-11e2-8deb-83a56a7e9d30.png)

**Comment by nickdesaulniers** [comment]
Interesting, this may be a bug within the build for windows.  Trying this in Mac OSX:
![Screen Shot 2013-02-25 at 9 19 53 AM](https://f.cloud.github.com/assets/1823839/192865/b08b0b40-7f6f-11e2-835d-e80e9133ca8d.png)

**Comment by Just4FireFox** [comment]
I see you tested with the same Time zone, i tried this with many Regions and Cities but with the same result everytime. Maybe the timestamp for Windows 7 is wrong?

**Comment by nickdesaulniers** [comment]
@mykmelez , looks like a few issues are related to Windows.  Should we request a few licenses to investigate these futher?

**Comment by mykmelez** [comment]
@nickdesaulniers I have Windows licenses (and VMs) for XP, Vista, 7, and 8 already, and I highly encourage you to request the same! Or at least 7 and 8 licenses. It'd be great to have a second person taking a look at these Windows-specific issues. :-)

**Comment by mykmelez** [comment]
This looks like a dupe of #364, where folks are digging into the underlying problem; so let's track it there.
