### ISSUE TITLE
Add geolocation mock data support - initial longitude and latitude choice

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#332]
The user should be able to click a button on the bottom of the simulator window (as opposed to the addon window) next to the home button.  This should open a dialog external to the simulator window.  The dialog should have radio buttons that default to "use my current location", the second non-default choice to be "enter in a longitude and latitude coordinate pair", and then maybe in a future iteration have room for a full map.  The user can then click apply or cancel to have their default changed for the duration of the simulator processes lifetime.

**Comment by mykmelez** [comment]
We might want to persist a selection location across Simulator sessions, but persisting for the current session is a good first step.

**Comment by nickdesaulniers** [comment]
Big thanks to @rpl , I copied most of your code from the rotation button for the geolocation button.  It gave me a lot of inspiration.  Also @kanru, who did all of the work on the FakeGeolocationProvider!
