### ISSUE TITLE
Date/time displayed as decimal numbers

### ISSUE THREAD

**Issue by Chris2mop** [mozilla/r2d2b2g#333]
With the last module update, (to day Wed, feb 27)
The date/ time/gmt is displayed on the main window  (big characters) as:
6/43,27
20,13
18.4:00,01
What's wrong ?
(that was the Date/time when i created this post)

**Comment by nickdesaulniers** [comment]
I wonder if this is related to #330? Can you post a screen shot and post your current locale settings?

**Comment by mykmelez** [comment]
This looks like a dupe of #364, where folks are digging into the underlying problem; so let's track it there.
