### ISSUE TITLE
(Left or right) clicking an error in the console crashes prosthesis process

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#336]
STR:
1. Open addon
2. Enable error console checkbox
3. When the prosthesis process starts and the b2g and error console windows open, click a link to a particular source file listed in an error.
4. Wait a few seconds
Prosthesis crash

**Comment by mykmelez** [comment]
I see this too. One more reason to stop exposing the Error Console and make sure it's fun and easy to see all messages in the remote Web Console!

**Comment by nickdesaulniers** [comment]
Duplicate of Issue #171
