### ISSUE TITLE
Not opening in Nightly

### ISSUE THREAD

**Issue by Vidhuran** [mozilla/r2d2b2g#342]
Firefox OS option doesn't show up under the Web Developer menu in Nightly (22.0a1 (2013-03-04)) even though it shows up on normal Firefox. 
On copying the resource URL in Nightly, the page shows up , but clicking on the "Stopped" button changes the button to "Running" but it remains disabled. Nothing shows up in selecting console option either. 
![Nightly Error](https://f.cloud.github.com/assets/1607713/220819/74a18644-857e-11e2-826f-9ea8d9324890.jpg)

**Comment by nickdesaulniers** [comment]
A new build was pushed 2 days ago.  Please remove the existing version through about:addons, then install the latest (3.0pre2) for [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi) to help us verify.

**Comment by Vidhuran** [comment]
It is fixed in the newer version (3.0pre2).

**Comment by nickdesaulniers** [comment]
@Vidhuran , thanks for verifying this for us!  Our team appreciates it!
