### ISSUE TITLE
Refresh after clicking on an error does not display app list

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#352]
STR:
1. Start simulator
2. Install app with invalid manifest so that an error is reported
3. Click on the (X errors and X warnings)
4. refresh the page

Expected results:
Installed apps are re-listed

Actual results:
Installed apps are not re-listed

Looks like the apps are not re-listed when there's an empty fragment identifier on the end of the URL:
resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html#

**Comment by nickdesaulniers** [comment]
Should probably be preventing default when clicking on the anchor tags.  Good first bug.

**Comment by mykmelez** [comment]
@rpl
