### ISSUE TITLE
Update MDN documentation

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#361]
[This](https://developer.mozilla.org/en-US/docs/Apps/Packaged_apps#Testing_packaged_app_installation) page could use an update.  Referencing Issue #315

**Comment by nickdesaulniers** [comment]
review? @mykmelez 
I added [this](https://developer.mozilla.org/en-US/docs/Apps/Packaged_apps#Testing_packaged_app_installation_%28with_Simulator%29) section.  Wasn't there another step for linux?

**Comment by nickdesaulniers** [comment]
Also, I think the following section, on installing sans simulator should just be deleted, since it's ridiculous to expect anyone to install apps that way.  Input, @mattbasta, @potch, @cvan?

**Comment by mattbasta** [comment]
The page should be deleted, it's made redundant on the devhub.

**Comment by nickdesaulniers** [comment]
@mattbasta , I should probably also update the devhub?  Does anyone have permission to edit devhub?  Hmmm.  Yes it's duplicated [here](https://marketplace.firefox.com/developers/docs/packaged).  Should I contact someone in charge of MDN docs like John Karahalis and ask him to remove that page?

**Comment by mattbasta** [comment]
Yeah, ask an MDNer to axe it. To update the devhub, just file a pull
request against [zamboni](https://github.com/mozilla/zamboni/tree/master/mkt/ecosystem/templates/ecosystem/) and I'll go ahead and merge it for you.

Also in the process, we're linking all of our CSP-related docs to
developer.mozilla.org/docs/Apps/CSP, so if you find any links to some other
CSP-related pages, just change them over. In fact, you can feel free to
just nix any CSP info (what the default CSPs are and stuff) since it's
redundant anyway.

**Comment by nickdesaulniers** [comment]
https://github.com/mozilla/zamboni/pull/662

**Comment by nickdesaulniers** [comment]
Nice!  So zamboni is updated, now I'll have to see about removing the MDN page.

**Comment by mattbasta** [comment]
Give it until Thursday when we push to prod. That way the page won't randomly disappear without having something for people to look at in its place.

**Comment by a2sheppy** [comment]
This sort of documentation needs to be on MDN. I was under the impression this material was due to be removed from DevHub in favor of the actual documentation being on MDN where it belongs.

**Comment by mattbasta** [comment]
For now, it should be removed from MDN to remove duplicate documentation. Current UX designs put this information on the devhub, though the devhub will eventually be eliminated and things will be moved back to MDN as soon as MDN has support for the features that our UX team is asking for.

**Comment by morgamic** [comment]
Hey - there's some confusion about things because it's now post-MWC and we haven't concluded UX/IA discussions.  For now, do this: put the document in MDN and sync it with devhub like we do with other docs.  We will work through the IA in the coming weeks.  Sorry for the confusion.

**Comment by fwenzel** [comment]
NB: There is no syncing between MDN and devhub any longer. Content changes to devhub can be made via pull request, but until the UX-driven redesign is in place, we won't mess with (or reintroduce) a syncing mechanism.

**Comment by mykmelez** [comment]
cc: @wbamberg, who is getting involved in Simulator documentation.

**Comment by mykmelez** [comment]
@wbamberg drafted docs for the Simulator on the following MDN page:

https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator

Please take a look and send him comments!

He didn't include screenshots for the "push to device" feature because he doesn't have a device. So it would be very helpful for someone with a device to take that on.

**Comment by nickdesaulniers** [comment]
What a nice looking MDN page, @wbamberg !  I'll take a look at it add some things.

**Comment by mykmelez** [comment]
@wbamberg There's an older MDN doc on the Simulator that is probably out-of-date by now:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_Firefox_OS_Simulator

It seems like we should consolidate these docs, adding info as appropriate from the older doc into the newer one and then redirecting the old one to the new one, so users always see a single page with the most up-to-date info.

Note that there's an even older URL where that document used to be located:

https://developer.mozilla.org/en-US/docs/Mozilla/Boot_to_Gecko/Using_Firefox_OS_Simulator

But that redirects to the newer URL now, and presumably a redirect from the newer URL to your doc will take care of that one too. Would be worth testing.

**Comment by mykmelez** [comment]
We should probably also redirect this whole section of the Packaged Apps doc to the appropriate section of the Simulator page:

https://developer.mozilla.org/en-US/docs/Apps/Packaged_apps#Testing_packaged_app_installation_%28with_Simulator%29

Presumably we can't do this automatically (i.e. via an HTTP redirect), since it's a section of a page rather than a whole page; but we could do it manually via a link in the text of the page.

**Comment by nickdesaulniers** [comment]
In the [Installing the Simulator add-on section](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Installing) the link to install from is an old version because we haven't yet gotten v3 reviewed.  The old version doesn't have some of the features such as orientation change or geolocation change.

**Comment by wbamberg** [comment]
@mykmelez - yes, once we're happy enough with the new page we'll replace the old one and have redirects and links to the new stuff. @a2sheppy is in town this weekend, so we can make that happen then.

When do you expect 3.0 to ship?

**Comment by wbamberg** [comment]
@nickdesaulniers  - yes, I was thinking that this documentation would be "released" along with 3.0 of the Simulator, at which point the version on AMO should be correct. But maybe it would be better to link to the pre-release build and note that it currently documents a pre-release, then we can just update that when 3.0 ships...

**Comment by nickdesaulniers** [comment]
I suspect that once 3.0 ships, @mykmelez doesn't plan on having preview builds anymore, since developers need to manually update them?

**Comment by mykmelez** [comment]
> When do you expect 3.0 to ship?

I hope to ship it late next week, but I expect to ship it early the following one.

> I suspect that once 3.0 ships, @mykmelez doesn't plan on having preview builds anymore, since developers need to manually update them?

I do still plan to have preview builds, but I hope to be able to distribute them from AMO via its [beta channel](https://addons.mozilla.org/en-us/developers/docs/policies/maintenance#beta-addons), which updates them automatically. But that will require the Simulator to get full review, which will take review time and might take additional development effort. So I may continue to distribute preview builds from ftp.mozilla.org in the meantime.

**Comment by nickdesaulniers** [comment]
In the [Managing Apps Section](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Managing_apps), where it says `It also gives us three commands:` is it too early in the page to mention the fourth, Push to device if connected?

**Comment by nickdesaulniers** [comment]
In the [Running the Simulator section](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Running_the_Simulator) where it says `if you add or update an app, ...` should also mention if you remove an app.

**Comment by wbamberg** [comment]
@ nickdesaulniers, thanks for the comments!

I added a little box at the top explaining that this documents a preview release (I don't like piling up these little boxes, but at least this one will be gone soon!) and updated the link. I'll go back and revert that when we release 3.0.

I also added your other suggestions, which made sense to me.

**Comment by mykmelez** [comment]
Closing this issue, as the work is done! (There's still a bit more work to do when we release 3.0, but we're tracking that elsewhere.)
