### ISSUE TITLE
Clear the manifest field after clicking add manifest

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#362]
STR:
1. Open Simulator
2. Paste "http://badappcache.testmanifest.com/manifest.webapp" into "URL for page or manifest.webapp"
3. Click Add URL
4. App is installed

Expected:
Field "URL for page or manifest.webapp" to clear, displaying the placeholder again

Actual:
http://badappcache.testmanifest.com/manifest.webapp stays in field

**Comment by mykmelez** [comment]
It looks like this got fixed at some point (although starting the badappcache app crashes the Simulator!).
