### ISSUE TITLE
Validation Result INVALID for just warnings

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#365]
The validator current marks the validation as failed when only 1 warning was found.

Warnings shouldn't mark validation failed.

On wording: Does something actually fail, or would it make more sense to label it "Invalid Manifest"? We still allow all actions on the app, it's a bit confusing.

**Comment by rpl** [comment]
should be fixed by #375 

now app with warnings are market "WARNINGS" instead of "INVALID"

I'm closing it, but please reopen if the current solution is not enough.
