### ISSUE TITLE
FirefoxOS emulator crash - starting "Hello world" application

### ISSUE THREAD

**Issue by m0rg0t** [mozilla/r2d2b2g#368]
Using 
- Firefox - 19.0.2
- FirefoxOS emulator - 2.0
- OS - Windows 8 Pro x64

After pressing "Run" for application, emulator start work and in 1-2 seconds close.

If press "update" for application - get such errors:

> Timestamp: 09.03.2013 14:38:00
> Error: TypeError: bluetooth is undefined
> Source File: app://system.gaiamobile.org/js/bluetooth.js
> Line: 36
> 
> Timestamp: 09.03.2013 14:38:00
> Error: TypeError: wifiManager is undefined
> Source File: app://system.gaiamobile.org/js/wifi.js
> Line: 52
> 
> Timestamp: 09.03.2013 14:38:02
> Error: [Exception... "Component returned failure code: 0x80004005 >(NS_ERROR_FAILURE) [nsIProperties.get]"  nsresult: "0x80004005 >(NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 63"  data: no]
> Source File: resource://gre/modules/FileUtils.jsm
> Line: 63

Example of mainfest and index.html file:

``` json
{
    "name":"Gde posilka?",
    "launch_path": "/index.html",
    "developer": {
        "name":"m0rg0t",
        "url":"m0rg0t.ru"
    },
    "description":"description",
    "icons": {
        "128":"/icon_128.png"
    }
} 
```

``` html
<html>        
<head>
      <meta charset="UTF-8">
      <script src="https://myapps.mozillalabs.com/jsapi/include.js"></script>
</head>
<body><p>hello world</p></body>
</html>
```

**Comment by nickdesaulniers** [comment]
@m0rg0t , hey thanks for reporting this issue!  I noticed you're running an outdated version of the simulator.  Do you mind removing it from about:addons, then reinstalling the latest (3.0pre2) and re-verifying?  We're working on getting this addon to auto update, but in the meantime, updates are manual.

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by m0rg0t** [comment]
At 3.0pre2 still have

> Error: [Exception... "Component returned failure code: 0x80004005 >(NS_ERROR_FAILURE) [nsIProperties.get]" >nsresult: "0x80004005 >(NS_ERROR_FAILURE)" location: "JS frame :: resource://gre/modules/FileUtils.jsm :: >FileUtils_getDir :: line 63" data: no]
> Source File: resource://gre/modules/FileUtils.jsm
> Line: 63

And can't install app to emulator (but this version don't crush)

**Comment by LordAmit** [comment]
I am also using this version 3.0pre3, in Linux Mint 64 bit. These errors show up when I run the simulator and then try to execute a simple hello world app.
I use Firefox 19.0.2

> Timestamp: 03/24/13 14:59:54
> Error: TypeError: bluetooth is undefined
> Source File: app://system.gaiamobile.org/js/bluetooth.js
> Line: 36
> 
> Timestamp: 03/24/13 14:59:54
> Error: TypeError: wifiManager is undefined
> Source File: app://system.gaiamobile.org/js/wifi.js
> Line: 52
> 
> Timestamp: 03/24/13 14:59:59
> Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 63"  data: no]
> Source File: resource://gre/modules/FileUtils.jsm
> Line: 63
> 
> Timestamp: 03/24/13 15:01:48
> Error: TypeError: window.navigator.mozMobileConnection is undefined
> Source File: app://costcontrol.gaiamobile.org/js/config_manager.js
> Line: 104
> 
> Timestamp: 03/24/13 15:03:26
> Error: TypeError: gMobileConnection.sendMMI is not a function
> Source File: app://settings.gaiamobile.org/js/about.js
> Line: 90

**Comment by m0rg0t** [comment]
Seems same bug like i have.

Maybe problem somewa connected with using 64 bit OS?

(try same at 32 bit)

**Comment by mykmelez** [comment]
I'm not sure those console messages are relevant to this problem. And the Linux issue may be a different one. We do have known issues on Windows 8, i.e. #310 and #380. So this could be one of those.

What do you see in the Error Console if you use about:config to add the preference extensions.r2d2b2g@mozilla.org.sdk.console.logLevel, give it the integer value 0, and then disable/reenable the addon?

**Comment by LordAmit** [comment]
HI @mykmelez 
I have added extensions.r2d2b2g@mozilla.org.sdk.console.logLevel in about:config as Integer type, set value to 0.
Then I have disabled the add on, several warnings were found in the error console of firefox, none were related to Firefox OS simulator IMO. However, when I enabled it - the following warnings + error were shown:

> debug: r2d2b2g: XULAPP:  Firefox 19.0.2 19.0.2
> debug: r2d2b2g: HAS_CONNECT_DEVTOOLS:  false
> info: r2d2b2g: simulator.observe: adb-ready
> Timestamp: 04/02/2013 02:46:27 AM
> Error: can't access dead object
> Source File: resource://gre/modules/XPIProvider.jsm -> file:///home/amit/.mozilla/firefox/mwad0hks.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js
> Line: 1004

**Comment by mykmelez** [comment]
> Error: can't access dead object

This is probably #416, which you can work around by reloading the Dashboard tab.

**Comment by mykmelez** [comment]
The latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) fixes that "can't access dead object" problem, although you may need to restart Firefox once after installing it to completely make the problem go away. Give it a try, and let me know how it works for you!

**Comment by LordAmit** [comment]
@mykmelez , Works better for me now! :D

**Comment by mykmelez** [comment]
@lordamit Great, thanks for the update!
