### ISSUE TITLE
After you add an app to simulator via "Add URL", the file input box should be cleared.

### ISSUE THREAD

**Issue by KWierso** [mozilla/r2d2b2g#370]
From the demo today at the devtools work week, @mykmelez added an app to the simulator. After he did this, the file input continued to list the selected path to the manifest file.

In my opinion, there probably isn't a need to re-add an already added app via URL, so the input should be cleared after the app is successfully added.

**Comment by KWierso** [comment]
document.getElementById("form-add-app").reset() would do this, right?

**Comment by mykmelez** [comment]
Closed by pull request #376.
