### ISSUE TITLE
Videos Playing Choppy

### ISSUE THREAD

**Issue by Ranger7** [mozilla/r2d2b2g#371]
Will this new version of Mozilla take care of my Videos Playing Choppy ? This is very frustrating. Thanks.

**Comment by mykmelez** [comment]
This issue tracker is for reporting issues with the Firefox OS Simulator, not Firefox itself (which is what I'm guessing you mean by "Mozilla"). For help figuring out your issue, please check out [mozilla support](https://support.mozilla.org/), for example [this article about choppy video](https://support.mozilla.org/en-US/questions/940559).
