### ISSUE TITLE
"add to Dashboard" silent fails to appear if validation doesn't manage to start simulator

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#374]
When you add an app to the dashboard, the validator runs the simulator to validate the permissions. But if the simulator doesn't start for some reason, then the validation process never finishes, and the app doesn't appear on the dashboard.

Reloading the dashboard causes the app to show up. But it hasn't been validated, and I suspect it also isn't initialized correctly (since much initialization happens in _updateApp(), which doesn't get called until updateApp() gets called back by the validator).

I noticed this because it happened to me on several occasions over the last couple days. Unfortunately, I don't have steps to reproduce consistently. When it occurs, I can often cause it to recur a few times by removing and readding the same app. But eventually it stops recurring. No error messages are written to the consoles.

We should find and fix whatever problem is preventing the simulator from starting up. But I wonder if we should also remove the dependency between the validator and the simulator, given that apps you add to the dashboard should always show up on it. They should never silently fail to appear.

@rpl, what do you think?

**Comment by rpl** [comment]
@mykmelez I agree, we should neve silently fail.

proposed a fix on #375

**Comment by mykmelez** [comment]
Fixed by #375.
