### ISSUE TITLE
Notifications panel gets in the way

### ISSUE THREAD

**Issue by Carter10** [mozilla/r2d2b2g#381]
Whenever I try to play a game, the notifications panel covers up a part of the screen, and this is slightly less than satisfactory. It ruins the entire gaming experience

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
