### ISSUE TITLE
FireFox OS Web Browser Overlay Bug?

### ISSUE THREAD

**Issue by dorman** [mozilla/r2d2b2g#382]
I started to try and test the browser to see how well it could do with having at least 20 tabs open and everything was good until I went back to create a new tab and after I chose which site to go to for the tab then the browser goes back to the main browser screen and a strange overlap of the tabs appear. I don't know if this is supposed to happen or if this is just because I have so many tabs open at once it shrinks them all down to size, but it still looks to me like there is some overlap. 

However, I couldn't seem to reproduce the bug when I tried. So I tried clicking on one of my previously created tabs and after that the same bug appeared once again. I have two screenshots below of the process.

![Overalbug2](https://f.cloud.github.com/assets/150633/275729/6885bb58-9098-11e2-8aa5-80b80982c0f9.jpg)

![Overlaybug](https://f.cloud.github.com/assets/150633/275745/d8ce73dc-9098-11e2-9189-4f9ef24eaa45.jpg)

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
