### ISSUE TITLE
Penguin pop not working only white frame visible after launch.

### ISSUE THREAD

**Issue by czerek** [mozilla/r2d2b2g#384]
On Windows 8, using  Firefox OS Simulator 2.0 and Mozilla Firefox ver. 19.0.2. 
![fos1](https://f.cloud.github.com/assets/3929896/285138/ee9405a6-920f-11e2-9764-ab67fb1c7051.png)

**Comment by mykmelez** [comment]
Thanks for reporting this problem! However, the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. Report those in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko&component=Gaia), making sure to note that you noticed the problem in the Simulator.
