### ISSUE TITLE
can't find Addon anymore (Nightly 22.0a1 (2013-03-21))

### ISSUE THREAD

**Issue by platzhersh** [mozilla/r2d2b2g#385]
Hello there,
I can't find the Addon anymore under the "Web Developers" menu.. has it been moved?

**Comment by nickdesaulniers** [comment]
Can you check by visiting "about:addons" in your URL bar?

**Comment by platzhersh** [comment]
sure, I did :) looks fine, I even reinstalled the addon. Still I can't find it in the "Web Developers" menu

**Comment by jincreator** [comment]
This bug also affects me.
I can't find it in menu, so I tried "firefoxos manager" command in GCLI.
It shows message balloon, "TypeError: activeWindow is null".

**Comment by mykmelez** [comment]
This is almost certainly due to a change in Nightly that breaks the stable version of the Simulator. Please try downloading the latest preview build of the next version, and let us know if it works for you!

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by jincreator** [comment]
Sorry for not mentioning r2d2b2g version I'm using.
I used 3.0pre3 before, and I still can't find it in menu after install 3.0pre4.

**Comment by mykmelez** [comment]
There's a known issue with nightly builds and the stable release of the Simulator (2.0), so I pushed a 2.0.1 hotfix that is in the review queue on AMO. In the meantime, it's available from ftp.mozilla.org:

Windows: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-2.0.1-windows.xpi
Mac: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-2.0.1-mac.xpi
Linux: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-2.0.1-linux.xpi

However, there are no known issues with 3.0pre4 on nightly builds, and it should be working! So I'm not sure why it isn't working for you. What shows up in the Error Console if you use about:config to set the extensions.r2d2b2g@mozilla.org.sdk.console.logLevel preference to the integer value 0 and then disable/reenable the addon?

**Comment by jincreator** [comment]
Mozilla/5.0 (X11; Linux x86_64; rv:22.0) Gecko/20130329 Firefox/22.0
Firefox OS Simulator 3.0pre4

My nightly is localized build, so I translate some words(e.g Time, Error, Source File, Line Number, ...)

debug: r2d2b2g: XULAPP:  Firefox 22.0a1 22.0a1
debug: r2d2b2g: HAS_CONNECT_DEVTOOLS:  true
info: r2d2b2g: simulator.observe: adb-ready

Time: 2013년 03월 30일 09시 07분 21초
Error: can't access dead object
Source File: resource://gre/modules/XPIProvider.jsm -> file:///home/jincreator/.mozilla/firefox/tp1876il.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js
Line Number: 1017

Time: 2013년 03월 30일 09시 07분 21초
Error: can't access dead object
Source File: resource://gre/modules/XPIProvider.jsm -> file:///home/jincreator/.mozilla/firefox/tp1876il.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js
Line Number: 1017

Time: 2013년 03월 30일 09시 07분 21초
Error: can't access dead object
Source File: resource://gre/modules/XPIProvider.jsm -> file:///home/jincreator/.mozilla/firefox/tp1876il.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js
Line Number: 1017

There was more log messages, but I only upload things (seem) have relationship with r2d2b2g.

**Comment by platzhersh** [comment]
Now I see it again in 23.0a1 (2013-04-04)

**Comment by nickdesaulniers** [comment]
Cool, thanks for reporting this bug anyways.  It still helps us keep track of everything.  Please don't hesitate to open any bugs in the future!

**Comment by mykmelez** [comment]
>  Error: can't access dead object

@jincreator: This particular issue is probably #416, which you should be able to work around by reloading the Dashboard page.

**Comment by jincreator** [comment]
@mykmelez Sorry, I have no Idea how to reload the Dashboard page. For now, I still can't find menuitem. Could you explain little bit more?

**Comment by mykmelez** [comment]
@jincreator Sorry, I misunderstood the issue you are experiencing. If you can't see the menuitem, then it probably isn't #416. The error in your log says it's happening with line 1017 in simulator.js, but that line in the 3.0pre4 build is a simple call to console.log:

```
console.log("simulator.observe: " + topic);
```

And "can't access dead object" is supposed to happen when an addon tries to access a DOM object for a DOM window that has been destroyed, per [this blog post](https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/).

So I'm not sure what's going on. cc: @ochameau, who might have an idea. In the meantime, you might try updating to the latest preview release ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) to see if it happens to solve the problem.

**Comment by jincreator** [comment]
@mykmelez I think I find the reason. I open new issue, #431
Also, I suggest to mark this issue as closed.

**Comment by mykmelez** [comment]
@jincreator Thanks for figuring that out! I've done some testing and added some notes to the new issue. Hopefully we can resolve it soon!

**Comment by white-gecko** [comment]
I also can't find the menu entry in Web Developers sub-menu.
I have Debian testing with Iceweasel 20.0 (Mozilla/5.0 (X11; Linux x86_64; rv:20.0) Gecko/20100101 Firefox/20.0 Iceweasel/20.0) and Firefox OS Simulator 4.0pre1.
I don't have History set to “Never remember history” so it is different from #431

**Comment by mykmelez** [comment]
@white-gecko Hmm, it sounds like you are experiencing #423, which is an Iceweasel-specific issue.

**Comment by white-gecko** [comment]
@mykmelez ok, thank you I thought the only difference is the name and the icon
