### ISSUE TITLE
Hidden text in the manifest.webapp input box

### ISSUE THREAD

**Issue by davidgomes** [mozilla/r2d2b2g#387]
I got confused by the extension of the manifest file and because only "URL for page or manifest.weba" is visible, I thought that the extension was ".weba".

This happens because the input box is too small.

**Comment by nickdesaulniers** [comment]
This may be dependent on screen res.

**Comment by davidgomes** [comment]
My thoughts exactly, so this either needs input from somebody more experienced with CSS or testing on different resolutions.
