### ISSUE TITLE
Firefox OS simulator not opening in beta 20 version

### ISSUE THREAD

**Issue by sapien-pixel** [mozilla/r2d2b2g#389]
Hi,

The Simulator is not working in the beta 20 version build- 5 of firefox. When i start the simulator it pops up new window and it automatically stops.
Dont know why.
I am using windows 7 and x86 processor

**Comment by mykmelez** [comment]
Thanks for reporting the problem, and sorry to hear the Simulator isn't working for you! Could you try installing the [latest preview build for Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi) to see if it still has the problem?

**Comment by nickdesaulniers** [comment]
bump @DhruvKalaria

**Comment by mykmelez** [comment]
Closing this due to lack of needed info. But please do reopen if you can provide that info!
