### ISSUE TITLE
Put icon to the left of app details

### ISSUE THREAD

**Issue by davidgomes** [mozilla/r2d2b2g#390]
On the list of installed apps on the index.html, on the left of the app details (name, type of app, open location, etc) the icon of the app could be added (if it exists) and the default icon for no-icon if there's no icon.

**Comment by mykmelez** [comment]
I like this idea. It would certainly help to distinguish between the various apps in the list.

**Comment by mykmelez** [comment]
This was just fixed by @louisstow in #513, and the fix will make it into the next preview build!
