### ISSUE TITLE
need of a firefox account sync 

### ISSUE THREAD

**Issue by leandroruel** [mozilla/r2d2b2g#391]
if user forgot your password, he need go to firefox account to recover the password, to download apps, or unlock the device (in the case of many attempts by blocking access denied)

**Comment by mykmelez** [comment]
Hi @leandroruel, thanks for reporting this problem. However, I'm not sure exactly what problem you're reporting. It sounds like you're saying that a user who forgets his password has to go through some procedure to recover it, but that doesn't sound like an issue in the Simulator. Perhaps you can explain further?

**Comment by leandroruel** [comment]
okay, i not speak english well, but imagine the following situation, the user in a future wants lock your device, with screen lock combination or password (security), if available this resource, but...if the user forget your password or screen lock combination, he need unlock the device again with a account, and recover it, and to do this, the user need of a option on firefoxOS to create a account, and sync it, before configuring a screen lock.

Example:
1. user want configure screen lock. > create a firefoxOS account before screen lock configuration. > user configures your screen lock. 
2. user forgot your screen lock combination > after try unlock three times firefoxOS request the account credentials. > firefoxOS sync account with device and the user unlocks the device again.

sorry again by my english

**Comment by mykmelez** [comment]
@leandroruel That's an interesting idea! But it sounds like a feature request for Firefox OS rather than the Simulator, which is just a tool for developers to test their apps in an environment that resembles the one that we'll put on Firefox OS phones. So I recommend you suggest it in the [Gaia forum](https://groups.google.com/forum/#!forum/mozilla.dev.gaia).
