### ISSUE TITLE
Don't work event listener(click) in Google map

### ISSUE THREAD

**Issue by tokovenko** [mozilla/r2d2b2g#403]
In my app I use Google Map. When I run my application in browser, everything is ok,but in r2d2b2g don't work event listener(click) and balloons on map dont't open. When I run this page https://google-developers.appspot.com/maps/documentation/javascript/examples/event-simple?hl=ru like application I have the same problem.

**Comment by mykmelez** [comment]
Hi @LivingBlues, sorry for the delay responding! Is your app publicly available? It's hard to know what the problem is without being able to see the code of the app. You might also try checking the Error Console to see if a relevant error is being reported there.

**Comment by tokovenko** [comment]
Now everything is ok. After update mozilla browser, event work normal

**Comment by mykmelez** [comment]
@LivingBlues Great, thanks for the update!
