### ISSUE TITLE
Some applications change the simulator window size

### ISSUE THREAD

**Issue by hyvakeke** [mozilla/r2d2b2g#404]
Starting some applications, BlockedCar for example, change the simulator window size and only way to fix this is to restart the simulator. I'm using the simulator on Windows 7.

![window_size](https://f.cloud.github.com/assets/1122993/323900/debab15a-9ad1-11e2-987d-8a6c1e10a681.png)

**Comment by hyvakeke** [comment]
The problem also occurs when long pressing the home button and the app switcher is displayed.

**Comment by mykmelez** [comment]
I don't see this with the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). Can you still reproduce the problem with that build?

**Comment by hyvakeke** [comment]
Cannot reproduce with 3.0 anymore.
