### ISSUE TITLE
Home button needs to be discoverable

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#41]
Currently, the user must push the home key on the keyboard (fn-left arrow on my Mac) to simulate the home button on the device. Since this is an extremely important thing for users to know, I think we should do something along these lines:
- put a Home button on a toolbar (with a Rotate button as well, if we can get that in v1). A tooltip that reflects the keyboard shortcut would be useful, or
- add a menu item to the B2G menu that says "Home"

I think the first is preferable, but the second is fine too if that's all we have time for.

**Comment by mykmelez** [comment]
Fixed by the aforementioned pull.

**Comment by mykmelez** [comment]
Note that I didn't implement a tooltip because adding a tooltip to the toolbar button caused B2G Desktop to crash when it tried to display the tooltip.

**Comment by dangoor** [comment]
OK, sounds good. I'm looking forward to seeing this in tomorrow's build!
