### ISSUE TITLE
manifest.webapp with a missing icon section caused the simulator to ignore a packaged app

### ISSUE THREAD

**Issue by mblayman** [mozilla/r2d2b2g#426]
I had a packaged webapp that had a valid minimum manifest (i.e. name and description), but every time I tried to add it to the simulator via the "Add directory" button, the interface would ignore it. It did not report that the manifest was missing necessary information for packaged apps so I had no direction about what was wrong.

I looked more closely at the manifest page and noticed that packaged apps are required to have at least one icon defined. As soon as I add the icon section, the app was recognized by the simulator the next time I tried to add via "Add directory."

I'm on Ubuntu 13.04 Beta 1 with Firefox 20 and Firefox OS Simulator 2.0.1.

**Comment by mykmelez** [comment]
@mblayman Urk, that is indeed a bad user experience. I'm sorry to hear you had to suffer through it! Fortunately, the [new stable release](https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/) has a manifest validator feature written by @rpl that will tell you if your manifest is missing icons (while also successfully installing the app in the Simulator, FxOS itself doesn't require an icon to install an app, although Fx Marketplace does require an icon to distribute an app).

**Comment by mblayman** [comment]
Cool. I love the simulator and how easy it is to use. Thanks for the good work!
