### ISSUE TITLE
Allow for addition of default receipt for installed apps to test paid apps

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#427]
If one wants to test receipt validation for a paid app, the appRecord returned by navigator.mozApps.getSelf must have a receipts property that is an array of receipt objects.  If there are no receipts, than it should be an empty array.  Currently, for apps installed through the simulator, the receipts property exists, but is null.  So if I want to test my paid packaged app, I must use the simulator to develop in (as most privileged APIs are b2g only, so far), but I can't actually test something like receipt verification for instance.

A receipt is bound to the appRecord during the call to navigator.mozApps.install as the second argument.

A receipt cannot be modified after installation but client side code can read and modify an in memory copy before sending it off to be validated, it just can't be written back to the appRecord from client side code.

I propose adding a button to the dashboard page for each installed application to add a default receipt.  The [validating a receipt MDN page](https://developer.mozilla.org/en-US/docs/Apps/Publishing/Validating_a_receipt) has more info on the fields within a receipt.  It may be nice to allow the developer to customize a few fields, especially the product  and verify fields.  But that can be a v2 improvement.  For now, maybe make all receipts have the product.storedata default to 1.

**Comment by kumar303** [comment]
I don't really see how the simulator can be responsible for this. Creating a cryptographically valid receipt can only done by a signing authority such as the Marketplace (or any store).

It sounds like the Marketplace is in a better position to offer receipts for developer testing purposes. See these for progress on that:
https://bugzilla.mozilla.org/show_bug.cgi?id=855912
https://bugzilla.mozilla.org/show_bug.cgi?id=863015

**Comment by wfwalker** [comment]
Can we wire up the simulator to somehow use https://marketplace.firefox.com/developers/test/receipts/ ?

**Comment by wfwalker** [comment]
see https://bugzilla.mozilla.org/show_bug.cgi?id=865498

**Comment by nickdesaulniers** [comment]
Note to self, don't forget to test the case where an app is:
- hosted
- packaged
- generated

**Comment by nickdesaulniers** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=867265

**Comment by kumar303** [comment]
Currently you have to log in to the Marketplace Devhub to get a test receipt. However, we can maybe expose this with the [Marketplace API](http://firefox-marketplace-api.readthedocs.org/en/latest/). I'm half expecting @andymckay to tell me it's already there :)

**Comment by andymckay** [comment]
Ok, if you insist: http://firefox-marketplace-api.readthedocs.org/en/latest/topics/payment.html#test-receipts

**Comment by kumar303** [comment]
Heh, full circle. Sorry, I was behind on bugmail.

**Comment by nickdesaulniers** [comment]
Fixed in #509
