### ISSUE TITLE
add make clean target

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#442]
We should have a `make clean` target that removes downloaded and generated files, including:
- B2G package and bindir (addon/data/PLATFORM/b2g/)
- ADB package and bindir (addon/data/PLATFORM/adb/)
- Gaia profile and associated files (addon/template)
- gaia/build/custom-prefs.js
- perhaps also a `make clean` in the gaia/ subdirectory

**Comment by nickdesaulniers** [comment]
Note: B2G package and bindir (`addon/data/PLATFORM/b2g/`) on OSX is `addon/data/PLATFORM/B2G.app/`

**Comment by nickdesaulniers** [comment]
Fixed in #447
