### ISSUE TITLE
How to change the direction (right to left) of reader.

### ISSUE THREAD

**Issue by khajafairoz** [mozilla/r2d2b2g#461]
Hi, I am developing a arabic book reader, so i have display the reader as 'rtl' (right to left) direction, i am not getting how to do it please any one can help.

**Comment by mykmelez** [comment]
Hi @khajafairoz, that's a great question, but unfortunately this isn't a great place to get it answered, as there are only a small number of app developers who pay attention to this issue tracker. I recommend you try posting to the [webapps forum](https://groups.google.com/forum/#!forum/mozilla.dev.webapps) or the [Gaia forum](https://groups.google.com/forum/#!forum/mozilla.dev.gaia).
