### ISSUE TITLE
Settings app on simulator doesn't show same set of locale choices as b2g phone

### ISSUE THREAD

**Issue by wfwalker** [mozilla/r2d2b2g#462]
When I go to the Settings app on my Unagi b2g phone, I get to choose from among nearly two dozen languages; when I do the same thing from Simulator 3.0 pre6, I can choose only English, French, Chinese, and Arabic. I would like to test the Portuguese localization of my app using the simulator, but don't know how.

**Comment by mykmelez** [comment]
I don't think we want to include the full two dozen languages that are on the Unagi development devices. Each language adds to the Simulator's already-significant download size, and a full set (currently 46 in Gaia's languages_all.json configuration file) adds ~3MB. But we should certainly add a few more languages to the list, including Portuguese. I hear that the following would be particularly valuable:
- Spanish
- Portuguese (br) 
- Polish
- German
- Hungarian
- Hebrew

> I would like to test the Portuguese localization of my app using the simulator, but don't know how.

Until I spin the next preview build (tomorrow), you can build your own copy of the Simulator with all available languages:

```
git clone git://github.com/mozilla/r2d2b2g.git
cd r2d2b2g/
git submodule init
git submodule update
export LOCALES_FILE=${PWD}/gaia/locales/languages_all.json
make locales
make build
```

To test the build (starts Firefox with addon preinstalled in a temporary profile), do:

`make run`

Then, to produce a redistributable package (at _addon/r2d2b2g.xpi_) that you can install into your regular Firefox profile:

`make package`

**Comment by mykmelez** [comment]
[Minus two stars for not having Spanish!](https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/reviews/456578/)

**Comment by mykmelez** [comment]
In 6657abbfbb048af8c4c96ea15623163d573164de I added a languages file with the following languages:
- عربي
- Deutsch
- English (US)
- Español
- Français
- עברית
- Hrvatski
- Magyar
- Português (do Brasil)
- 正體中文 (繁體)

That's the file I'll use to create builds like the latest preview build, which I pushed this morning.
