### ISSUE TITLE
Remove Install Page as App menu item

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#47]
...to put the focus on commonly used features, point people to use the Manager more, and ensure that people will be more likely to point to manifests or at least the page they really want.

**Comment by digitarald** [comment]
Removed. We still have context menu for *.webapp links, which seems a useful place but nobody will discover unless we document it. My user story: the app lookup in Marketplace offers a link to the manifest that I was able to click and install to test the app.

**Comment by dangoor** [comment]
Sounds good. I see no trouble with a context menu item for .webapp links. Thanks!
