### ISSUE TITLE
Use watch position for geolocation

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#470]
The user/developer's current coordinates may change as they develop.  Use watchPosition instead of [getCurrentPoition](https://github.com/mozilla/r2d2b2g/blob/6d2b02252b55acd17485457e45cdfbd2438ba1ff/addon/lib/remote-simulator-client.js#L253).  You would then need to add an r2d2b2g:geolocation-stop request from shell on custom selection to the dbg-simulator-actors, then to remote-simulator-client.

The issues that arise involves the [timer in the FakeGeolocationProvider](https://github.com/mozilla/r2d2b2g/blob/6d2b02252b55acd17485457e45cdfbd2438ba1ff/prosthesis/components/FakeGeolocationProvider.js#L85).

When using custom coordinates, how often should the timer fire?  Currently, it's every second.  When we use current coordinates though, we don't want to use a timer, and instead want to update whenever the Firefox process (remote-simulator-client) receives a watch update.  That way, the app behaves as if it's using a real life watchPosition call (because it is).  Maybe a timer could be defined during start up, but reinitialized during each update from the shell (meaning only for custom coordinates).

Also, is it important that the developer be able to specify the period of the timer?

**Comment by mykmelez** [comment]
We shouldn't need a timer at all after switching to watchPosition. At that point FakeGeolocationProvider can simply update its callback each time it receives an update from Firefox (when "current coordinates" is selected and the watchPosition callback gets an update) or from the shell (when "custom coordinates" is selected and the developer updates the coordinates).

**Comment by nickdesaulniers** [comment]
fixed in #544
