### ISSUE TITLE
mozSystem set to false when app run via dashboard

### ISSUE THREAD

**Issue by DiscoStarslayer** [mozilla/r2d2b2g#474]
Responses don't return and XMLHttpRequest.mozSystem returns false when I click 'run' from the dashboard and the simulator is running. If I click on the app icon itself in the simulator, mozSystem becomes true and my program gets responses.

How to reproduce:
Add systemXHR to manifest. Run this js:

var request = new XMLHttpRequest({mozSystem: true});
alert(request.mozSystem);

Install to simulator. Start simulator. Click the run button on the dashboard for the app.

Will alert true if run from within simulator by clicking on app's icon, but false if ran through the simulator's dashboard.

**Comment by mykmelez** [comment]
@rpl Any idea what might be different about the _run_ command that could cause this?

**Comment by DiscoStarslayer** [comment]
I'm not sure, but the problem seems to be gone now that I've updated r2d2b2g.
