### ISSUE TITLE
Simulator doesn't work in Nightly 23.0a1

### ISSUE THREAD

**Issue by Gioyik** [mozilla/r2d2b2g#475]
Hi,

I tried to install the Simulator 3.0pre8 Linux in Nightly 23.0a1, there are some problems.
- The Firefox OS simulator option in the Developer Tools menu doesn't exist or is not created after the installation
- The only way to access at the Simulator is puting in the url bar: resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html
- If i try to run the Simulator clicking on the start button, it never starts
- If i close Nightly and i start again, the SImulator is not installed

Someone could check this?

Thanks,
Gio

**Comment by mykmelez** [comment]
Hi @Gioyik, what distribution and version of Linux are you running, and is it a 32-bit or 64-bit installation? Also, if you open up the Error Console after starting Firefox, do you see any messages in the console? If not, then try using about:config to set extensions.r2d2b2g@mozilla.org.sdk.console.logLevel to the integer value 0 (zero), restarting Firefox, and checking the Error Console again. Let me know what messages appear!

**Comment by GalegO** [comment]
Same thing on Windows 8 64bits using Nightly 23.0a1 (2013-05-02)...

**Comment by mykmelez** [comment]
This could be the "can't access dead object" bug that we fixed recently. Please try installing the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)), then restart Firefox and see if you can access the Simulator. If not, please use about:config to set extensions.r2d2b2g@mozilla.org.sdk.console.logLevel to the integer value 0 (zero), restart Firefox again, try to access the Simulator again, and let me know what messages appear in the Error Console!

**Comment by Gioyik** [comment]
Hi @mykmelez 

My system is Ubuntu 13.04 32 bit, using Firefox Nightly 23.0a1. I have been installed the latest build of the Simulator but it doesn't work. The Simulator option in the Developer Tools Menu is not there, i nees to put in the url bar this to access at the simulator dashboard:

resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html

And if i click on the start buttom to open de Simulator, it doesn't open the new window with the simulator. i set the extensions.r2d2b2g@mozilla.org.sdk.console.logLevel in about:config but it doesn't work and the console error doesn't show nothing related to the Addon.

Is this a Bug?

I attach a screenshot

![captura de pantalla de 2013-05-04 00 15 02](https://f.cloud.github.com/assets/1834718/462135/98951e64-b47a-11e2-85e9-3183c0127615.png)

**Comment by Gioyik** [comment]
Other problem is that it doesn't show the words in the dashboard:

No apps added yet? Add some...

I Attach an image to show the problem.

![captura de pantalla de 2013-05-04 00 30 09](https://f.cloud.github.com/assets/1834718/462142/0bb1b500-b47c-11e2-8350-5394e1fc6781.png)

**Comment by ltedone** [comment]
I have the same problems on Ubuntu 13.04 32 bit with the latest version of Firefox Nightly

**Comment by tschuxi** [comment]
Same problem on Debian Wheezy.
Since I updated to Firefox OS-Simulator 3.0 on Iceweasel 21.0a -> no Menu-Entry and unable to start over resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html
Also after updated to Iceweasel 22.0a2 -> no no Menu-Entry and unable to start

**Comment by tschuxi** [comment]
Ups sorry, this issue is for Nightly 23.0a1.
My problem is fixed now. I deinstalled the Simulator AddOn and deletet the directory .mozilla/b2g/. After this I reinstalled the AddOn. Now it works.

**Comment by Gioyik** [comment]
Sorry, but this problem continue for me.

**Comment by mykmelez** [comment]
The Iceweasel issue is probably #423, which is a bug in Iceweasel itself.

The other problems sound like they might be #518, which prevents the Simulator from loading in recent builds of Nightly. Until we fix that bug, the workaround is to use an Aurora, Beta, or release build of Firefox.

**Comment by mykmelez** [comment]
We fixed #518, and the fix is in the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)), so I think this issue is now resolved. Please try installing the latest preview build, and reopen the issue if you still experience the problem!

**Comment by ltedone** [comment]
It doesn't work for me, I'm using Nightly 24.0a1 (2013-05-17); I unistalled the version 3.0, rebooted my pc and then installed the version above; after the installation I can use the simulator and there is the entry in the tools menu, but if I close the browser and then open it the menu entry is not visible

**Comment by mykmelez** [comment]
> It doesn't work for me, I'm using Nightly 24.0a1 (2013-05-17); I unistalled the version 3.0, rebooted my pc and then installed the version above; after the installation I can use the simulator and there is the entry in the tools menu, but if I close the browser and then open it the menu entry is not visible

Is there any chance you've configured Firefox to "never remember history" in its preferences? If so, then you might be running into #431.

**Comment by ltedone** [comment]
No Myk, it remembers history, I checked in my preferences

**Comment by ltedone** [comment]
I found that if I disable the simulator in the add-ons panel and then enable it again the menu entry is shown

**Comment by mykmelez** [comment]
@ltedone Just to make sure I understand: the menu entry never appears when you first start the browser, but it always appears after you disable/reenable the addon?

**Comment by ltedone** [comment]
@mykmelez the menu entry appears when I instal the simulator, then it disappears when I close and reopen the browser. But if I disable/reenable the addoin it appers again, until I close the browser.

**Comment by mykmelez** [comment]
@ltedone It sounds like you're experiencing a different problem, since the behavior you're noticing is somewhat different from the behavior originally reported in this issue (even though the end result is the same: you can't use the Simulator). Can you create a new issue for your problem? That way we can work on it without getting it confused with the issue that was originally reported here.

**Comment by ltedone** [comment]
@mykmelez It seems fixed right now, I have the menu entry after the browser restart

**Comment by mykmelez** [comment]
@ltedone Ah, great, thanks for the quick update!
