### ISSUE TITLE
Modified step-7,8 of CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#478]
Hi,
I  have modified steps-7,8 of CONTRIBUTING.md.
Step-8 suggested changing to a directory and run make which didn't have a Makefile
and step-7 is modified in accordance to a Feature newly added.
I have a patch and i have sent a pull request.
Thanks.

**Comment by nickdesaulniers** [comment]
Fixed in #479 
Thanks @SoumenG !
