### ISSUE TITLE
simulator works only once when it was installed first time

### ISSUE THREAD

**Issue by waqar1** [mozilla/r2d2b2g#489]
i installed simulator for windows  . I am using mozile firefox 20.0.1 on windows 7 64-bit. It worked for the first time after that it shows running but no simulator shows nor it works

**Comment by mykmelez** [comment]
Hi @waqar1, what version of the Simulator are you using? You might try installing the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)), restarting Firefox, and then seeing if it makes any difference.

**Comment by waqar1** [comment]
thanks for your reply i installed latest version of simulator and it solved the problem for me. Thanks for your kind reply.

Date: Fri, 3 May 2013 16:28:41 -0700

**Comment by mykmelez** [comment]
@waqar1 Great, thanks for the update!
