### ISSUE TITLE
Provide a changelog with each release

### ISSUE THREAD

**Issue by jeffgca** [mozilla/r2d2b2g#491]
The publishing platform for the simulator is currently AMO - if possible we should provide high-level changes there with a link to a full changelog if possible.

**Comment by mykmelez** [comment]
I just added a link to the release announcement, which describes high-level changes, and GitHub comparisons of the Simulator and Gaia, which provide ⅔ of a full changelog (the missing ⅓ being the B2G changelog; although I suppose one might quibble with the absence of the Add-on SDK from my "changelog completeness" calculations), into the description of the addon on its [AMO listing](https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/).

**Comment by jeffgca** [comment]
Worth considering automating this as we go, that sounded like a distraction to pull together.

**Comment by mykmelez** [comment]
It only took a few minutes, but automating it would be better!
