### ISSUE TITLE
Add UI to dashboard to specify receipt type.

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#494]
@potch is working on updating the dashboard UI.  With the addition of receipts, I'd like him to think about the UI for receipts.  @andymckay 's [tool](https://marketplace.firefox.com/developers/test/receipts/) features a dropdown with the receipt types of None, Valid, Expired, Invalid, Refunded, or None.  We may want to allow the dev to chose this on initial install _and_ subsequent updates.

**Comment by mykmelez** [comment]
@nickdesaulniers: do you plan to work on this in the near future? If so, let's assign this to you. Otherwise, let's move it out of the v4 milestone. Your pick!

**Comment by mykmelez** [comment]
@nickdesaulniers I'm going to move this back into the v4 milestone, as I think we need to do this in order to complete the feature!

@potch this is currently assigned to you, and I think @nickdesaulniers's thinking is that you would design the UX, then @nickdesaulniers would implement it.

@nickdesaulniers is that correct?

@potch are you available to do the design here?

**Comment by nickdesaulniers** [comment]
I was thinking @potch would implement it along with the new UI, but if we're looking to implement something before the new UI lands, then I'd be happy to implement it with some UI decisions made for me.

**Comment by potch** [comment]
Glad to work this into the new design, and happy to handle the UI stuff. Not sure what sauce is needed on the backend.

**Comment by nickdesaulniers** [comment]
@potch , I'd like to implement the feature by milestone 4 which is due by 6/11/13.  I'm ready to go on this.  If you are too, I'd recommend if you created a separate branch that we both work out of, then could merge into master.  Thoughts?

**Comment by nickdesaulniers** [comment]
The first step is to get listApps to include information on the installed receipt type, then have updateApp contain info on the newly selected receipt.  updateApp should probably be fired onchange of the receipt type UI element.

**Comment by potch** [comment]
@nickdesaulniers, sounds easy enough :) is there a division of labor you want to do here? I have some UI stuff I can land in the coming week that could include this. Is there a particular format to the receipt info that the addon-land code would like? (integer, string, etc)

**Comment by nickdesaulniers** [comment]
You handle rendering the receipt type and interaction, I'll handle the update.  So in [applist.renderSingle](https://github.com/mozilla/r2d2b2g/blob/9472033438bed47684d8584fe71db35dfe6f67ba/addon/data/content/js/applist.js#L48) the app variable should contain a "receiptType" field which is a string of either ["ok", "expired", "invalid", "refunded", "none"](https://github.com/mozilla/r2d2b2g/blob/9472033438bed47684d8584fe71db35dfe6f67ba/addon/data/content/js/main.js#L184).  For [updateApp](https://github.com/mozilla/r2d2b2g/blob/9472033438bed47684d8584fe71db35dfe6f67ba/addon/data/content/js/applist.js#L101), just add the selected receiptType with a value of one of those strings if the app's receipt type was updated and I'll handle making sure it gets updated properly in the app directory.

One thing to be careful of in the code: any app installed before my initial receipts support patch will **NOT** have a receiptType property.  You should make sure to handle this case, maybe by either rendering it as "none" or setting it to "none" then calling updateApp on it.

**Comment by nickdesaulniers** [comment]
Actually, I'd prefer the dashboard to send a new message, maybe "updateReceiptType", instead of reusing updateApp.  This will allow me to create a cleaner separation of concerns.

**Comment by potch** [comment]
@nickdesaulniers Great! I'll have a PR for you hopefully by EOD tomorrow.

**Comment by nickdesaulniers** [comment]
@potch , your grandma was right, you are a "nice boy"!  Just to make sure, for the update event you should be calling something like `window.postMessage({name: "updateReceiptType", id: id, receiptType: "ok"}, "*");`

**Comment by potch** [comment]
@nickdesaulniers, I'm able to add apps with various receipt types, but the `receiptType` field isn't present on the resultant app object. Is that field located elsewhere?

**Comment by nickdesaulniers** [comment]
@potch, so sendListApps fires like a hundred different times while doing anything with simulator.  See how many times renderSingle gets called while updating an app, and you'll see probably the last invocation have the field.  Definitely an issue, that the various update code paths keep calling sendListApps.

**Comment by potch** [comment]
the app objects always get the receipt, but never the receiptType. I have this code console.logged to heck and can't figure out what's going on. Can you take a look and make sure the receiptType is being stored?

**Comment by potch** [comment]
I have the UI working but for the fact I can't confirm that it works :)

**Comment by potch** [comment]
Found the issue- `receipt` was getting attached to the stored app object, but not `receiptType`. Adding that to my patch.
