### ISSUE TITLE
Push receipts to device

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#496]

**Comment by mykmelez** [comment]
@nickdesaulniers: do you plan to work on this in the near future? If so, let's assign this to you. Otherwise, let's move it out of the v4 milestone. Your pick!

**Comment by mykmelez** [comment]
@nickdesaulniers I'm going to move this back into the v4 milestone, as I think we need to do this in order to complete the feature!

**Comment by nickdesaulniers** [comment]
The other half of this bug is [here](https://bugzilla.mozilla.org/show_bug.cgi?id=881499).

**Comment by mykmelez** [comment]
Both halves of this have landed; fixed!
