### ISSUE TITLE
Add Style Editor actors to simulator

### ISSUE THREAD

**Issue by harthur** [mozilla/r2d2b2g#499]
On nightly, the Style Editor can use the remote debugging protocol, but the simulator doesn't have the actors required to communicate with it. The actors are located in `toolkit/devtools/styleeditor/dbg-styleeditor-actors.js`

@mykmelez says it would be easier to get these actors in the simulator than b2g.

**Comment by harthur** [comment]
Hold up one second for [bug 868321](https://bugzilla.mozilla.org/show_bug.cgi?id=868321) to land.

**Comment by harthur** [comment]
Okay, actors should be ready to uplift:

https://github.com/mozilla/mozilla-central/tree/master/toolkit/devtools/styleeditor

**Comment by ochameau** [comment]
It won't necessary be easier to uplift to simulator as we are still using m-c 18 and the recent refactoring of debugger server may not be easily cherry picked to this old branch :(
If that's easily cherry pickable, why not trying to uplift it to the master repo in order to ship the style editor in the phones released on the market?

@dcamp, @canuckistani:
Do we have a plan for on-device development? In its current state, phones won't have much developer features when being released with the 18 branch. Do we plan to communicate that if developers want to use devtools, they should flash their phones on a nightly, or something more recent than v1, like gecko 24 or 25 when the phone is finally sold on market?

**Comment by mykmelez** [comment]
I asked about uplifting remote debugging changes to the b2g18 branch in the DevTools meeting this morning, and @dcamp said the changes they've made on trunk recently are too significant to uplift piecemeal; and many more such changes are coming down the pike; so they're going to complete the work required to make all tools remoteable, which they plan to do in time for the Firefox 24 merge on Monday, June 24; and then they're going to pursue a bulk uplift of the new implementation to b2g18.

The one exception is the Style Editor actors, which landed before the recent major changes, and which it should be possible to uplift without too much trouble. Issue #499 is about landing them in the Simulator; although we should also pursue uplifting them to b2g18.

**Comment by ochameau** [comment]
@harthur I tried to make work the style editor actor on b2g18 by loading it from simular addon which is installed in b2g desktop (a.k.a. prosthesis). See PR #568. But this attempt failed. I tried to replace all recent Javascript feature usages, like `for of` and `=>`. But it doesn't seem to be enough. The dbg-styleeditor-actors.js file is correctly loaded without any exception, and the call to addTabActor pass without any exception either.
Do you have any idea what could be wrong here? Is style editor expected to work against shell.xul?

I took current aurora version of the file:
  http://mxr.mozilla.org/mozilla-aurora/source/toolkit/devtools/styleeditor/dbg-styleeditor-actors.js
which seems to contain bug 868321, you mentioned over in this thread.

**Comment by harthur** [comment]
If it's showing a loading indicator forever, then an error occured somewhere, unfortunately. The thing to do would be to add logging statements in various places.

**Comment by mykmelez** [comment]
Hrm, I thought this would be easier. At this point, it seems better to wait for a mass uplift of support for remote devtools to the b2g18 branch (although I'd still take a fix for this if it became available).

**Comment by mykmelez** [comment]
A fix became available, and we took it!
