### ISSUE TITLE
Orientation button doesn't work

### ISSUE THREAD

**Issue by Gioyik** [mozilla/r2d2b2g#500]
Hi,

I have been installed the latest version of the Simulator, and in Firefox 20.0 / Ubuntu 13.04. The orientation buttom of the simulator doesn't work. It doesn't change the orientation of the simulator, it's vertical all the time.

Regards

**Comment by rpl** [comment]
Currently the Orientation button doesn't rotate the screen if the app lock
the orientation (e.g. currently the homescreen lock the screen in portrait)

Could you try to run an app which unlock the screen? (e.g. run the gaia
browser app and click the orientation button)

Besides that we agree that the current button behavior is not
complete/clear and we're going to make it more explicit.

**Comment by mykmelez** [comment]
@Gioyik Can you confirm that the button works if you try it in the browser app?

**Comment by Gioyik** [comment]
@mykmelez The rotation works in the browser app. Now i tested in other webapps and it works good. Sorry about it, probably was something stucking my brain in that moment. Is not a bug. :)

**Comment by mykmelez** [comment]
> @mykmelez The rotation works in the browser app. Now i tested in other webapps and it works good. Sorry about it, probably was something stucking my brain in that moment. Is not a bug. :)

Thanks for the quick response, and not that this isn't your fault! The current behavior is confusing, not only for you, but also for other users. @ochameau fixed #482 to make it a bit better, and we have ideas for making it even better in #312.
