### ISSUE TITLE
Date and time display on home screen is totally weird

### ISSUE THREAD

**Issue by k5e** [mozilla/r2d2b2g#502]
The date and time display on the simulator v.3 is not as expected:
![fxos_simulator-1](https://f.cloud.github.com/assets/606885/465150/bd0ee07e-b626-11e2-9715-2b7e74465144.png).
It even spills over to the next page:
![fxos_simulator-2](https://f.cloud.github.com/assets/606885/465151/c398ee4e-b626-11e2-9618-47fc5b16ff11.png).

This is the case since v.1 of the simulator.

**Comment by ochameau** [comment]
@mykmelez, This issue has been fixed in gaia master via this bug:
  https://bugzilla.mozilla.org/show_bug.cgi?id=863318
I'm going to ask if this patch is upliftable.

**Comment by ochameau** [comment]
If that's not upliftable, we can provide a simplier patch as the most important lines are these three additions:
https://github.com/KevinGrandon/gaia/commit/4278903c96fd9692ee091cd244b3f24e510dd699#diff-9

**Comment by ochameau** [comment]
Actually, the patch I was refering to has already been uplifted on 1st of May on v1-train,
so that will be fixed on the next update of gaia submodule!

**Comment by mykmelez** [comment]
I updated Gaia to the 2013-05-08 tip in 7a229b0d80bd26d752ad418997d8792fe45ff6b7, fixing this issue. The fix will show up in the next preview build.
