### ISSUE TITLE
Lockscreen isn't disabled

### ISSUE THREAD

**Issue by ochameau** [mozilla/r2d2b2g#504]
On simulator master the lockscreen isn't correctly disabled.
It is a regression in gaia v1-train, as it doesn't fail with gaia master.
For some reason, the lockscreen is displayed whereas `lockscreen.enabled` settings is reported to be false here:
https://github.com/mozilla/r2d2b2g/blob/master/prosthesis/content/lockscreen.js#L6

**Comment by ochameau** [comment]
It was something wrong in v1-train. We were missing the uplift from https://bugzilla.mozilla.org/show_bug.cgi?id=836056
I just uplifted it, so that should be fixed when we update our gaia submodule.

**Comment by mykmelez** [comment]
I updated Gaia to the 2013-05-08 tip in 7a229b0d80bd26d752ad418997d8792fe45ff6b7, fixing this issue. The fix will show up in the next preview build.
