### ISSUE TITLE
Wrong this reference

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#505]
![screen shot 2013-05-06 at 4 48 53 pm](https://f.cloud.github.com/assets/1823839/468894/9d84b1e4-b6a7-11e2-930e-c87f19d3c836.png)

Noticed this in my log.  Notice how [this](https://github.com/mozilla/r2d2b2g/blob/117c6750b6b5100c82e99c1cb4db8e04102848d6/prosthesis/content/dbg-simulator-actors.js#L309) in this context will refer to req, not SimulatorActor.prototype.  A simple `let that = this;` pattern would do the trick.  Good beginner bug!

**Comment by raudabaugh** [comment]
this reference is no longer there, instead handled by `let debug = this.debug.bind(this);`

I think it's safe to close this issue

**Comment by nickdesaulniers** [comment]
@raudabaugh , you're [correct](https://github.com/mozilla/r2d2b2g/blob/96a057a1f6f9a22d30859839fb68f913081b8bbb/prosthesis/content/dbg-simulator-actors.js#L245)!  Nice catch!  It still might be nice to move the variable assignment to the top and use that instead of repeatedly accessing it through this, but NBD.
