### ISSUE TITLE
appOrigin is not defined.

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#506]
![screen shot 2013-05-06 at 5 05 33 pm](https://f.cloud.github.com/assets/1823839/468961/e9c6d242-b6a9-11e2-8187-00fd5e9c4ba9.png) from installing packaged apps in `prosthesis/content/window-manager.js`

**Comment by nickdesaulniers** [comment]
Haven't seen this in a while.

**Comment by mykmelez** [comment]
Ironically I just found a source for this today, and I fixed it in #662.
