### ISSUE TITLE
ocsp lookups appear in web console

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#508]
![screen shot 2013-05-07 at 10 16 58 am](https://f.cloud.github.com/assets/1823839/472717/128d73bc-b73a-11e2-83c6-b73d7c5d976c.png)

Seems like when there is HTTPS traffic, we log the OCSP request (has something to do with cert revocation lists IIRC) which I don't think is normal.

**Comment by mykmelez** [comment]
Is this the console for the Dashboard or a remote console connected to the Simulator? And if the latter, is it connected to shell.xul or the Main Process?

**Comment by nickdesaulniers** [comment]
remote console to main process.  Unable to verify now...
