### ISSUE TITLE
app manifest validation fails to complain about bogus value for appcache_path

### ISSUE THREAD

**Issue by wfwalker** [mozilla/r2d2b2g#514]
It appears the otherwise excellent manifest validation in the simulator is not checking the validity of appcache_path.

Steps to Reproduce:

git clone git://github.com/wfwalker/opensun.git
add opensun/www/online.manifest as app to Simulator
should validate successfully
change appcache_path to something bogus
expected behavior: validation error
actual behavior: validation success

**Comment by mykmelez** [comment]
Note related issue #306: when the appcache path is invalid, not only does the validator not warn you, but installation fails silently.

**Comment by ochameau** [comment]
Note that appcache isn't supported for packaged app. In PR #523, I'm displaying a warning when we try to use appcache in packaged app.

Wouldn't it be interesting to introduce two modes for "Add directory" where we could select either hosted or packaged app type? The packaged app type would be the existing behavior. The hosted would be something similar to gaia DEBUG=1 mode, where we would automagically fire an httpd instance binded to the folder you gave. It sounds like some subtential amount of work, but would ease various painfull environnment step you have to jump before having a working hosted app. Like having correct content-types...

**Comment by mykmelez** [comment]
> Wouldn't it be interesting to introduce two modes for "Add directory" where we could select either hosted or packaged app type? The packaged app type would be the existing behavior. The hosted would be something similar to gaia DEBUG=1 mode, where we would automagically fire an httpd instance binded to the folder you gave. It sounds like some subtential amount of work, but would ease various painfull environnment step you have to jump before having a working hosted app. Like having correct content-types...

I like that idea a lot! I would just be careful to distinguish between the "Gaia DEBUG=1" use case and the "third-party developer of hosted app" use case.

"Gaia DEBUG=1" is a mode in which a packaged app is served from a web server as if it was a hosted app, which seems pretty unique to Gaia development and isn't particularly useful in the Simulator, given that the Simulator knows how to package, install, and update a packaged app and can do so just as quickly as Gaia DEBUG=1 can reload a hosted app.

But it would be potentially very useful for the third-party developer of an app that is actually intended to be hosted to be able to point to a local directory containing its files and have the Simulator spin up a web server that hosts it (taking care of registering content types, rerouting domain names, etc. as necessary), so the developer doesn't have to go to the trouble of spinning up that server!

cc: @potch so he's aware of this use case. Note also @tofumatt's suggestion that it be possible for a hosted app developer to identify a build step that the Simulator will perform automatically when the developer refreshes their app. Providing capabilities like these would potentially make hosted app development simple and delightful!

**Comment by mykmelez** [comment]
Fixed by #523.
