### ISSUE TITLE
Holding the home button should launch the task manager

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#52]
In the Simulator, holding the home button should launch the task manager as it does on the actual device.

**Comment by syssgx** [comment]
True, same as with the keyboard "Home".

**Comment by mykmelez** [comment]
Holding down the keyboard's Home key should already work!

And holding down the Home button should work now that I've merged [pull request #82](https://github.com/mozilla/r2d2b2g/pull/82).
