### ISSUE TITLE
reassure AMO reviewers that setting port value is safe

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#524]
Code like the following made @kmaglione nervous in his AMO review of v3:

```
      contentScript: "window.addEventListener('load', function() { document.getElementById('port').value = '"+port+"'; }, true);"
```

@kmaglione suggests that we "at least escape the port with something like JSON.stringify(port)". There's no actual vulnerability, since we generate the port value and know that it's an integer. But we should do something to reassure future AMO reviewers of that fact.

**Comment by nickdesaulniers** [comment]
we should use [parseInt](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/parseInt) with an explicit radix of 10 and pass that to [isNaN](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/isNaN).

**Comment by kmaglione** [comment]
If you want to use parseInt, I'd prefer:

```
       contentScript: "window.addEventListener('load', function() { document.getElementById('port').value = '"+parseInt(port)+"'; }, true);"
```
