### ISSUE TITLE
under windows 7 i have a white screen when i open the phone book (Contact)

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#546]
on FF 22 beta 32bit
![rubricabug](https://f.cloud.github.com/assets/4499372/548243/e1758872-c2de-11e2-8140-7747d649b24b.png)
 I haven't this problem under ubuntu 12.04 32 bit FF 22

**Comment by stefanostatuti** [comment]
confirmed in 4.3 preview

**Comment by mykmelez** [comment]
This is issue #400.
