### ISSUE TITLE
Icon doesn't appear when registering a local app manifest

### ISSUE THREAD

**Issue by ochameau** [mozilla/r2d2b2g#548]
I don't know if I miss something, but with very simple testcase, the icon doesn't show up in dashboard when I register a local manifest:

```
/myapp/ico.png
/myapp/manifest.webapp:
{"name": "foo", "icons": {"128": "ico.png"}}
- or - 
{"name": "foo", "icons": {"128": "/ico.png"}}
```

**Comment by mykmelez** [comment]
I'm having trouble reproducing this. I created a directory /Users/myk/Mozilla/app-icon/ with the following files:

```
06-10 12:00 > ll /Users/myk/Mozilla/app-icon
total 24
-rw-r--r--  1 myk  myk  4504 Jun 10 12:00 icon.png
-rw-r--r--  1 myk  myk    65 Jun 10 12:01 manifest.webapp
```

manifest.webapp is:

```
{
  "name": "App With Icon",
  "icons": { "128": "/icon.png" }
}
```

And the icon file is this one:

https://github.com/mykmelez/mykzilla-org/blob/master/app/img/icon-128.png

When I add the app to the Dashboard, I see its icon in the Dashboard (and in the Simulator):

![screen shot 2013-06-10 at 12 04 43](https://f.cloud.github.com/assets/305455/633479/aa5e26ba-d200-11e2-92ff-ae4010e6a745.png)

**Comment by mykmelez** [comment]
@ochameau can you still reproduce this?

**Comment by ochameau** [comment]
Yes, I do, it appears to be a windows specific issue...
