### ISSUE TITLE
NotSupportedError - touch-events.js

### ISSUE THREAD

**Issue by StrawMan** [mozilla/r2d2b2g#560]
**Build:**  _r2d2b2g-4.0pre3-windows.xpi / 24-May-2013 00:08_
**Firefox Version: 21.0**

``` javascript
[10:07:22.643] NotSupportedError: Operation is not supported @ chrome://desktop-helper.js/content/touch-events.js:167
```

The above error is being thrown everywhere. From the home screen and any given application. Unfortunately, it's making this build well nigh unusable.

**Comment by mykmelez** [comment]
cc: @ochameau 

@StrawMan Does it prevent you from interacting with the Simulator, or does it just clutter up the console so much that you can't see your own console messages?

**Comment by StrawMan** [comment]
Unfortunately, the error is affecting custom events in the application that I'm authoring. To the extent that they refuse to fire at all, or fire unpredictably. 
In one case the simulator orientation change event (button at the foot of the simulator) was called when I was selecting something completely unrelated and nowhere physically near it.

**Comment by ochameau** [comment]
@myk, are we replacing gaia profile when updating the addon?
The touch event component requires the removal of this preference:
https://github.com/mozilla/r2d2b2g/commit/099563cc3e8c0bf4cfaac6a09158cf1b877ef004#diff-1

**Comment by mykmelez** [comment]
Yes, we completely replace the Gaia profile when updating the addon, so I don't think that's the problem.

**Comment by mykmelez** [comment]
@StrawMan do you still see this problem with the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi))?

**Comment by StrawMan** [comment]
While the above error no longer appears in my console, button behavior remains erratic. Sometimes a particular button works, then immediately fails.
You can see this (at least I'm presently seeing it) if you open up the _Firefox Marketplace_ application and scroll down any given category, then attempt to use the "More" button.

In another case, the _HERE Maps_ application map dragging fails to function. Silently though, without any particular console error.

Perhaps I should file separate bugs for these? 
They do all indeed appear to be related. 

Occasionally (unpredictably), the following error is now thrown instead:

``` javascript
[10:22:07.011] TypeError: evt.target.ownerDocument is null @ chrome://desktop-helper.js/content/touch-events.js:53
```

**Build:**  _r2d2b2g-4.0pre5-windows.xpi / 7-June-2013 11:28_
**Firefox Version: 21.0 / Windows Vista**

**Comment by StrawMan** [comment]
Back to the original error in _pre6_.

Clicking on the home screen, other applications etc. All over the place.
Button events similarly erratic.
Map dragging does, on the other hand, work properly once again.

**Build:**  _r2d2b2g-4.0pre6-windows.xpi / 12-Jun-2013 16:44_
**Firefox Version: 21.0 / Windows Vista**

``` javascript
[15:04:04.660] NotSupportedError: Operation is not supported @ chrome://desktop-helper.js/content/touch-events.js:167
```

**Comment by StrawMan** [comment]
A full, clean re-installation of the _pre-6_ build appears to have cleared up the problem.
Button events are working as expected and no errors are being thrown.

**Comment by mykmelez** [comment]
@StrawMan Excellent, I'm glad to hear it!

Note that there is a known issue with touch event simulation, #603, which sounds very much like the issue you described. It manifests when you scroll a scrollable element and then click to simulate a touch event. A fix for that will land in the next preview build, so if you experience the problem again, try downloading that when it becomes available later this week!
