### ISSUE TITLE
Privileged apps does not work

### ISSUE THREAD

**Issue by laukstein** [mozilla/r2d2b2g#561]
Issue reported also in https://github.com/robnyman/Firefox-OS-Boilerplate-App/issues/14

Firefox OS Simulator 3.0.1 returns

> **File not found**
> Firefox can't find the file at app://9ae0db53-4940-46e4-a500-f20cb7aba03b/app/."
> 
> Content JS ERROR at app://homescreen.gaiamobile.org/js/page.js:161 in icon_fetchImageData: Got an exception when trying to load icon "app://9ae0db53-4940-46e4-a500-f20cb7aba03b/app/images/logo64.png", falling back to cached icon. Exception is: [Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: app://homescreen.gaiamobile.org/js/page.js :: icon_fetchImageData :: line 158"  data: no]

Firefox OS Simulator Dashboard errors:

> **Packaged App**
> Validation Result: WARNINGS (0 errors and 1 warnings)
> Warnings: Denied permission 'bluetooth' for type 'privileged'.
> 
> **Hosted App**
> Validation Result: INVALID (1 errors and 0 warnings)
> Errors: Hosted App can't be type 'privileged'.

Pushing on device packaged app, shows alert "App installed", but actually it did not install it and app icon does not shows up on screen. And on pushing hosted app, nothing happens at all.

The **manifest.appcache** additions 

```
"type": "privileged",
"permissions": {
    "bluetooth": {}
}
```

I tried also to add also CSP header for **index.php**, but it did not help ether

```
header("Content-Security-Policy: default-src *; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'");
```

Any solution or reported bug for it?

**Comment by mykmelez** [comment]
Based on the discussion in robnyman/Firefox-OS-Boilerplate-App#14, it sounds like the issue is that the app in question wants the bluetooth privilege, which is restricted to certified apps. So this is not an issue in the Simulator, it's an unfortunate limitation of the current design.

**Comment by laukstein** [comment]
Why would not Firefox OS allow privileged app API to everyone? User allways can decide to allow the permissions or not.
