### ISSUE TITLE
HERE Maps NOT working (display the index of app://m.here.com)

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#564]
hi,
i tried to launch HEREMaps but i display the index of app://m.here.com.

W7 Ultimate 32Bit simulator 4.3
![maps](https://f.cloud.github.com/assets/4499372/564313/7745b5ac-c555-11e2-9cab-44e65c0f79a6.png)

EDIT:
i tried to download the app from the store (https://marketplace.firefox.com/downloads/file/201674/here-maps-packaged-1.8.58.zip) & after install on simulator the app work fine.
I think is only a problem in the app version. In Simulator the date of some files are 16/01/2013 but from store i have 03/04/2013.

**Comment by mykmelez** [comment]
This is #386 and is caused by a difference between the Simulator and devices with regard to third-party app installation.
