### ISSUE TITLE
Simulator actors don't initialize until the dashboard sends an app

### ISSUE THREAD

**Issue by bkase** [mozilla/r2d2b2g#571]
Simulator actors in `prosthesis/content/dbg-simulator-actors.js` are not initialized until the dashboard runs an app.

This means that the shell in prosthesis is unable to communicate via observers to the simulator actors until an app is run from the dashboard. The simulator actors should be initialized prior to any observer communication.

**Comment by bkase** [comment]
We could just send a wakeup message to the simulator actors when someone toggles the simulator to running. 
Is this too hacky?

**Comment by mykmelez** [comment]
It isn't too hacky, although we should still also figure out the underlying problem.

**Comment by nickdesaulniers** [comment]
fixed in #653
