### ISSUE TITLE
SecurityError while using Devicestorage.enumerate()

### ISSUE THREAD

**Issue by nootanghimire** [mozilla/r2d2b2g#575]
I Tried to use devicestorage API on an app. When i run the app on simulator, SecurityError occurs

**Comment by mykmelez** [comment]
Hi @nootanghimire, sorry to hear about the problem! I would need a bit more info to diagnose it, however. Does the app request a device-storage permission in its manifest? And what is the exact text of the SecurityError message?

See [App Permissions](https://developer.mozilla.org/en-US/docs/Web/Apps/App_permissions) for the permissions the app can request, and see [Apps Manifest: Permissions](https://developer.mozilla.org/en-US/docs/Web/Apps/Manifest?redirectlocale=en-US&redirectslug=Apps%2FManifest#permissions) for instructions for requesting them.

**Comment by nootanghimire** [comment]
Here is  a part of my manifest file:

```
"permissions": {
     "desktop-notification": {
       "description" : "To show notifications"
    },
    "geolocation": {
        "description" : "Marking out user location"
    },
    "device-storage:sdcard" : {
        "description" : "To get epub files"
    }
    }
```

And the code that is outputting the error is

```
var storage = navigator.getDeviceStorage("sdcard");

        cursor = storage.enumerate();

        cursor.onerror = function() {
            console.error("Error in DeviceStorage.enumerate()", cursor.error.name);  //< this shows SecurityError in console
       };
```

I tried to find details by replacing 'name' by 'message' or 'status', in that case, nothing was consoled.

**Comment by mykmelez** [comment]
Thanks for the additional info! Can you also provide the exact text of the error message in the console? Cut/paste should work and would be ideal.

**Comment by mykmelez** [comment]
Closing due to lack of needed info; but please reopen if you can provide it!
