### ISSUE TITLE
Gaia > Settings > Language requires multiple clicks

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#576]
Since we landed support for simulated touch events (099563cc3e8c0bf4cfaac6a09158cf1b877ef004), it takes two or three clicks on the Language item in Gaia's Settings app to make the Language section appear.

Steps to Reproduce:
1. start the Settings app;
2. scroll down to the Language item;
3. click the Language item two or three times.

Expected Results: the Language section appears after the initial click.
Actual Results: the Language section doesn't appear until the second/third click.

When I start the Settings app, I see this error in the console:

> Timestamp: 2013/05/30 08:31:14
> Error: ReferenceError: MouseEventShim is not defined
> Source File: app://settings.gaiamobile.org/js/settings.js
> Line: 893

But I also see that after I revert the touch events simulation, so it seems unrelated.

The command-line console shows the same set of messages for clicks that fail as those that succeed:

> info: r2d2b2g: desktop-helper (TouchEventHandler): mousedown:
> info: r2d2b2g: desktop-helper (TouchEventHandler): mouseup: 1
> info: r2d2b2g: desktop-helper (TouchEventHandler): click
> desktop-helper (TouchEventHandler): click: fire
> info: r2d2b2g: desktop-helper (TouchEventHandler): mousedown: fire
> info: r2d2b2g: desktop-helper (TouchEventHandler): mousemove: fire
> info: r2d2b2g: desktop-helper (TouchEventHandler): mouseup: fire

In and of itself, this is not a significant issue, but it could be the tip of the iceberg, i.e. a minor manifestation of a larger problem that causes other symptoms that I haven't noticed yet. Perhaps #560 is related.

**Comment by mykmelez** [comment]
> In and of itself, this is not a significant issue, but it could be the tip of the iceberg, i.e. a minor manifestation of a larger problem that causes other symptoms that I haven't noticed yet.

Indeed: the more I navigate around the Settings app, the more I notice various clicks being swallowed. I just saw this while clicking the Back button to return from a section to the main list of settings.

**Comment by mykmelez** [comment]
Further usage reveals that clicks are getting swallowed all over the place, not just in the Settings app.

**Comment by ochameau** [comment]
See #583 for possible fix.

**Comment by mykmelez** [comment]
#583 appears to have fixed this.
