### ISSUE TITLE
geolocation watcher tries to update simulator that isn't running

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#579]
After installing 4.0pre4, I'm noticing a bunch of these two messages showing up in pairs:

> info: r2d2b2g: Firefox sending geolocation response
> 
> Timestamp: 2013/05/30 16:27:18
> Error: this._remote is null
> Source File: resource://gre/modules/XPIProvider.jsm -> file:///Users/myk/Library/Application%20Support/Firefox/Profiles/j50wskkw.Default%20User/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/remote-simulator-client.js
> Line: 261

It looks like the geolocation watcher is trying to update the simulator with a new location even though the simulator isn't running.

**Comment by nickdesaulniers** [comment]
If it's responding, doesn't that mean it received a request over the remote?

**Comment by mykmelez** [comment]
Yes, I think this happens when the user starts the Simulator, tells the Simulator to use their current coordinates for geolocation (triggering an unsolicited notification to Firefox that causes it to start watching the position), and then shuts down the Simulator.

At that point, Firefox should stop watching the position, but for some reason it doesn't do so, and when a position change occurs, it tries to send a request to the Simulator with the new coordinates, but the Simulator isn't running, so _this._remote_ is undefined, and the attempt fails, throwing an exception.

Unfortunately, I don't seem to be able to reproduce the problem anymore. But I can still prevent it from happening by checking _this._remote_ in the _watchPosition_ callback and logging a warning when it isn't defined. I'll request a pull with that change.

**Comment by mykmelez** [comment]
Actually, upon closer inspection, I do see a race that could theoretically cause this problem, although it seems unlikely.
