### ISSUE TITLE
Simulator addon fails to load on browser startup, menu item missing on Ubuntu 13.04/Nightly

### ISSUE THREAD

**Issue by flaki** [mozilla/r2d2b2g#580]
Hi!

I am installing the latest preview build (4.0pre3) on the latest Firefox Nightly (24.0a1, 2013-05-26 - Mozilla Firefox for Ubuntu Canonical - 1.0, AFAIK x64) on Ubuntu 13.04 x64.

The addon installs all right and runs well - however after browser restart the addon is not registering. The Simulator menu item is missing from the Web developer tools menu, and the `firefoxos` command line item is not recognized in the Developer command line.

To fix the addon, one must disable it first, restart the browser and re-enable the addon, after which it is correctly shown and running again.

**Comment by bkase** [comment]
Hi @flaki 

Can you confirm that this is still happening for you on the latest Nightly? I tried to reproduce this with build 4.0pre3 and 4.0pre4, and it's not happening (on an Ubuntu 13.04 x64 VM).

**Comment by mykmelez** [comment]
I can't reproduce it either with those preview builds and the latest Nightly, but I also can't reproduce with the Nightly from 05-26. Even after reinstalling Ubuntu 13.04 64-bit from scratch (in case it's a question of the addon depending on some non-default system library that I had previously installed).

**Comment by mykmelez** [comment]
I released a new preview build late last week. @flaki can you test with the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi))?

**Comment by flaki** [comment]
@mykmelez as far as I can tell, the issue seems to be resolved now - I could not reproduce it with the latest preview build on today's trunk release of Firefox Nightly (Ubuntu, x64)

**Comment by mykmelez** [comment]
Ah, great, thanks @flaki!
