### ISSUE TITLE
manifest file is having a bug

### ISSUE THREAD

**Issue by shuvam07** [mozilla/r2d2b2g#587]
wen i am ceating a app icon say of pixel value greater or less than 128px the app icon is not showm in the simulator..

**Comment by mykmelez** [comment]
I just tried adding a packaged app with a single 256x256px icon, and I see the icon both on the Dashboard and in the Simulator itself.

Is the app hosted or packaged, and can you show us its manifest? I would also be interested to see the source code of the app itself, if that is available. In particular, it would be useful to see the location and content of the icon file.

**Comment by mykmelez** [comment]
Closing due to lack of needed info; but please reopen if you can provide it!
