### ISSUE TITLE
notify user if "push to device" fails

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#593]
If a "push to device" fails for any reason, the Dashboard should tell the user about it, so they know that it failed (and ideally also why it failed). See issue #538 for examples of failures that we don't tell the user about.

**Comment by nickdesaulniers** [comment]
It looks like the webapps actor [always responds with an obj](http://mxr.mozilla.org/mozilla-central/source/toolkit/devtools/server/actors/webapps.js#294) so we can look for that.

**Comment by nickdesaulniers** [comment]
myk: other thoughts to file away for future enhancements: remind the user that they might have to confirm the prompt (f.e. we could show a picture of it and say something like "Make sure you confirm this prompt if it appears on your phone!")

**Comment by nickdesaulniers** [comment]
Filed [this](https://bugzilla.mozilla.org/show_bug.cgi?id=883931) for the DebuggerClient.
