### ISSUE TITLE
purge IndexedDB (or LocalStorage?) when user presses Shift-Cmd/Ctrl-R

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#595]
Last Friday I demoed @rpl's Shift-Cmd/Ctrl-R feature to purge the AppCache while refreshing an app, and @cvan (or was it @mattbasta?) suggested we also purge another cache/database that I think was IndexedDB (although it could have been LocalStorage).

@cvan, @mattbasta, can y'all confirm which data you want to have purged during such a refresh?

**Comment by cvan** [comment]
``` javascript

sessionStorage.clear();
localStorage.clear();
```

would be good for me.

``` javascript
(function clearCookies() { var s=(document.cookie+';').replace(/([^=]*)=[^;]*; */g,"$1=; expires=Thu, 01 Jan 1970 00:00:00 GMT;\n").split('\n'); for (var i in s) { document.cookie = s[i]; } })();
```

would also be nice.

**Comment by mykmelez** [comment]
cc: @rpl

**Comment by rpl** [comment]
@mykmelez I'm on it
