### ISSUE TITLE
Capitalize receipt types

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#597]
I noticed that the receipt types for each app are lowercase, while the receipt types for a new install are Capitalized.  Also looks like they're a different font?

**Comment by mykmelez** [comment]
The receipt types should be consistent, at least until we fix #611. However, we should still capitalize the receipt types in the menu for existing apps, if that's the right way to present them. (And the "ok" type should be called "valid").

cc: @potch for his thoughts on whether these types should be initial-letter capitalized or all lower-case.

**Comment by potch** [comment]
I'm going to clean up the appearance and such on the receipt selector,  as well as fix #611.

**Comment by nickdesaulniers** [comment]
Fixed in #618
