### ISSUE TITLE
Red and Yellow outlines for app errors/warnings gone

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#598]
I just downloaded and installed 4.0pre5 and the two apps I had that had errors no longer were surrounded in red.  Is this part of the UI change?

**Comment by mykmelez** [comment]
Yes, this is an intentional change to make the UI less intrusive, since developers don't necessarily want to fix errors and warnings immediately (or ever), and the strong colorful outlines were overly insistent that attention be paid to them.

cc: @potch
