### ISSUE TITLE
Data provided to an operation does not meet requirements.

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#599]
Timestamp: 11/06/2013 22:49:01
Error: DataError: Data provided to an operation does not meet requirements.
Source File: app://costcontrol.gaiamobile.org/shared/js/async_storage.js
Line: 75

i can reproduce this bug:

start the simulator
clear ALL logs
open the top menu & receive the error

**Comment by mykmelez** [comment]
Does this prevent you from using the Simulator to develop apps?

**Comment by stefanostatuti** [comment]
no.

**Comment by mykmelez** [comment]
Ok, in that case I'll close it! But please reopen if you discover that it does cause a problem!
