### ISSUE TITLE
Add a way to change orientation.

### ISSUE THREAD

**Issue by JoeStagner** [mozilla/r2d2b2g#6]
From Portrait to Landscape

**Comment by hkgrild** [comment]
I agres with that suggestion, for dev's it would be awesome

**Comment by leandroruel** [comment]
i agree too...i want it too

**Comment by nhoizey** [comment]
It's a must have, of course.

**Comment by abogdanovich** [comment]
+1 - we really need this option. Thanks guys!

**Comment by rpl** [comment]
fixed by #305
(it will be released in the next simulator preview build)
