### ISSUE TITLE
NS_ERROR_FAILURE: Component returned failure code: 0x80004005

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#604]
Timestamp: 11/06/2013 23:41:51
Error: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMMozMobileMessageManager.getSegmentInfoForText]
Source File: app://sms.gaiamobile.org/js/thread_ui.js
Line: 503

open the simulator:
open messages & clean ALL the logs
now click "write button" & receive the message in log console.

**Comment by mykmelez** [comment]
Hi @stefanostatuti. As I mentioned in another issue, individual messages in the Error Console, like this one, aren't necessarily a cause for concern. So we don't typically track each one. But we do want default apps that expose an activity to work, and the Messages app exposes two activities. Did this error appear to prevent you from using the Messages app?

**Comment by mykmelez** [comment]
Closing due to lack of needed info. But please reopen if you can provide it!
