### ISSUE TITLE
Can't play an mp3 stream on the simulator

### ISSUE THREAD

**Issue by ChoiZ** [mozilla/r2d2b2g#606]
When I want to play an mp3 stream from an icecast server in « <audio> » tag nothing happens.

Note this code and stream doesn't works in simulator but it's works on my geeksphone peak.

**Comment by mykmelez** [comment]
@ChoiZ, Unfortunately, the Simulator doesn't support MP3 decoding, as we note in the [documentation](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Audio.2Fvideo_codecs), because it depends on a hardware codec.
