### ISSUE TITLE
manager always has horizontal scrollbar

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#61]
No matter how wide I make the browser window, the manager always has a horizontal scrollbar. It should fit into the available space provided the browser window is a reasonable size.

**Comment by hkgrild** [comment]
You should also see that, we can't make it smaller...
As it is supposed to be a "SmartPhone Emulator", i would like to make that window Smaller thant an smartphone screen, and bigger than my 28" screen .... 
Why can't i do that ? 
Oh yeah, it's a SMARTPHONE EMULATOR!!!!!!!!!!!!!!

Set a maxwindow value or something so this kind of stupid kind of comment doesn't shows up anymore, thanks
