### ISSUE TITLE
brief delay between Dashboard page load and app list display

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#610]
There's now a brief delay between the apparent completion of page load for the Dashboard and the display of the list of apps. The delay is only a fraction of a second, but it's significant enough to be noticeable and at least long enough for a developer's heart to skip a beat while they wonder what happened to all their apps. We shouldn't scare developers like this!

I suspect this is a regression from recent changes to the page. Perhaps we now delay the initial build of the list of apps? cc: @potch @nickdesaulniers

**Comment by nickdesaulniers** [comment]
Fixed in #618
