### ISSUE TITLE
remove Receipt Type selector for app being added to Dashboard

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#611]
We initially implemented the Receipt Type selector for a new app being added to the Dashboard because there wasn't going to be any other way to test receipts until we implemented a Receipt Type selector for an existing app on the Dashboard, and the latter implementation was blocked by Dashboard redesign work that was in progress.

That Dashboard redesign work has been completed, and a Receipt Type selector has been added to existing app entries on the Dashboard. So we no longer need the new app selector.

And it isn't useful enough to keep it around anyway, since it's just as easy to select a receipt type after adding the app. Also, most developers most of the time won't be testing receipts, so it's better for them to be able to lazily choose a receipt type when they actually start testing them than be prompted to do so when they initially add the app.

So we should remove the Receipt Type selector for new apps.

cc: @potch @nickdesaulniers

**Comment by potch** [comment]
Agreed- I'll remove it!

**Comment by nickdesaulniers** [comment]
fixed in #618
