### ISSUE TITLE
no feedback on status of Receipt Type selection

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#613]
When I select a receipt type from the Receipt Type selector for an existing app, nothing appears to happen. This is disconcerting, even if the selection is actually working as expected, because there's no way to know if it really did without pushing the app to the Simulator and seeing if it behaves the way you would expect it to behave with the given receipt.

A Dashboard app entry should provide information about the status of a Receipt Type selection, i.e. inform the user via some kind of status indication that a selection is being processed and then that it has been completed successfully (or failed for some reason).

**Comment by mykmelez** [comment]
cc: @potch @nickdesaulniers

**Comment by nickdesaulniers** [comment]
There is no feedback in the dashboard when a user clicks Update, either.  The notification appears on the simulator after the select element is changed.  What kind of feedback did you have in mind?

**Comment by mykmelez** [comment]
> There is no feedback in the dashboard when a user clicks Update, either.

Yes, and that's also a problem, although it's less significant for packaged apps, whose resources are all local (so there's no chance of network latency or unavailability, although archiving large apps can still take noticeable amounts of time).

> What kind of feedback did you have in mind?

I think we should display a throbber next to the field while the new receipt is being downloaded.

**Comment by mykmelez** [comment]
I have a fix for which I'll request a pull shortly.
