### ISSUE TITLE
Open Location link on the dashboard does not work.

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#614]
Whenever a new instance of an application is created and loaded into the simulator dashboard,the Open Location option(just below the name of the application) does not seem to work.It behaves as a plain text(dead link).

**Comment by mykmelez** [comment]
It throws the following error:

```
Timestamp: 2013/06/13 15:03:40
Error: TypeError: $(...)[0] is undefined
Source File: resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/js/main.js
Line: 23
```

@potch, @nickdesaulniers: a regression from the recent Dashboard changes?

**Comment by nickdesaulniers** [comment]
Verified in 4.0pre5

**Comment by nickdesaulniers** [comment]
The onclick is handled for every [anchor tag whose href attribute starts with](http://api.jquery.com/attribute-starts-with-selector/) '#'.

$(element).attr('attribute_name') returns a [string](http://api.jquery.com/attr/#attr-attributeName) so then accessing the first element would be '#'.

My guess is that the href's were being used to store an id selector in the form '#my_element_id' and they no longer are.  The href from then being selected on, but if it's an id, then there should only be one element, therefor trying to access it like an array should not work.  Did this code ever work?

**Comment by nickdesaulniers** [comment]
[cc](https://github.com/mozilla/r2d2b2g/blame/master/addon/data/content/js/main.js#L23) @digitarald

**Comment by nickdesaulniers** [comment]
It certainly works in 3.0.1.

**Comment by nickdesaulniers** [comment]
but the error is still present!

**Comment by nickdesaulniers** [comment]
Error also occurs (in 3.0.1) when clicking remove.

**Comment by nickdesaulniers** [comment]
I'll run a bisect tomorrow

**Comment by potch** [comment]
It was a regression from landing of ui-revamp. My fault.
