### ISSUE TITLE
Manifest.webapp is not refreshing

### ISSUE THREAD

**Issue by breck7** [mozilla/r2d2b2g#617]
Here's my workflow:
- Open simulator
- Install app from url to the manifest.webapp file
- App installs great in simulator
- Update manifest.webapp
- Click "Update" in Dashboard

Expected: new manifest file is reflected.
Actual: cached(outdated) manifest file is used.

If I open a new tab in FF and redownload the manifest file, then refresh dashboard and click "Update", I get the new manifest file.

Perhaps this is already fixed, and it's something wrong with my setup.

**Comment by mykmelez** [comment]
Is there a particular field or fields that you're changing? Any chance your manifest file is publicly available?

**Comment by breck7** [comment]
I was changing the App title field and the icons field.

**Comment by breck7** [comment]
Manifest file is here: http://firefly.nudgepad.com/manifest.webapp

**Comment by mykmelez** [comment]
Hmm, I see this too on the latest dev version of the Simulator when changing the `name` field of a hosted app (http://mykzilla.org/app/manifest.webapp). And I confirm the workaround of downloading the manifest via a separate tab. Which suggests that this is a cache issue: updating the app uses a local cached copy of the manifest file instead of a fresh copy downloaded from its server.

**Comment by breck7** [comment]
Yes, that was my guess as well. It seems like hitting update should always download the latest manfiest.webapp file

**Comment by mykmelez** [comment]
> Yes, that was my guess as well. It seems like hitting update should always download the latest manfiest.webapp file

I agree!

**Comment by breck7** [comment]
@mykmelez Much better code than my fiddling with the url.

Just updated. Using the new github interface so not quite sure if I submitted that updated request correctly.

**Comment by mykmelez** [comment]
I'm on the new GitHub interface now too, and it looks like you submitted it correctly, so I have merged it along with https://github.com/mozilla/r2d2b2g/commit/b7027dce1d13a47041bffe99c6273e82b9b70fa8 which adds you to the list of contributors. Thanks for the issue and the fix!
