### ISSUE TITLE
click on virtual keyboard creates duplicate character

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#629]
Step to reproduce:
open the telephone app & try to click on a number. the push generate all the numbers twise.if you try to delete ONLY the last number have the same problem (delete 2 number)

Tested with W7 & ubuntu and i have the same problem.

**Comment by mykmelez** [comment]
I see this too on Mac OS X, and I see it in the browser app as well. The workaround is to use your keyboard to type, as key events don't result in duplicate characters.

@ochameau perhaps this is more fallout from touch event simulation?

**Comment by ochameau** [comment]
Yes, it has been fixed by https://github.com/mozilla/r2d2b2g/commit/83983d38e85e5064009586ef1c3445465d590c32
