### ISSUE TITLE
reduce size of Remove button icon

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#633]
The Remove button icon is larger than the icon on the Push button (and the icons being added to the Refresh née Update button and upcoming Connect button), which makes it quite noticeable relative to those buttons, even though users will rarely use it.

So we should reduce its size to make it less noticeable, perhaps down to the size of the icons on the other buttons.

(We might also consider styling the button like a button on hover, like Firefox does to its Close Tab button, to make it clearer that it's a button.)

**Comment by potch** [comment]
Fixed by https://github.com/mozilla/r2d2b2g/pull/648
