### ISSUE TITLE
Simulator starts on Firefox startup with session restore of Dashboard if it was running on Firefox shutdown

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#634]
If the Simulator is running, and the Dashboard is open, and the user quits Firefox and then restarts it, and Firefox is configured to restore the user's session on startup, then it not only restores the Dashboard, but it also restarts the Simulator. That's quite unexpected and seems unlikely to be what the user wants.

I think it's also a recent regression, as I don't recall it happening until very recently (late last week?).

@potch @nickdesaulniers perhaps one of last week's Dashboard changes triggered this?

**Comment by nickdesaulniers** [comment]
I cannot reproduce with 4.0pre6, or from source in Nightly.  When trying from source there is no option to restore previous session because the home page is about:blank.  I'm running this with `PROFILE=~/mozilla/profiles/r2d2b2g make run`.
How did you reproduce this?

**Comment by mykmelez** [comment]
I see it with `make run PROFILE=…` and Nightly.

Set Firefox to restore its previous session with Preferences/Settings > General > Startup > When Firefox starts: > Show my windows and tabs from last time.

**Comment by nickdesaulniers** [comment]
Verified good `b746170`, running a bisect

**Comment by nickdesaulniers** [comment]
result of my bisection

```
5df4723f4df315583a69b4fb9634a443eb8bcd78 is the first bad commit
commit 5df4723f4df315583a69b4fb9634a443eb8bcd78
Author: Matt Claypotch <thepotch@gmail.com>
Date:   Fri Jun 14 12:28:05 2013 -0700

    remove old panel showing logic

:040000 040000 eaefbf5fe371f6c0275dbf343567b5379d354f71 1c0a875121d85430350fdc84efe9b25b1fdad2c5 M  addon
```

I'll take a look at this tomorrow and try to help debug

**Comment by potch** [comment]
it would appear that by making the Simulator module init before page load, the behavior we're seeing occurs. I can look into why.

**Comment by mykmelez** [comment]
Thanks @nickdesaulniers and @potch for looking into this! @nickdesaulniers says on IRC that he'll take it on, so assigning it to him!

**Comment by nickdesaulniers** [comment]
I feel completely baffled by this.  The only thing I can think of is that Firefox is restoring the previous state of the form on the page when the document.readyState changes to complete which is after the [toggler's checked property is set to false](https://github.com/mozilla/r2d2b2g/blob/master/addon/data/content/js/main.js#L13).  Something is toggling the #command-toggle after the document has loaded, but before any [messages from the simulator](https://github.com/mozilla/r2d2b2g/blob/master/addon/data/content/js/main.js#L57) come in.  I would have suspected [this](https://github.com/mozilla/r2d2b2g/blob/master/addon/data/content/js/main.js#L74) but even commented out doesn't fix the problem.  When you set the pref to "Show my **windows** and tabs from last time", isn't the b2g process a window?  Though not a Firefox process window, isn't it still a child process?
