### ISSUE TITLE
r2d2b2g 3.0.1 not working on ubuntu12.04/firefox21.0

### ISSUE THREAD

**Issue by jandendolder** [mozilla/r2d2b2g#639]
installed "firefox os simulator 3.0.1" on firefox21.0, it is visible as an installed add-on. Nowhere in the menu I find an item pointing to the simulator, especially NOT in tools/Web developer. The add-on is available in the directory tree:
.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g
Probably interesting to know:

$~/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/adb/adb devices
bash: /home/mynameis/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/adb/adb: Permission denied

Another instance of adb is actually working on my system

$/usr/bin/adb devices
List of devices attached 
full_keon   device

No idea what to try next. Anyone good suggestion ?

**Comment by mykmelez** [comment]
Hi @jandendolder, sorry to hear about this problem! Please try the latest preview build of the next version of the Simulator ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) to see if we've solved the problem since 3.0.1.

**Comment by jandendolder** [comment]
Thanks for replying. I installed the latest version (4.0pre6). I found a menuitem under tools/Web developer now. If I activate the menuitem 'firefox os simulator' it gets activated. On the left side I see 'simulator .. stopped' and under it 'device connected'. If I disconnect the keon it replies 'device disconnected', so it looks it is communicating with my keon. If I click 'stopped' nothing happens ('stopped' stays 'stopped'), but in the upper part I get the next error:
"'/home/mynameis/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g is not an executable file'"
If I execute this 'b2g' file from the command line I get the same error.

**Comment by mykmelez** [comment]
What does `ls -la /home/mynameis/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g` report? And what kind of Linux (distribution, version, and bit depth) is your installation?

**Comment by jandendolder** [comment]
$ whoami
user
$ ls -la /home/mynameis/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g
-rwxr-xr-x 1 user user 71948 jun 12 15:25 /home/mynameis/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g

distro is ubuntu 12.04 i386

**Comment by mykmelez** [comment]
What happens if you run `file` on the file? On my Ubuntu 11.10 32-bit system I get:

myk@ubuntu:~$ file /home/myk/.mozilla/firefox/do32rbri.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g 
/home/myk/.mozilla/firefox/do32rbri.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, stripped

**Comment by jandendolder** [comment]
$ file /home/user/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g
/home/user/.mozilla/firefox/0axz0khs.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=0x46033bda4cf417ef39f018570b8357b7559e56fd, stripped

**Comment by jandendolder** [comment]
Sorry accidently 'closed' the issue. Meanwhile I am trying to do the same on a different system, same os (ubuntu 12.04 i386). Making slightly more progress. I appended my comments on the appropiate issue #473.

**Comment by mykmelez** [comment]
I'm going to update my Ubuntu 11.10 32-bit system to 12.04 today and see if I can reproduce there.

**Comment by mykmelez** [comment]
I updated to 12.04 32-bit:

```
myk@ubuntu:~$ uname -a
Linux ubuntu 3.2.0-48-generic #74-Ubuntu SMP Thu Jun 6 19:45:16 UTC 2013 i686 i686 i386 GNU/Linux
```

But I still can't reproduce the problem. Starting the Simulator (i.e. the `b2g` executable) works from both the Dashboard and the command line. And it works with both 3.0.1 and 4.0pre7 (the latest preview build). Moreover, _ldd_ sees it as an executable file with a set of dependencies that look standard:

```
myk@ubuntu:~$ ldd /home/myk/.mozilla/firefox/do32rbri.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g 
    linux-gate.so.1 =>  (0x00a13000)
    libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0x00287000)
    libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0x00aa0000)
    libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0x00476000)
    libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0x00df5000)
    libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0x00806000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0x002a2000)
    /lib/ld-linux.so.2 (0x0065f000)
```

On the off chance that the file was corrupted during download, you might check the md5sum:

```
myk@ubuntu:~$ md5sum /home/myk/.mozilla/firefox/do32rbri.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g 
ffebb6c91887c816c53609e3c75dee42  /home/myk/.mozilla/firefox/do32rbri.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/b2g
```

I also tried installing the Simulator in the guest account in case it has to do with permissions to install and run software (my personal account is an "administrator"), but I was able to run the Simulator after installing it as the guest.

**Comment by jandendolder** [comment]
two soals and one thought. I also started from scratch on a fresh installed ubuntu 12.04 system. It went smoothly into installing the simulator. It just worked like expected. The only thing I can think of is that any other product on my system was interfering with the simulator in an unpredictable manner. If I happen to find out during the reinstall of things what is going on in my system I will let you know. So far thanks very much for the support. I will close the ticket.

**Comment by mykmelez** [comment]
@jandendolder I'm glad to hear it's working for you now! And please do let us know if you find out more info about what caused it to fail!
