### ISSUE TITLE
Weird bugs

### ISSUE THREAD

**Issue by ShadowFox13** [mozilla/r2d2b2g#649]
The simulator keeps thinking I'm pressing letters twice when I'm only hitting them once... Also YouTube videos will only lode on the desktop site... Is this normal for the Windows version?

**Comment by mykmelez** [comment]
> The simulator keeps thinking I'm pressing letters twice when I'm only hitting them once

That is issue #629.

> Also YouTube videos will only lode on the desktop site... Is this normal for the Windows version?

Per [Firefox OS Simulator: Audio/video codecs](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Audio.2Fvideo_codecs), it isn't possible to test video playback in apps and websites (like the mobile version of Youtube) that rely on codecs that depend on hardware-accelerated decoding.
