### ISSUE TITLE
after drag to scroll, click is ignored

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#651]
When I click after dragging to scroll an app like Settings and Marketplace, the click is ignored. If I click again, though, the second click is usually observed, although sometimes I have to click a third time before the click is observed.

Steps to Reproduce:
1. start Settings and click-drag to scroll to bottom of app;
2. click Device Information.

Expected Results: Device Information view opens.
Actual Results: nothing happens.

You can also reproduce by scrolling down the Marketplace app and then clicking on an entry for a popular app.

I'm not sure if it's related, but clicking and click-dragging triggers numerous errors like the following:

```
[23:32:29.091] NotSupportedError: Operation is not supported @ chrome://desktop-helper.js/content/touch-events.js:167
```

@ochameau this looks like another issue with the touch event emulation.

**Comment by nickdesaulniers** [comment]
Yes I see this as well.  I had a dummy app with a single button, and I have to click it twice for it to call it's onclick handler, then once after that.

**Comment by StrawMan** [comment]
Yes indeed, unfortunately it's resurfaced in pre7:

#560

**Comment by ochameau** [comment]
Oh, sorry, I missed updating the simulator when bug 869689 was uplifted!!
