### ISSUE TITLE
Apps don't start unless clicked exactly in the centre of the app icon

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#654]
Apps present in the OS Simulator have to be clicked right in the centre for the app to particularly start. Also, clicking in the space between two different applications in a row also ends up generally opening the application to the right of the clicked region.

![clickedpoint](https://f.cloud.github.com/assets/4545925/703087/6a871854-dda3-11e2-9a64-f73ec5689b14.png)

Clicking at the point where the pointer is ends up opening CitySearch.

**Comment by nickdesaulniers** [comment]
It seems contradictory that you have to click in the center of an icon to start an app, but you can also start an app by clicking in between icons.  I did not find that I had to click in the center of an icon to start it.

Anyways, it's more important for the app to have large click targets (larger than the icons themselves) on mobile than to have precise precision in the simulator.  The click handlers must be on the enclosing divs, not the icon imgs.  Everything.me is part of gaia, and we shouldn't be monkeypatching apps from gaia just for the simulator.
