### ISSUE TITLE
FirefoxOS Simulator mp3 issue

### ISSUE THREAD

**Issue by paolooo** [mozilla/r2d2b2g#659]
Hi,

I'm currently developing an app that requires to play mp3 audio file but FirefoxOS Simulator somehow doesn't play .mp3, but it works well on.ogg files.

Any help will do thank you.

:)

Paolo

**Comment by nickdesaulniers** [comment]
@paolooo , yes this is a [known issue](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Audio.2Fvideo_codecs).  The simulator, an add on for desktop Firefox, shares the same codec support as desktop Firefox.  While we could implement software decoding, which would be practical in the simulator since it would be running on a desktop IMO, we could also wait for support to land in desktop Firefox and not have to add a significant amount of code to the simulator.

**Comment by paolooo** [comment]
@nickdesaulniers  even on Firefox Nightly? Thanks for the quick reply :)

**Comment by paolooo** [comment]
@nickdesaulniers I just wonder why the Simulator doesn't support, because if I test .mp3 using HTML5 &lt;audio> on desktop Firefox or Nightly, it just works perfectly... but it doesn't work on FirefoxOS Simulator on both desktop Firefox and Nightly version.

**Comment by nickdesaulniers** [comment]
@paolooo are you on Windows?  I think we may have enabled mp3 codec support in desktop Firefox for Windows already.

**Comment by nickdesaulniers** [comment]
As a side note, codec support implementation is complex, and varies by host operating system.  This [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=799318) is a high level overview for implementation support.

**Comment by paolooo** [comment]
I see... Yes, I'm using Windows.. So, for now mp3 won't play on Simulator (desktop Firefox and Nightly) but it will work on Firefox device right?

Is there a chance that FirefoxOS Simulator will support mp3 in the near future on Windows?

**Comment by nickdesaulniers** [comment]
> So, for now mp3 won't play on Simulator (desktop Firefox and Nightly) but it will work on Firefox device right?

Right.

> Is there a chance that FirefoxOS Simulator will support mp3 in the near future on Windows?

See my [first answer](https://github.com/mozilla/r2d2b2g/issues/659#issuecomment-20083243).

**Comment by mahemoff** [comment]
@nickdesaulniers Your first answer says you're waiting for support to land in desktop Firefox OS; if that's present now on Windows nightly, isn't that now possible? Or maybe it's a matter of waiting til it's more stable...just trying to understand what's preventing it.

**Comment by mahemoff** [comment]
@nickdesaulniers Any update on this? It seems like this should work in Windows now, given that the hardware codec is there.

**Comment by nickdesaulniers** [comment]
@mahemoff just tested on today's nightly build on Windows.  No beans.  Though I think it may be hidden behind a pref.  Let me ask some of my friends who work on the media team.

**Comment by mahemoff** [comment]
@nickdesaulniers Appreciate it, thanks.
