### ISSUE TITLE
Scrolling Up and Down from the centre of the screen in Firefox OS Simulator.

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#661]
### Steps to reproduce
1. Run simulator from Tools -> Web Developer -> [Firefox OS Simulator](resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html)
2. Swipe towards the right from the home screen showing the time.
3. Select any one of the categories, here I chose Social
4. To scroll the screen up and see the apps below, the scrolling is only possible while pressing the pointer and dragging it upwards from any of the two cursor positions as shown in the next two pictures.

![working_point1](https://f.cloud.github.com/assets/4545925/711985/45e4895e-de9e-11e2-8466-5f27af81157e.png)
While dragging from this point shown in figure above, you can even drag the cursor towards the top of the screen and hence out of the simulator screen. ( **I believe this dragging out of the simulator screen shouldn't be allowed** )
![working_point2](https://f.cloud.github.com/assets/4545925/711984/45de861c-de9e-11e2-9f73-5cef06b5267f.png)
The same scroll action can be done from this point, dragging from the bottom ,up!

Both of the actions result in the following scrolled screen.
![scrolled_screen](https://f.cloud.github.com/assets/4545925/711982/452f8edc-de9e-11e2-8e90-1b09cebc59be.png)

But here's what is the problem, Many phone users also scroll from the middle of the screen as shown in the figure below, but this doesn't work on the simulator when dragged up from this location. 
![scroll_not_working](https://f.cloud.github.com/assets/4545925/711981/44152b24-de9e-11e2-8c06-b2e2eff9da17.png)
#### What could be done

1: Add the feature to enable scrolling from the middle of the screen.
2: Do not allow the scrolling to continue if cursor dragged out of the simulator window. 
( _after discussing if it would be a good idea or not_)

**Comment by nickdesaulniers** [comment]
1. works for me in 4.0pre9 in OSX, maybe OS specific?
2. Not sure how we could detect that? @ochameau

**Comment by sudheesh001** [comment]
Works on Windows 8. Could be OS specific.

**Comment by mykmelez** [comment]
It works for me on Ubuntu 13.04 64-bit as well.

@sudheesh001 What version of the Simulator are you testing? Version 3.0 had limited support for touch event emulation, and some of the preview builds of 4.0 also didn't support touch events well. But the 4.0 release build should support them correctly. Can you test with the latest version and let me know if you still see the problem?

You can get 4.0 from the AMO listing page: https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

**Comment by sudheesh001** [comment]
Fixed in v4.0 Works fine.
