### ISSUE TITLE
Enable USB Storage icon error

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#664]
The Storage section of the settings application, has an option called Enable USB Storage having the **Airplane Mode** as the icon, this icon needs to be replaced with a USB symbol.

![icon_error](https://f.cloud.github.com/assets/4545925/716400/1b4c95fa-df35-11e2-8fdf-2f760207828d.png)
### What could be done

1: Replace the icon with the correct icon to avoid confusion.

**Comment by nickdesaulniers** [comment]
Fixed in 4.0pre9 and source.  Was probably a gaia issue that was fixed when we updated our submodule.  Thanks for taking the time to report though!  We appreciate it!
