### ISSUE TITLE
CONTRIBUTING.md talks about step 9 when there isn't any

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#665]
The current file says 

```
## Using Custom Profiles ##

If you need to use a custom Firefox profile, you can skip step 9 and run via
the following command

`PROFILE=/path/to/arbitrary/profile make run`
```

Updating it by either removing the step 9 part and changing the portion as

If you wish to use a custom Firefox profile which is the best way to simulate Gaia in the browser, the URL specified in this command is actually intercepted and routed to a local web server that's started while using this profile (there's a custom Firefox extension that runs the local server, while using this profile).

```
/path/to/firefox -profile /Volumes/Mozilla/b2g/B2G/gaia/profile http://system.gaiamobile.org:8080
```

On Mac OS X

```
/Applications/FirefoxNightly.app/Contents/MacOS/firefox -profile /path/to/B2G/gaia/profile http://system.gaiamobile.org:8080
```

Or anything else appropriate.

**Comment by nickdesaulniers** [comment]
@sudheesh001 , yes this would be a good beginner bug if you want to remove the reference to line 9 with something like `If you need to use a custom Firefox profile, instead run with following command` or something.  The second part you mention doesn't really have anything to do with contributing to the simulator.  Maybe there is a better place for that tip?  Anyways, would you like to submit the patch for the line 9 reference?

**Comment by sudheesh001** [comment]
Yes :+1: I'd be very happy to do so. Thank you

**Comment by nickdesaulniers** [comment]
Thank you!  Please mention me in the pull request and I'll be happy to review it!
