### ISSUE TITLE
Connect fails to connect

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#679]
STR:
1. Open a few apps by clicking Connect in their listing in the dashboard and close them using command Q.

Expected:
Multiple apps can be opened and connected to.

Actual:
After 1 or 2 apps being opened and closed in this way, connect stops working.  All I see in the console is `info: r2d2b2g: Simulator.onMessage connectToApp`.  Reopening the dashboard tab doesn't fix this, restarting the Firefox process does.

**Comment by mykmelez** [comment]
cc: @ochameau 

@nickdesaulniers To conform: when you say "close them using command Q," does that mean you press Connect to connect to an app, starting both the Simulator and the app within the Simulator in the process, and then disconnect by pressing Command-Q to quit the Simulator (and the app within)?

**Comment by nickdesaulniers** [comment]
Yes

**Comment by mykmelez** [comment]
I can reproduce by quitting the Simulator as soon as it opens, before the toolbox has a chance to appear. After that, pressing the Connect button for another app doesn't have any effect.
