### ISSUE TITLE
Dashboard reload sets toggle switch to Stopped even if Simulator is running

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#691]
If you reload the Dashboard while the Simulator is running, the toggle switch changes to Stopped, although it should stay Running.

Steps to Reproduce:
1. press toggle switch to start Simulator;
2. reload Dashboard.

@potch, @nickdesaulniers regression from a Dashboard change?

**Comment by nickdesaulniers** [comment]
I did not find this to be the case.  Are you working out of master?  What's your latest commit?

**Comment by mykmelez** [comment]
I'm working out of master. My latest commit is the tip: 2dca3c594a3e338b4b9e21762d68d637693e0693.

It seems to be a race, as reloading repeatedly shows sometimes Running, sometimes Stopped.

**Comment by nickdesaulniers** [comment]
@mykmelez , can you try with #683 applied?

**Comment by mykmelez** [comment]
Yes, I just tried it, and #683 doesn't fix this issue.

**Comment by mykmelez** [comment]
But another commit to #683 did fix it, so this is now fixed.
