### ISSUE TITLE
HERE app shows directory listing

### ISSUE THREAD

**Issue by untitaker** [mozilla/r2d2b2g#692]
![screenshot](http://i.imgur.com/910jKxg.png)

**Comment by nickdesaulniers** [comment]
Packaged apps do this when there the [launch_path](https://developer.mozilla.org/en-US/docs/Web/Apps/Manifest) is messed up.

**Comment by untitaker** [comment]
This is just the untouched emulator.

**Comment by mykmelez** [comment]
Thanks for reporting! This was actually reported already, and we're tracking it in #386. Please follow that issue to track our progress addressing it!
