### ISSUE TITLE
 Denied permission 'systemXHR'

### ISSUE THREAD

**Issue by marti1125** [mozilla/r2d2b2g#699]
![simulador](https://f.cloud.github.com/assets/223240/747008/f990865a-e444-11e2-8b9e-6e37b10db4fa.png)

when I add this line "type": "privileged" It doesn't show warning message.

but I need to remove that line for validate my manifest.

![validate](https://f.cloud.github.com/assets/223240/747023/ab87fd2a-e445-11e2-9d60-e63ecd5341c6.png)

**Comment by rpl** [comment]
Only packaged app can be "type privileged", when you put an http manifest
url into the marketplace validator it will be validated as an hosted app.

If you archive your packaged app in a zip and submit the zip to the
marketplace validator, you should be able to validate it correctly as a
packaged app.

**Comment by nickdesaulniers** [comment]
@marti1125 the [MDN page](https://developer.mozilla.org/en-US/docs/Web/Apps/App_permissions) on permissions has the full listing.  Apps can either be hosted or packaged.  And the packaged apps have three levels of permissions, in increasing restriction: web, privileged, certified.  See [this](http://nickdesaulniers.github.io/firefoxOSPresentation/#/step-7) and the following slides for more info.
