### ISSUE TITLE
Report emulator resolution and not desktop Firefox resolution

### ISSUE THREAD

**Issue by JoeStagner** [mozilla/r2d2b2g#7]
Content seems to think the screen resolution of the tool's display is the same as the full version of firefox.

**Comment by tofumatt** [comment]
I'ma check this out; I think I can figure it out myself.

**Comment by lisabrewster** [comment]
Just checking in, is there an update on this?  It's my favorite.  =]

**Comment by rpl** [comment]
fixed by #305
(it will be released in the next simulator preview build)
