### ISSUE TITLE
Audio Testing. Keeps loading for more than 10 minutes.

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#704]
#### Tested on : Windows 8, Aurora v24.0a2
1. Open the Browser in Firefox OS Simulator
2. Surf to http://areweplayingyet.org/
3. Please check the issue of bad layout display ? I've posted an issue [here](https://github.com/soundcloud/areweplayingyet/issues/48) because I believe its website specific and not a problem with the OS Simulator.\* _Other mobile websites work properly._
4. Click on the play all button.
5. Here is how it started off.<br>
   ![overlapped](https://f.cloud.github.com/assets/4545925/767073/e59f5984-e875-11e2-8420-98fe0cb11b7b.PNG)
6. After quite a long time.<br>
   ![1](https://f.cloud.github.com/assets/4545925/767080/24ffdac2-e876-11e2-951a-73e8179c5a6d.PNG)
   ![2](https://f.cloud.github.com/assets/4545925/767081/252d8a1c-e876-11e2-99fb-69dc3e329838.PNG)

It just keeps loading. Can someone confirm if the same is happening on the phone ?

Can we fix the mp3 playback issue ? or does it violate any patent. Support H.264/AAC/MP3 video/audio playback ?  H.264/AAC/MP3 has been shipped on Firefox for android , is there work needed for Firefox OS ? { Am i discussing this in the wrong place and should i rather go to bugzilla? }

**Comment by nickdesaulniers** [comment]
Duplicate #659
