### ISSUE TITLE
receipts tests depend on other tests, hang if run by themselves

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#707]
The receipts tests hang if you run them by themselves via `make test TEST=test-receipts`. So they seem to depend on other tests, which is dangerous (and breaks the common use case of running a subset of tests). So we should break that dependency.

@nickdesaulniers says he can take this on.

**Comment by mykmelez** [comment]
It looks like the specific other test script that _receipts_ depends on is _main_, since the tests don't hang when both of those are run via `make test TEST='main\|receipts'`.

@nickdesaulniers Have you made any progress on this?

cc: @bkase

**Comment by nickdesaulniers** [comment]
Haven't looked into it yet, been swamped with partner questions.

**Comment by nickdesaulniers** [comment]
```
error: r2d2b2g: An exception occurred.
TypeError: socket is undefined
resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/adb/adb-device-tracker.js 115
```

^^^ When I run `make test`, but I do see `make test TEST=test-receipts` hanging for a different reason.

**Comment by nickdesaulniers** [comment]
So the [window reference](https://github.com/mozilla/r2d2b2g/blob/master/addon/test/test-receipts.js#L91) is not [posting messages](https://github.com/mozilla/r2d2b2g/blob/master/addon/test/test-receipts.js#L109) to the [simulator](https://github.com/mozilla/r2d2b2g/blob/master/addon/lib/simulator.js#L1406).

**Comment by mykmelez** [comment]
> error: r2d2b2g: An exception occurred.
> TypeError: socket is undefined
> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/adb/adb-device-tracker.js 115
> 
> ^^^ When I run make test, but I do see make test TEST=test-receipts hanging for a different reason.

This happens when the Simulator is running and has loaded libadb in another Firefox process (f.e. your main Firefox process). The workaround is to quit that process. (Not sure what the fix is, but @bkase is going to make the error message more recognizable in the meantime.)

**Comment by nickdesaulniers** [comment]
So test-main requires main.js, which is what my test depends on.  Requiring main a second time exposes the socket error because an instance of the simulator is created for each require.  What's unfortunate is that the side effects of requiring main.js are not limited to a single test file.  @bkase suggested moving all test cases that require main into test-main.  It might be possible to improve the clean up code between test case runs, or undo corresponding require('main')'s somehow.  Thoughts, @mykmelez ?
