### ISSUE TITLE
App added to dashboard without icon, but pushed with Icon

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#708]
[This manifest](http://m.youtube.com/mozilla_youtube_webapp) when added to the dashboard does not have an icon, but when I push it to device it does.  It has an absolute path for the icons, but I thought they had to have the same origin as the manifest?

**Comment by mykmelez** [comment]
> This manifest when added to the dashboard does not have an icon, but when I push it to device it does. It has an absolute path for the icons, but I thought they had to have the same origin as the manifest?

I think they do and will investigate further; in the meantime, I merged @ccarruitero's change so the behavior in the Dashboard is consistent with the behavior in the Simulator and on devices.
