### ISSUE TITLE
Welcome Page?

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#71]
r2d2b2g had a welcome screen in its first version. I just switched it back on, but now thinking about its usefulness.

Some questions:
- When to show it? Its introduction might only be useful in first launch and upgrade (it later could feature a changelog)
- What to show? Currently explains how to open the FxOS Simulator dashboard and the home button shortcut.

Thoughts? @dangoor @mykmelez

**Comment by dangoor** [comment]
I don't think we need a welcome page right now...
