### ISSUE TITLE
Firefox OS Simulator crash on  OS X Mavericks DP3

### ISSUE THREAD

**Issue by midudev** [mozilla/r2d2b2g#714]
I know that OS X Mavericks DP3 is a Developer Preview. That's only to help to determine if that's an error that could be present in the final version to take care of. In fact, for that is the Developer Preview, to check if all is working fine. So, I hope it helps you. :)

Process:         firefox [6092]
Path:            /Applications/Firefox.app/Contents/MacOS/firefox
Identifier:      firefox
Version:         22.0 (2213.6.18)
Code Type:       X86-64 (Native)
Parent Process:  firefox [5955]
Responsible:     firefox [5955]
User ID:         503

Date/Time:       2013-07-12 18:58:40.372 +0200
OS Version:      Mac OS X 10.9 (13A510d)
Report Version:  11
Anonymous UUID:  EA588030-2747-CF6A-3139-2C7C270FC7D9

Sleep/Wake UUID: 1F3932C3-9590-43F6-B6DC-190D5E852720

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
**\* multi-threaded process forked ***
crashed on child side of fork pre-exec
**\* error for object 0x136d89c40: pointer being freed was not allocated
...
...
External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 16024
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=270.5M resident=126.4M(47%) swapped_out_or_unallocated=144.2M(53%)
Writable regions: Total=404.8M written=25.1M(6%) resident=220.7M(55%) swapped_out=328K(0%) unallocated=184.1M(45%)

REGION TYPE                      VIRTUAL
===========                      =======
ATS (font support)                 32.0M
ATS (font support) (reserved)         8K        reserved VM address space (unallocated)
CG image                             36K
CG raster data                      192K
CoreImage                            16K
Kernel Alloc Once                     8K
MALLOC                             84.4M
MALLOC (admin)                       32K
Memory Tag 242                       12K
Memory Tag 251                       16K
OpenCL                               44K
OpenGL GLSL                        1664K
STACK GUARD                        56.0M
Stack                              33.6M
VM_ALLOCATE                       250.4M
VM_ALLOCATE (reserved)              260K        reserved VM address space (unallocated)
__DATA                             52.5M
__IMAGE                             528K
__LINKEDIT                         67.1M
__TEXT                            203.4M
__UNICODE                           544K
mapped file                         1.5G
shared memory                         4K
===========                      =======
TOTAL                               2.2G
TOTAL, minus reserved VM space      2.2G

**Comment by midudev** [comment]
on the system.log:

Jul 12 19:06:20 miduga firefox[6234]: firefox(6234,0x7fff76396310) malloc: **\* error for object 0x119205288: pointer being freed was not allocated
    **\* set a breakpoint in malloc_error_break to debug
Jul 12 19:06:20 miduga.local ReportCrash[6182]: Saved crash report for firefox[6234] version 22.0 (2213.6.18) to /Users/miguel/Library/Logs/DiagnosticReports/firefox_2013-07-12-190620_miduga.crash
Jul 12 19:06:25 miduga firefox[6235]: firefox(6235,0x7fff76396310) malloc: **\* error for object 0x11d2105e0: pointer being freed was not allocated
    **\* set a breakpoint in malloc_error_break to debug
Jul 12 19:06:25 miduga.local ReportCrash[6182]: Saved crash report for firefox[6235] version 22.0 (2213.6.18) to /Users/miguel/Library/Logs/DiagnosticReports/firefox_2013-07-12-190625_miduga.crash
Jul 12 19:06:29 miduga firefox[6236]: firefox(6236,0x7fff76396310) malloc: **\* error for object 0x127b25f48: pointer being freed was not allocated
    **\* set a breakpoint in malloc_error_break to debug
Jul 12 19:06:29 miduga.local ReportCrash[6237]: Saved crash report for firefox[6236] version 22.0 (2213.6.18) to /Users/miguel/Library/Logs/DiagnosticReports/firefox_2013-07-12-190629_miduga.crash
Jul 12 19:06:36 miduga firefox[6238]: firefox(6238,0x7fff76396310) malloc: **\* error for object 0x10ab681a8: pointer being freed was not allocated
    **\* set a breakpoint in malloc_error_break to debug
Jul 12 19:06:37 miduga.local ReportCrash[6237]: Saved crash report for firefox[6238] version 22.0 (2213.6.18) to /Users/miguel/Library/Logs/DiagnosticReports/firefox_2013-07-12-190637_miduga.crash
Jul 12 19:06:45 miduga.local netbiosd[4566]: findReachableAddress: Using port 139 family = 33

**Comment by midudev** [comment]
More info about that. If I install Firefox 21 that's not happening. The issue is present only with Firefox 22.

**Comment by mykmelez** [comment]
Hi @miduga, thanks for the report! However, based on that crash report, it looks like this is actually a crash in Firefox, not the Simulator. It might be [bug 886096](https://bugzilla.mozilla.org/show_bug.cgi?id=886096), although it's hard to say. By any chance, did Mozilla's Crash Reporter appear after the crash? If so, you might be able to get more information about the crash by restarting Firefox and going to about:crashes.

In any case, I recommend you track the aforementioned bug (or file a new bug report if you think your crash is different). You can also track [meta-bug 883824](https://bugzilla.mozilla.org/show_bug.cgi?id=883824), which collects various bugs about issues with Mavericks.

**Comment by midudev** [comment]
Okey! Thanks and keep up the good work!

**Comment by ochameau** [comment]
Actually, that's a simulator crash, tracked in the following bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=928168

**Comment by midudev** [comment]
Interesting. Thanks.
