### ISSUE TITLE
Update button gives no feedback

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#72]
When I click the update button for an app in the Manager, there's no visual indication that anything has occurred.

**Comment by dangoor** [comment]
I'll add to this that update apparently requires a restart of the Simulator (at least if an app is being reinstalled). If that's the case, the feedback the user sees should specifically say that. Or should we just restart the Simulator automatically?

**Comment by mykmelez** [comment]
We should restart the simulator automatically! In which case the feedback might be as simple as bringing the simulator window to the forefront.

**Comment by syssgx** [comment]
That's an issue for b2g, right?

**Comment by mykmelez** [comment]
This is actually the responsibility of the addon, as the Update button is part of the addon, and the code that updates the app when the user presses the button is in the addon.

**Comment by mykmelez** [comment]
Merge af60ee1c6e5a72f4a99bbe0cb1df7da69f8b9b73 makes Update launch the app in B2G. @dangoor is that sufficient to resolve this issue?

**Comment by dangoor** [comment]
Yes, that should do it. There just needs to be _something_ that happens, and that certainly sounds like a more useful something than just printing a message!
