### ISSUE TITLE
"This page doesn't have any stylesheet"

### ISSUE THREAD

**Issue by sole** [mozilla/r2d2b2g#721]
The style editor doesn't find any styles on my app... but there are a few of them indeed!
https://github.com/sole/rtcamera/blob/master/index.html#L6

That was with the latest version of the simulator that I can get as an Add-on.

I then tried to build my own version but the outcome was even worse--the style editor option didn't even appear when connecting to my app.

Is there anything I can do for helping to debug this? :-)

**Comment by harthur** [comment]
@sole what version of Firefox are you using?

**Comment by sole** [comment]
I am using Nightly. I can test with other versions if you want! :-)

**Comment by sole** [comment]
So I tested this on Firefox 23 Beta and it indeed showed me the styles. And I was going to say aaah, Nightly is funny, blabla. Then I updated to the latest Nightly and tested this again... _and now it works beautifully_

Closing bug for evident reasons :-D

Thanks for having a look anyway! :thumbsup:

**Comment by harthur** [comment]
I just landed a fix in Nightly, glad to see it worked. Thanks for reporting!

**Comment by sole** [comment]
Hey @harthur - out of curiosity, could you point me to the fix? Just to get an idea of the internals :-)

**Comment by harthur** [comment]
@sole the fix is over here in Firefox [bug 892757](https://bugzilla.mozilla.org/show_bug.cgi?id=892757)
