### ISSUE TITLE
Configure server for push notifications

### ISSUE THREAD

**Issue by digitarald** [mozilla/r2d2b2g#724]
To test push notifications, the Simulator should have push notifications enabled and configured.

```
user_pref("services.push.enabled", true);    
// Via JR from services/ops team
user_pref("services.push.serverURL", "wss://push.services.mozilla.com");
```

**Comment by digitarald** [comment]
I verified with push team that this is the official server and the best choice.

**Comment by nikhilm** [comment]
Turns out its not the prefs that are causing a problem, but bug 856495 which hasn't been uplifted to b2g18.

**Comment by mykmelez** [comment]
I built and pushed B2G builds with the fix for bug 856495, then I updated the Simulator to use the new builds and tested with @nikhilm's simplepush-test-app, which appeared to work as expected. So this has been fixed, and the fix will make it into the Simulator preview builds I spin later today.

**Comment by nikhilm** [comment]
Thanks @mykmelez !
