### ISSUE TITLE
Pushing apps to ZTE Open require restart to show up

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#725]
When I push applications to my ZTE Open using the simulator the application doesn't show in the applications list (on the main screen). I have to restart the device for it to show up.

**Comment by mykmelez** [comment]
Hi @postal2600, sorry to hear about this problem! The problem you're experiencing is #441, which is a bug in B2G that I fixed earlier this year, but the fix didn't make it onto some older phones. The workaround is to restart your device the first time you push a packaged app; you don't have to restart after every time you push the app, though; only the first time you push the app. Alternately, you may be able to update your phone to a version of Firefox OS that contains the fix, although I'm not familiar with the process for your particular phone.
