### ISSUE TITLE
If I open the simulator after the phone has been connected to the computer, it doesn't detect the phone

### ISSUE THREAD

**Issue by sole** [mozilla/r2d2b2g#728]
If I disconnect and connect the phone again, it successfully shows the 'Device Connected' message.

I'm trying with Firefox Beta 23--noticed this while changing from Nightly to Beta to try determining if something else I found is a bug or a Nightly "feature" :-)

**Comment by mykmelez** [comment]
This sounds a lot like #441! So I'm going to guess it is. But please reopen if it turns out to be a different problem!

**Comment by sole** [comment]
Yes it sounds like it! Thanks for having a look, @mykmelez :)
