### ISSUE TITLE
Update does not restore apps that were deleted in Simulator

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#73]
If you delete an app from the Simulator and click the Update button in the Manager, the app does not reappear in the Simulator.

**Comment by digitarald** [comment]
Works for me (installed an app, uninstalled in Simulator, clicked update in Dashboard, restarted Simulator, app is there), does this happen with 5.1?

**Comment by dangoor** [comment]
It's possible that:

# I didn't restart the simulator

# The apps were installed on the last screen

Either way, playing with it now (0.6) it seems to be working fine.
