### ISSUE TITLE
Firefox OS Simulator doesn't close when Dashboard page is closed.

### ISSUE THREAD

**Issue by sudheesh001** [mozilla/r2d2b2g#737]
### Steps to reproduce:
1. Open resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html or 
   Tools > WebDeveloper > Firefox OS Simulator.
2. Once the simulator starts, open the Amazon app.
3. Close the Dashboard screen on Firefox/Aurora
4. The Simulator doesn't quit. Daemon still keeps running on port.
### Required effect:

The simulator should close too.

**Comment by nickdesaulniers** [comment]
I _thought_ this would be an easy fix; just try to toggle the sim onbeforeunload, but it doesn't look like window.postmessage is working at that time.

**Comment by ochameau** [comment]
Weird that it doesn't work onbeforeunload... 
May be we could listen for worker destroy event in main.js?

**Comment by nickdesaulniers** [comment]
[This](https://github.com/mozilla/r2d2b2g/blob/master/addon/lib/main.js#L122) looks like a bug.

**Comment by nickdesaulniers** [comment]
Oh, that block just makes sure to close the simulator process when ALL tabs are closed.

**Comment by sudheesh001** [comment]
Wouldn't it be better if the condition uses the URL instead of the title ? Maybe something like

``` javascript
Tabs.on('close', function(tab) {
  // Kill process when the last tab is gone or dashboard closed
  if (!Tabs.length || tab.url === "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/data/content/index.html") {
    Simulator.unload();
  }
  if (Simulator.worker) {
    Simulator.sendListTabs();
  }
});
```

In this case even if someone uses the simulator code to rename the title to something other than "Simulator Dashboard - Firefox OS" closing would still terminate the Simulator.

**Comment by nickdesaulniers** [comment]
Alex's [comment](https://github.com/mozilla/r2d2b2g/issues/737#issuecomment-22310192) is a less brittle solution.  That way the title and resource URI can change and this will still work.
