### ISSUE TITLE
[Receipts] fix manifest_url API parameter for packaged apps.

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#748]
See [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=867282#c1).

**Comment by bkase** [comment]
`make test TEST=test-receipts` hangs right now. Is it because of this bug?

**Comment by nickdesaulniers** [comment]
could be, haven't investigated yet

**Comment by nickdesaulniers** [comment]
Just tested this today, nothing broken.  Might not be live yet in production.

**Comment by nickdesaulniers** [comment]
I don't think this is an issue.
