### ISSUE TITLE
Add and open a webapp from the command line

### ISSUE THREAD

**Issue by fwenzel** [mozilla/r2d2b2g#758]
Use case is the following: For the Apache Cordova integration, there is a standard set of CLI commands that do something useful for all platforms. For "cordova emulate firefoxos", we would like to take the project as-is and pop it open in the Simulator.

A possible and fairly light-weight option would be to hand Firefox the Simulator's `resource://` URL with `?manifest=/Users/.../webapp.manifest` for a packaged app, or a manifest URL for a hosted app.

(Will it let you open a resource URL from the command line?)

Opinions?

**Comment by fwenzel** [comment]
I think @nickdesaulniers volunteered to implement this :)

**Comment by nickdesaulniers** [comment]
I think this can be separated into two issues:
1. Opening a manifest from a querystring parameter.
2. Running the simulator from the command line.

**Comment by nickdesaulniers** [comment]
Part 1 is #743

**Comment by fwenzel** [comment]
@nickdesaulniers did you have a chance to take a look? :)

**Comment by nickdesaulniers** [comment]
@fwenzel , yeah my initial solution won't work, see the discussion in #770 .  We'll probably have to whitelist sites using the Pagemod add-on SDK.

For part two, you can't run firefox from the command AND pass it the resource url; it won't open the simulator dashboard (but it would open an HTTP based URI).  There might be a way to run the add-on if you knew where it was (which is platform specific, and I think profile specific).

I'll have to do more digging before we can say whether this is feasible or not.  I'll have to take a look at this once I take care of some other things on my plate first.

**Comment by mykmelez** [comment]
I mentioned to @nickdesaulniers that it might be possible to use the xremote feature of Firefox to send it a command that the addon processes. The addon would need to add an xremote command handler to Firefox, which I'm not sure how to do. And xremote would then have to work as expected (which it did on Windows and Linux, the last time I checked; but Mac seemed busted). So I'm not sure how feasible this is; and xremote is not well documented; but there's the source, and there's this document that provides some basic info:

http://www-archive.mozilla.org/unix/remote.html

**Comment by fwenzel** [comment]
I am both in awe of and disturbed by an interface whose documentation is on www-archive ;)

**Comment by jlongster** [comment]
We need to start working on this feature soon. I can help out but I'd like to some help on where to start. Who can help mentor this feature?

**Comment by nickdesaulniers** [comment]
This project has been handed over to dev tools.  The state of maintaining this repo is questionable, ATM.

**Comment by jlongster** [comment]
Ok. I'll try to hit up the devtools team.

**Comment by ochameau** [comment]
I can help mentoring this. The main shift is that the dashboard, i.e.  most of the simulator UI is now the App manager (about:app-manager) directly bundled into Firefox, whose source code lives here:
  http://mxr.mozilla.org/mozilla-central/source/browser/devtools/app-manager/

The app manager itself, is able to launch any app by using the debugger protocol and calling start command of the webapps actor:
  UI launch code
  http://mxr.mozilla.org/mozilla-central/source/browser/devtools/app-manager/content/device.js#175
  Device webapps actor launch method
  http://mxr.mozilla.org/mozilla-central/source/toolkit/devtools/server/actors/webapps.js#722

Having said that, I'm not sure it is really usefull for you to go through the app manager. It sounds more productive to launch b2g runtime by yourself... And you should be able to launch an app with its --runapp argument:
  https://developer.mozilla.org/en-US/Firefox_OS/Using_the_B2G_desktop_client#option-runapp

**Comment by jlongster** [comment]
Since r2d2b2g isn't maintained as much anymore (focus is on app manager I think?) we should move the discussion of this over here: https://bugzilla.mozilla.org/show_bug.cgi?id=900230

What we're doing isn't related to the addon anyway. We're bypassing it completely and talking straight with B2G.

**Comment by mykmelez** [comment]
r2d2b2g is still being maintained! We've just reduced its scope, since part of its functionality has now landed in Firefox as the App Manager. Regardless, we can discuss issues in either bug tracker, and I've cc:ed myself, @ochameau, and @harthur to bug 900230. Let's continue the discussion there.
