### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by iFadey** [mozilla/r2d2b2g#761]
I am trying to initiate Bluetooth transfer using Web Activities but it looks like Bluetooth app is not working on the simulator. Even I tried using Bluetooth from Gallery app and same thing happens. It only show a dark blank screen and that's it.

Also I tried it on Geeksphone Keon. It looks like the real device is also giving error
"Bluetooth file transfer failed. Check that the Bluetooth settings are correct."

**Comment by mykmelez** [comment]
Hi @iFadey. Unfortunately the Simulator doesn't yet simulate bluetooth. See #393 for a bit more info.
