### ISSUE TITLE
Crashes when you open the Firefox app

### ISSUE THREAD

**Issue by The-MAZZTer** [mozilla/r2d2b2g#77]
Windows 7 SP3 x64, running the extension under Firefox UX 19.0a1 (2012-11-06).

Just installed for the first time, started it up, unlocked, ran the Firefox app.

Mozilla B2G crash reporter comes up, Details button doesn't seem to do anything.

I put a link to this issue in the comments field of the crash report before sending it.

**Comment by syssgx** [comment]
I can confirm for the Vista x86 version, Firefox 16.0.2.

**Comment by mykmelez** [comment]
This is fixed in the latest version!
