### ISSUE TITLE
I can't start the simulator.

### ISSUE THREAD

**Issue by vpaa** [mozilla/r2d2b2g#791]
Hi,

I installed the simulator from its website and I now see it in the list of Add-ons. However, there are only buttons like "Disable" and "Remove" and a link for more detailed information. However, there is no button or hint as to how to start the app again. If I go to the original website, it seems that I could re-install it, but surely there should be some other way to re-run an app than re-installing it.

This touches a broader problem: Now that apps are coming to Firefox (right?), how to manage them neatly?  After all, their nature is somewhat different from those typical add-ons that bring some new search engine or other service to Firefox.

Thanks.

**Comment by ccarruitero** [comment]
Hi,

For start the simulator you have to do in Tools/Web Developer/Firefox OS Simulator. You can found more details in https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Installing

**Comment by lukasvan3l** [comment]
I'm afraid I have the same problem, on a mac. In the screenshot you can see the firefox page displaying my extensions, where the firefoxos simulator is enabled. But when I go to the tools, there's no menu item there :(

Is this a mac issue?

![screen shot 2013-08-11 at 22 10 38](https://f.cloud.github.com/assets/169870/944578/3647f7ae-02c2-11e3-9f82-e30781e0f0ee.png)

**Comment by vpaa** [comment]
Thanks, ccarruitero, that solved the problem for me. My platform is Linux, so lukasvan3l's problem may be Mac-specific.

**Comment by ccarruitero** [comment]
@lukasvan3l can you tell more details about version of your system and addon?

**Comment by lukasvan3l** [comment]
When I went to the version tab of firefox it said I have version 19.0.2
And immediately it started downloading an update. Now I'm on 23.0.1 and the simulator is visible!

Weird that it didn't auto-update, I thought firefox did that? But I don't use firefox frequently...

thanks for the reaction anyway, but by now it seems fixed so I can continue my app!

**Comment by ccarruitero** [comment]
@mykmelez you can close this issue

**Comment by mykmelez** [comment]
> @mykmelez you can close this issue

Thanks, @ccarruitero!
