### ISSUE TITLE
I do not recognize the device

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/r2d2b2g#801]
I am currently testing (and developing) Windows 8.1 Preview, and I already have two devices Firefox OS (one ZTE Open and GeeksPhone Keon), the thing is that the simulator did not recognize any device.

Now install the necessary drivers, following Mozilla tutorials and instructions for Windows 8, it still does not recognize me and therefore I can not do push for my applications.

He already tried the comand "adb devices" and if I show the Keon, but not in the simulator.

**Comment by bkase** [comment]
Hi @rodmoreno

I think the problem with your Keon was fixed here: https://github.com/mozilla/r2d2b2g/pull/783 , what is the most recent build you have tried? (Just a warning -- it's a little crashy right now on Windows).

If your ZTE Open isn't showing up in `adb devices` when you run it from the commandline, then it won't get picked up by the simulator. Do you have the ZTE Open Windows drivers installed?

EDIT: It looks like you might have to build from source to get that fix from #783, maybe @myk can give you an updated build?

**Comment by mykmelez** [comment]
> EDIT: It looks like you might have to build from source to get that fix from #783, maybe @myk can give you an updated build?

I just pushed a new preview build with a new build of libadb!

Latest preview build:
- Windows: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi
- Mac: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi
- Linux: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi

**Comment by rodmoreno** [comment]
I I installed this version I post @mykmelez, effectively and recognize me well my device (Keon GeeksPhone I test yet ZTE Open) but when push do not: (

**Comment by rodmoreno** [comment]
I've been following the development and I have the beta 6, and since I had no problems with Keon or the Open, thank you very much for your help.
