### ISSUE TITLE
Package Build failed.

### ISSUE THREAD

**Issue by soumenganguly** [mozilla/r2d2b2g#813]
Hi
The build process encounters a fatal error while updating the submodule packages.According to the steps given in the README file,git initializes the submodule packages but when it tries to update those packages via --git submodule update-- it encounters an error:Repository not found ,while cloning a repo into the submodule path
addon/packages/gcli.Apparently this could be because git fails to initialize any such repo.

**Comment by jryans** [comment]
Hmm, maybe I had to repeat the word "fixes" for GitHub to figure it out... In any case, we should be able to close this now.
