### ISSUE TITLE
Crashes on startup with `X_GLXCreatePixmap: BadMatch`

### ISSUE THREAD

**Issue by DanOpcode** [mozilla/r2d2b2g#828]
When I start the Firefox OS Simulator it opens in a new window for a couple a seconds and then it disappears.

I'm running Manjaro Linux 64 bit with Nvidia's 325.15 drivers, and I have tried starting it in both Firefox 23.0.1 and Nightly 26.0a1. I'm pretty sure this is related to [bug 896287](https://bugzil.la/896287), but their problem seems to be resolved already.

In the terminal it crashes with the following error message:

```
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
console.error: r2d2b2g: 
  (process:6649): GLib-CRITICAL **: g_slice_set_config: assertion `sys_page_size == 0' failed
console.error: r2d2b2g: 
  ###!!! ABORT: X_GLXCreatePixmap: BadMatch (invalid parameter attributes); 62 requests ago: file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXCreatePixmap: BadMatch (invalid parameter attributes); 62 requests ago: file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
console.error: r2d2b2g: 
  (process:6680): GLib-CRITICAL **: g_slice_set_config: assertion `sys_page_size == 0' failed
console.error: r2d2b2g: 
  ###!!! ABORT: X_GLXCreatePixmap: BadMatch (invalid parameter attributes); 62 requests ago: file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXCreatePixmap: BadMatch (invalid parameter attributes); 62 requests ago: file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
```

**Comment by ekisu** [comment]
Same here... NVidia GT 610 with 325.15 proprietary driver.

**Comment by ochameau** [comment]
If that's related to bug 896287, you should have this bug fixed in the new simulator addon, 
the one that plugs to the new App manager feature directly shipped into Firefox 26+.
Could you confirm that it is actually working with this?

More info, here:
https://hacks.mozilla.org/2013/10/introducing-the-firefox-os-app-manager/

**Comment by ekisu** [comment]
Well, I started to use Nouveau drivers, and it's actually working, just saying. But I will reinstall the proprietary drivers to confirm that for you.

**Comment by ekisu** [comment]
It worked. However, it's a bit buggy, like the touchscreen keyboard double-presses(1.2) and the Enter button doesn't works with the search of the home screen(1.3).

**Comment by jryans** [comment]
Sounds like this issue is now resolved.
