### ISSUE TITLE
Firefoxx OS addon

### ISSUE THREAD

**Issue by Marian07** [mozilla/r2d2b2g#832]
Hello,

Nice add-on! keep the good work!

I was wondering how I could get the emulator on a PC, without the need to run continuously browser. I saw that is created in the Java language, it is possible emulation files in an interactive format or flash?

Br,
Marian

**Comment by ccarruitero** [comment]
I think you refer to b2g desktop build? You can build this from source or download from [mozilla ftp](ftp://ftp.mozilla.org/pub/b2g/nightly/latest-mozilla-aurora/)
