### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#84]
Can you please make a note on how to bring the task manager up?
pressing the home button doesn't work currently, as well as the arrow keys.

Also, how often is the xpi rebuild to reflect current changes?
Thanks

**Comment by mykmelez** [comment]
Holding down the Home key on your keyboard will do it (although there may be a different issue with viewing the task manager on some platforms). And so will holding down the Home button in the interface, as of commit 3ae8aa335b0643696c70a6b82251b0e6a7ca3108, which landed two days ago. I don't think that commit is in the most recent build, 0.6, but it will be in the next one 0.7, which comes out next week.

New builds come out once per week on Wednesdays.
