### ISSUE TITLE
insufficient permissions for device

### ISSUE THREAD

**Issue by worikgh** [mozilla/r2d2b2g#843]
I am using a Keon phone, Ubuntu 13.04 Firefox 20.0 and a freshly installed FirefoxOS simulator Addon downloaded from https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/.

On the phone I have enabled 'remote debugging' as per... https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Firefox_OS_build_prerequisites#Enable_remote_debugging

When I go to 'push' an app to my phone I get the following sequence of errors (from the browser console after enabeling verbose logging as per https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator#Simulator-verbose-logging....

-------------------START------------------------------
[13:31:32.828] info: r2d2b2g: Simulator.onMessage pushAppToDevice

[13:31:32.828] info: r2d2b2g: Simulator.pushAppToDevice: /home/worik/Documents/Research/FirefoxOS/Apps/CompanieNZ/manifest.webapp

[13:31:32.828] info: r2d2b2g: adb: forwardPort 6000

[13:31:32.828] info: r2d2b2g: adb: runCommand host:forward:tcp:6000;tcp:6000

[13:31:32.830] info: r2d2b2g: adb: runCommand onopen

[13:31:32.830] info: r2d2b2g: adb: len=34 30303145686f73743a666f72776172643a746370 001Ehost:forward:tcp

[13:31:32.831] info: r2d2b2g: adb: runCommand ondata

[13:31:32.832] info: r2d2b2g: adb: Response: FAIL

[13:31:32.832] info: r2d2b2g: adb: Error: insufficient permissions for device

[13:31:32.832] info: r2d2b2g: adb: runCommand onclose

------------------------------STOP----------------------------------------------------

This has worked before.  I have several apps on my phone that I installed via 'push'.  I expect I have unwittingly changed a setting on my phone.

Any ideas?

Worik

**Comment by ochameau** [comment]
The Simulator addon 4 isn't compatible with devices on devices on Firefox OS 1.2+. So if you keon is updated on nightly channel, it won't work.
If that's the case, I suggest you to give a try to the new app manager that is being shipped in Firefox Aurora 26:
  http://www.mozilla.org/en/firefox/channel/#aurora/aurora-desktop
This tool works only with phones on 1.2+. Once firefox started, open the page `about:app-manager` and install the two suggested addons.

**Comment by worikgh** [comment]
The down load from that link does not work.  None of the executables will run. 

Aurora from https://launchpad.net/~ubuntu-mozilla-daily/+archive/firefox-aurora is Aurora 25 and there is no "about:app-manager"

I have got Aurora 25.0a2 (2013-09-15) installed but I am still having no joy, but this is not V26 as you recommended

Worik

**Comment by ochameau** [comment]
What about this link?
http://www.mozilla.org/en-US/firefox/aurora/
This one installed Aurora 26 for me.

**Comment by worikgh** [comment]
No, it still fails.

I can find no documentation on that page, and I am assuming I am not doing something correctly.

I am unpacking the archive and trying to run ./firefox, ./firefox-bin and/or ./run-mozilla.sh directly.

worik@sharon:/tmp/firefox$ ./firefox
bash: ./firefox: No such file or directory
worik@sharon:/tmp/firefox$ ./firefox-bin 
bash: ./firefox-bin: No such file or directory
worik@sharon:/tmp/firefox$ ./run-mozilla.sh 

run-mozilla.sh: Cannot execute .

worik@sharon:/tmp/firefox$ 

Worik

**Comment by worikgh** [comment]
worik@sharon:/tmp/firefox$ file ./firefox-bin 
./firefox-bin: ELF 32-bit LSB executable,.....

It is a 32-bit executable and

worik@sharon:/tmp/firefox$ uname -m
x86_64

I am 64-bit

Duh!

Worik

**Comment by worikgh** [comment]
I have compiled Aurora from source.  OK

Running 26.0a2 (2013-10-03)

I added the simulator addon and the adb Helper Add-on suggested on the about:app-manager.

Looking at https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_the_App_Manager#Configuring_device it says I need to  sure my device is running Firefox OS 1.2+.

But in Settings -> Device information it says I am running "Boot2Gecko 1.0.1.0-prerelease"  last updated 20-Aug-2013.  I thought the whole problem was I was running FirefoxOS 1.2+.  Under "Check for Updates" it says I am running the latest version of FirefoxOS.

I am confused!

Anyhow when I plug in my phone the app-manager page at the bottom says "Not Connected.
Connect to: <??????????> or <Start Simulator>

Pressing the <??????????> button has no effect.

So I still do not have a useful set up.  

Worik

**Comment by worikgh** [comment]
I did not mean to close this.  Damn!  I'm reopening

**Comment by worikgh** [comment]
The problem was a missing udev entry.

When I created a rule in /etc/udev/rules.d with the lin:

SUBSYSTEM=="usb", ATTR{idVendor}=="05c6", MODE="0666", GROUP="plugdev" 

The problem went away.

I named my rule file: "01-firefoxos.rules" the name is irrelevant but it must end in '.rules' and the rules are executed in lexicographical order.
