### ISSUE TITLE
simulator doesn't detect peak

### ISSUE THREAD

**Issue by novia713** [mozilla/r2d2b2g#844]
i'm in fedora 19 simulator doesn't detect my geeksphone peak with adb console and remote debugging switched on.

**Comment by jryans** [comment]
What version of Firefox are you using?
What version of Firefox OS is on your Peak?
Do you have [udev rules](http://developer.android.com/tools/device.html#setting-up) set up?

**Comment by novia713** [comment]
Firefox → 24.0
Firefox OS Simulator → 0.5pre5
B2G in peak → 1.3.0 prerelease (from git repo from a couple of days ago)
adb output →  beb27088f488    device

**Comment by jryans** [comment]
When you say it "doesn't detect" the phone, do you mean that you do **not** see this image?

![device connected](https://dl.dropboxusercontent.com/s/mm8lrr34a9s6z2m/2013-10-07%20at%203.59%20AM.png)

**Comment by novia713** [comment]
affirmative

**Comment by nickdesaulniers** [comment]
You should be using the [app manager](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Using_the_App_Manager) for b2g > 1.1.
