### ISSUE TITLE
Firefox OS Simulater doesn't start

### ISSUE THREAD

**Issue by pollti** [mozilla/r2d2b2g#846]
Firefox OS Simulater doesn't start with Firefox 24.0
pollti

**Comment by jryans** [comment]
Which version of the Simulator addon are you trying?

**Comment by pollti** [comment]
I'm using Firefox OS Simulator 4.0. When i try to start it, it changes to the green running and after a while it shows the startscreen of Firefox OS for two seconds and then it stops completely. (Stopped)

**Comment by ccarruitero** [comment]
which OS are you using?

**Comment by pollti** [comment]
Sorry, it works now, don't know why it didn't work for a week... (I'm using Windows 7 Pro SP1)

**Comment by ccarruitero** [comment]
@mykmelez you can close this

**Comment by pollti** [comment]
oooh yes, sorry :D
