### ISSUE TITLE
RTL/Arabic Bugs

### ISSUE THREAD

**Issue by louy** [mozilla/r2d2b2g#848]
When using the firefox os in Arabic language there are some critical bugs:
- Home screen swipe works in the opposite direction (swiping to the right opens the left page...)
- Wrong margin in apps (double margin on the right and no margin on the left.)
- There's also a bug in the back button, it shows black space instead of the button. (settings app)

**Comment by louy** [comment]
There's also a bug in the slide animation, wrong direction.

**Comment by anefzaoui** [comment]
Hello :) The bugs you are speaking about are not related to the Simulator, instead, they are related to Gaia, the OS interface. I am very aware of every single bug of them and we are working on fixing those bugs as soon as possible :)
Thanx :)

**Comment by louy** [comment]
You mean https://github.com/mozilla-b2g/gaia, I just realised that :)
There's no issues page there btw. Thanks and I hope to see it fixed soon.

**Comment by anefzaoui** [comment]
We use Bugzilla ( http://bugzilla.mozilla.org/ ) for tracking issues of all Mozilla products.. Then patches land on Github :) When you face a bug.. You can look for it on Bugzilla.. If you can't find it, you can still file it :)
