### ISSUE TITLE
Screen: Everything news

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#85]
You can click for example the "news" icon on the Everything screen, but when you'll try to click the "CNN" app, it won't respond to the click.

**Comment by mykmelez** [comment]
In general, we're not going to address issues with the default apps, as our focus is helping app developers test their own apps. There will be some exceptions for apps that are useful to app developers, like Firefox and Settings. But the Everything app isn't one of those.

It's still useful to report problems in those apps! But you should probably confirm the problem in another B2G (the standard distribution of B2G Desktop or a B2G testing device) first, as these problems might be specific to the way B2G Desktop is wrapped and invoked in the simulator.
