### ISSUE TITLE
Can't see PUSH to device button

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#864]
Can't see PUSH to device button after I connected the device and installed USB drivers. 

adb devices can see it as a KEON device

**Comment by ghost** [comment]
UPDATE: after restart the device I can see my "push" button, I click on it and the device show "XY app installed" 
but I cannot see it on the device as an icon :(

**Comment by ghost** [comment]
OK, and an other RESTART solved my probleme again...something not good here

**Comment by mykmelez** [comment]
Hi @lacasrac, sorry to hear about your problems! It sounds like you experienced a combination of #441 and #452. Read those issues for more details!
