### ISSUE TITLE
FirefoxOS Simulator: missing SD

### ISSUE THREAD

**Issue by Mte90** [mozilla/r2d2b2g#866]
I try to use a web activity for pick the image but when i choose gallery i get an alert message that say to me that the sd is missing.
In the settings page it's impossible change the media location.
There is a way for use the gallery on the simulator?

**Comment by Shura0** [comment]
+1. I also has faced with such limitation when tried to use navigator.getDeviceStorage.

**Comment by rmader** [comment]
+1
i'd like to write a encfs implementation for local data, but don't have a own device yet. It would be awesome to atleast have some kind of readonly dummy filesystem.
Even if it's hardcoded in the emulator. Just something :)

**Comment by jryans** [comment]
It is possible to access the SD card on a recent simulator but you have to create a [secret directory](https://bugzilla.mozilla.org/show_bug.cgi?id=996619#c4). Hoping to make this simpler soon.

**Comment by rmader** [comment]
Thanks for the information! That will do for me in the meantime.
