### ISSUE TITLE
Firefox OS Simulator Not running!

### ISSUE THREAD

**Issue by aeroaks** [mozilla/r2d2b2g#877]
I am running Arch Linux with Firefox 26.0.
I have downloaded and installed the Simulator Add-on yesterday. I tried to open the Simulator using File->Web Developers->Simulator. A new tab opens up with Simulator as 'Stopped'. When I try to Run the Simulator, a new window opens up with a starting message "Based on Mozilla Technology". Then the window closes with no error or log in console.
I am unable to figure out what is the problem.
Please Help. Sorry for lame questions, a newbie here.

**Comment by jryans** [comment]
What version of the Simulator add-on did you install?

**Comment by aeroaks** [comment]
Add-on Simulator 4.0.

**Comment by jryans** [comment]
This add-on version is not compatible with Firefox 26+. For those versions of Firefox, the Simulator is used via the App Manager. See here for more info: https://developer.mozilla.org/en-US/Firefox_OS/Using_the_App_Manager

**Comment by aeroaks** [comment]
Thanks! Will have a look and update!

**Comment by aeroaks** [comment]
I have downloaded Firefox OS 1.2 Simulator on my PC. When I open about:app-manager, it says "Not Connected.
No device found. Plug a device or Start Simulator" at the bottom. On clicking Start Simulator button it shows "No simulator installed." whereas when I see Add-ons Manager, Firefox OS 1.2 Simulator 6.0pre7 is installed.

What can I be missing?

**Comment by jryans** [comment]
Hmm... What OS are you running?

If you open the Browser Console (Tools -> Web Developer -> Browser Console) and try to start a simulator again, do you see any errors?

**Comment by iFadey** [comment]
Yes I am facing the same issue. I tried installing add-ons for both Firefox OS 1.2 and 1.3 beta but App Manager is unable to detect the installed simulators i.e. "Install Simulator" button still appearing in App Manager. I also tried to reset my Firefox from Troubleshooting Information and reinstalled the simulator but still not working. Then I created a new user account in my machine and tried installing simulator there but still same problem.

Ubuntu 12.04.3
Firefox 26

**Comment by skoro** [comment]
I am confirm, same issue. Firefox 26, Ubuntu 13.04 (amd64) and Ubuntu 12.04, after installing from App Manager simulator appears in addons page but App Manager not found simulator and propose to install. So, how get working simulator?

**Comment by jryans** [comment]
Unfortunately, there is currently an issue with Firefox 26 only. A fix has been made in #876.

We still need to release updated builds of the add-on to make the fix available, which should happen today.

Alternatively, you could use Firefox Beta or Aurora, as they don't have this issue.

**Comment by iFadey** [comment]
@jryans Thanks for the update

**Comment by aeroaks** [comment]
@jryans Thanks. Will try that.

**Comment by jryans** [comment]
Updated builds of the simulator add-ons have now be released, so if you make sure your add-on is updated to the latest build (6.0pre8 for 1.2 simulator and 7.0pre7 for 1.3 simulator), it should now also work on Firefox 26.
