### ISSUE TITLE
Create Feedback Application

### ISSUE THREAD

**Issue by syssgx** [mozilla/r2d2b2g#88]
It should be able to take a screenshot and have a comment for easy issue reporting to the dev team.

**Comment by mykmelez** [comment]
I like this idea, but it seems like the kind of thing that would make sense for the Web Developer tools or Firefox features as a whole, not just for this particular tool. After all, this is just one of many Web Developer tools, which are themselves a small subset of the features of Firefox, and it seems strange to give developers a feedback reporting option like this only for one of those features.

But @dangoor is the Product Manager for this and the other Web Developer tools, so perhaps he can provide some perspective.

**Comment by tofumatt** [comment]
Yeah this seems excessive. All platforms have the ability to take a screenshot and GitHub issues works just fine as a bug reporter.

We shouldn't reinvent any wheels here.
- tofumatt (Sent from mobile)

**Comment by dangoor** [comment]
I agree that we don't want to dig in for this as part of r2d2b2g. I would certainly like to see less friction in providing feedback. There's actually a screenshot command in the developer toolbar. And, Aurora and Beta both have feedback buttons (though what you can enter there is very limited).

For now, I think it's enough to tell people to come here to file issues.

**Comment by mykmelez** [comment]
Ok, closing based on @tofumatt's and @dangoor's comments.
