### ISSUE TITLE
geolocation does not work

### ISSUE THREAD

**Issue by Shura0** [mozilla/r2d2b2g#884]
Simulator does not get my current location, it always uses predefined location in San Francisco.

**Comment by jryans** [comment]
What version of the Simulator addon are you using, and what version of Firefox?

**Comment by Shura0** [comment]
I tried 1.2 and 1.3 simulators on the latest 29.0 nightly build.
Geolocation in firefox works well, but in simulator does not.
OS is Linux

**Comment by jryans** [comment]
Ah okay, the geolocation functionality hasn't yet been included in the newer simulators. You can follow the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=925761) on this for more updates.
