### ISSUE TITLE
User Agent in the FirefoxOS Simulator incorrect [1.2 and 1.3]

### ISSUE THREAD

**Issue by markknol** [mozilla/r2d2b2g#888]
The simulators logs as UserAgent : `"Mozilla/5.0 (Mobile; rv:18.0) Gecko/18.0 Firefox/18.0"`  
This is incorrect according this information: https://developer.mozilla.org/en-US/docs/Gecko_user_agent_string_reference#Firefox_OS

This is the case in the simulator version 1.2 and 1.3. I'm _not_ using a development/forked version.

Windows 7, Firefox 27.0.1

**Comment by jryans** [comment]
Yep, this is a known issue. We're tracking this here: https://bugzilla.mozilla.org/show_bug.cgi?id=964598
