### ISSUE TITLE
Cannot use FxOS Simulator on Firefox 23 or under

### ISSUE THREAD

**Issue by felipekm** [mozilla/r2d2b2g#896]
I Have a device with the 1.1 version and now I'm not able to deploy on this.
I've tried to install both 24 and 25 versions but I couldn't find the FireFox Simulator Item to open it.

Could someone help?
FF for Windows 7 OS

**Comment by jryans** [comment]
What version of the add-on do you have?

**Comment by felipekm** [comment]
I did it! Actually I was thought that this add was only able to install on 25 or 24 versions of FF, now I just tried to install this add-on https://addons.mozilla.org/pt-br/firefox/addon/firefox-os-simulator/ on 30 version and it works. Thanks @jryans :+1:

**Comment by jryans** [comment]
We just released an updated version of the add-on in the last 24 hours to work with Firefox 30+, so that probably explains the change. :smile: Glad it's working for you!

**Comment by felipekm** [comment]
What a coincidence! It definitely works ;)

**Comment by AprilMorone** [comment]
Awesome. Can't wait to try it.  :)
