### ISSUE TITLE
Firefox OS Design Issue

### ISSUE THREAD

**Issue by hackalone** [mozilla/r2d2b2g#898]
just got a new Cherry Mobile Phone powered by Firefox OS. i input a simple payload to test the search box. 
![searchbox](https://cloud.githubusercontent.com/assets/7557313/5281752/6c743674-7b3b-11e4-9443-0b4efbfc20d5.png)

then i input this code for XSS payload testing please see the image
![searchbox payload test](https://cloud.githubusercontent.com/assets/7557313/5281790/bd205bfc-7b3b-11e4-81b8-a67966490dd0.png)
no pop-ups, no alert or even a prompt but i notice the response of the search box asking for internet connection to get the app.
![broken image](https://cloud.githubusercontent.com/assets/7557313/5281844/219e7ec4-7b3c-11e4-9f3b-c1cd9eb03bfe.png)
I know this is not a security issue but i think this issue needs to be fix?
but when i tried to use the search box with internet no issue.

thanks and regrads

**Comment by jryans** [comment]
This repo is for the b2g simulator. I would suggest contacting the dev-gaia or dev-b2g mailing lists.
