### ISSUE TITLE
Extension causes Firefox to crash

### ISSUE THREAD

**Issue by jesobreira** [mozilla/r2d2b2g#901]
Hi!

I was coding an app as usually with FxOS Simulator and my LG Fireweb (LG broke the contract with Mozilla and didn't release any update for it), but it just stopped working suddenly. No update was done. Now, although Firefox works like usually, if I open FxOS Simulator it freezes Firefox window completely, and I'm unable to change tabs or even start the simulator (the entire Firefox window stops responding to clicks and I must close it with `killall firefox`). It crashes in any way, if my cellphone is plugged in or not.

I'm using Elementary OS Luna (x64 machine) and Firefox 41, never had that problem before. I tried removing and adding the extension as well as reinstalling Firefox, no luck.

**Comment by jryans** [comment]
What version of Firefox OS is on the phone?

**Comment by jesobreira** [comment]
1.1
Unfortunately LG never updated it nor released the bootloader (but it always worked well).
Also, it freezes even if I don't have my device connected.

**Comment by jesobreira** [comment]
I'm able to run Firefox OS Simulator using Firefox running on Wine. But it does not detect my device plugged on.

But when I try running Firefox OS Simulator on the native Firefox, it freezes as soon as I open it.

**Comment by jesobreira** [comment]
More updates... I've tried running Firefox as root, as well as downloading it from the Mozilla official website, unpacking and executing `./firefox`, as root and not. I also tried deleting the folder `~/.mozilla`. No success with Firefox OS Simulator. I can't imagine myself using Windows again, it's sad that in Brazil we have currently only FxOS 1.1 devices so far...

**Comment by jryans** [comment]
As a workaround, is it possible to use an older version of Firefox to access this add-on?

If so, what is the last version that works correctly?

**Comment by jesobreira** [comment]
Hi, I've tried with Firefox 25, as [this page](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_1.1_Simulator) tells about its compatibility. No success, however. The same thing happens. I also removed the `~/.mozilla` folder before running Firefox 25 (and I made sure I was really running this version by accessing Help > About).

No update was provided when it stopped working. No changes were done, profile removal/default resets on the Firefox browser or at the device side. They're really the same. I've used Firefox 41 since I installed my OS, and I never had had any problem. The problem started suddenly, with no clear reason.

As a detail, I'm able to access the device through `adb`, and even get into its interactive shell through `adb shell` with no problem, but I didn't figure out how to push my apps to my device and debug it (get its console output).

Would it be possible to use Firefox OS Simulator with some derivative? As soon as I have time, I will take a try with Iceweasel and Aurora.

**Comment by jesobreira** [comment]
Wew :no_mouth: 

I've also had problems with FxOS Simulator on Windows, but my Windows partition is a lost case, it's full of problems (it runs Windows...) and I only boot it when I really need (although I avoid more than possible). So I don't care, but...

Running Firefox (latest version) and FxOS Simulator (latest version) through Playonlinux (Wine wrapper) is working now! I can run my apps on the simulator or even push it to my device. Amazing! Although it's not native environment, everything is working well so far!

I'll let you updated if something stops working, but so far I am happy with Wine lol

**Comment by jryans** [comment]
Okay, I'm glad it's working even if it's through Wine. I am not aware of any changes to Firefox or the Simulator that would have suddenly caused this to happen, so it sounds like it might be something specific to your machine, but it's hard to say for sure.

I'll close this issue for now, but if you find more info that suggests something in Firefox or the Simulator did change, we can reopen it.
