### ISSUE TITLE
Operation Failed : Connecting To Firefos OS 2.2

### ISSUE THREAD

**Issue by YashSinghal1** [mozilla/r2d2b2g#902]
getting this problem

**Comment by mykmelez** [comment]
This project hasn't been maintained, so issues aren't going to get resolved. The README redirects to the [mozilla-central repository](https://hg.mozilla.org/mozilla-central/), but the simulator has been removed from that repository as well. And I don't see its code in the [B2G repository](https://github.com/mozilla-b2g/B2G) either. So unfortunately I don't know where you can go to report this issue. ☹️
